### ISSUE TITLE
Unnecessary warning message when calling `between` with Date variables

### ISSUE THREAD

**Issue by jlegewie** [tidyverse/dplyr#2766]
Title says it all. I don't think the warning message makes sense here. All variables are `Date`. I guess some get converted and others don't, which produces the warning.

```r
d <- as.Date(c("2010-08-14", "2010-12-19"))
between(d, as.Date("2010-09-14"), as.Date("2011-09-14"))
# Warning message:
# between() called on numeric vector with S3 class 
```

**Comment by odeleongt** [comment]
I've asked myself the same thing, and just now bothered to look into the code.

This happens because `between` is [implemented in Cpp](../blob/14b5d128c3/src/between.cpp) as a simple numeric comparison for efficiency. There is no obvious issue for comparing three vectors with the same S3 class (such as `Date`s) and `numeric` mode, but a few issues easily come to mind for more general use. Two simple examples:

- What if you compare dates (class `Date`) with times (`POSIXct`)? Both have a `numeric` storage mode, thus could be compared by `dplyr_between` in Cpp. But... the `Date` representation will always be smaller than the `POSIXct` represantation for any given date after the epoch (and larger before the epoch).

```
# Now is always between yesterday and tomorrow, right?
between(Sys.time(), Sys.Date() - 1, Sys.Date() + 1)
## [1] FALSE
```

- Factors also have a `numeric` storage mode, so can be compared by `between`. But... in order to be comparable, both factors should have the same levels. Also, this kind of comparison only would make sense for `ordered` factors.

```
# b and d right?
between(factor(c("a", "b", "c")), factor("b"), factor("d"))
## [1]  TRUE FALSE FALSE
```

So the warning is needed. And I'd probably go as far as raising an error if any of `x`, `start` and `end` has a different class from the others.

**Comment by odeleongt** [comment]
Then the issue boils down to efficiency and simplicity against generality and robustness.

A simple fix would be creating a generic `between` function with the current implementation as `between.default` and let S3 dispatch for some well defined cases (*e.g.* all of `x`, `start` and `end` having class `Date`, coerce to `numeric` and dispatch to default). But how to go about the necessary methods?
