### ISSUE TITLE
Not able to use tbl to preview remote data table in teradata

### ISSUE THREAD

**Issue by happyshows** [tidyverse/dplyr#2799]
Hi,

I'm using RJDBC to connect to TERADATA and execute SQL statement. I'd like to follow the example on [tutorial](https://rviews.rstudio.com/2017/05/17/databases-using-r/) but it didn't work for me at tbl step. It seems to append the incompatible 'LIMIT 10' instead of 'TOP 10' in the sql statement.

Is this a JDBC issue or dplyr issue? How to override it on my side?

```
> tbl(conn,'TABLENAME')
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT *
FROM "TABLENAME"
LIMIT 10 ([Teradata Database] [TeraJDBC 15.00.00.33] [Error 3706] [SQLState 42000] Syntax error: expected something between the word 'TABLENAME' and the 'LIMIT' keyword.)
```

**Comment by hadley** [comment]
You need to write a custom backend. See http://dbplyr.tidyverse.org/articles/sql-translation.html and http://dbplyr.tidyverse.org/articles/new-backend.html for details. You might be able to crib code from the MS SQL backend which also uses TOP instead of LIMIT: https://github.com/tidyverse/dbplyr/blob/master/R/db-odbc-mssql.R
