### ISSUE TITLE
Regression bug: can't `return()` from inside a dplyr::do()

### ISSUE THREAD

**Issue by daattali** [tidyverse/dplyr#2804]
Related to https://github.com/tidyverse/dplyr/issues/2745

The following code works:

```
dplyr::do(dplyr::group_by(mtcars, cyl), head(., 2))
```

The following code results in an error: (just added a return statement)

```
dplyr::do(dplyr::group_by(mtcars, cyl), return(head(., 2)))
```

Error:

```
Error in overscope_eval_next(overscope, args[[j]]) : 
  no function to return from, jumping to top level
```

session_info:

```
Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_Canada.1252         
 tz       America/New_York            
 date     2017-05-18                  

Packages ---------------------------------------------------------------------------
 package    * version     date       source                           
 assertthat   0.2.0       2017-04-11 CRAN (R 3.3.3)                   
 base       * 3.3.3       2017-03-06 local                            
 datasets   * 3.3.3       2017-03-06 local                            
 devtools     1.13.0.9000 2017-05-10 Github (hadley/devtools@c071299) 
 digest       0.6.12      2017-01-27 CRAN (R 3.3.3)                   
 dplyr        0.5.0.9005  2017-05-18 Github (tidyverse/dplyr@bf53ac1) 
 glue         1.0.0       2017-05-15 Github (tidyverse/glue@41a5cff)  
 graphics   * 3.3.3       2017-03-06 local                            
 grDevices  * 3.3.3       2017-03-06 local                            
 magrittr     1.5         2014-11-22 CRAN (R 3.3.3)                   
 memoise      1.1.0       2017-04-21 CRAN (R 3.3.3)                   
 methods    * 3.3.3       2017-03-06 local                            
 R6           2.2.1       2017-05-10 CRAN (R 3.3.3)                   
 Rcpp         0.12.10     2017-03-19 CRAN (R 3.3.3)                   
 rlang        0.1.1.9000  2017-05-18 Github (tidyverse/rlang@f419e09) 
 stats      * 3.3.3       2017-03-06 local                            
 tibble       1.3.1       2017-05-18 Github (tidyverse/tibble@8f30072)
 tools        3.3.3       2017-03-06 local                            
 utils      * 3.3.3       2017-03-06 local                            
 withr        1.0.2       2016-06-20 CRAN (R 3.3.3)
```

**Comment by hadley** [comment]
Why you expect `return()` to work here?

**Comment by daattali** [comment]
Because I expect to be able to return from anywhere within the `do()` block, not only from the last line. 

From the function documentation:

```
You can use do() to perform arbitrary computation, returning either a data frame or arbitrary objects which will be stored in a list.
```

What if you want to return something conditionally/prematurely? (That's my actual usecase, the bug report is a minimal reprex)

It works fine with CRAN version.

**Comment by hadley** [comment]
If you want to return early, write a proper function. I'd say this is out of scope for `do()`.

**Comment by daattali** [comment]
I don't mind rewriting my code, but I imagine there are other people who have existing code that returns inside a `do()`. The documentation uses the word "return" a few times so IMO it's a bit dangerous to break this functionality

**Comment by hadley** [comment]
Unfortunately it's too late to make any fixes for this version of dplyr.

**Comment by lionel-** [comment]
I know what's going on now, `Rf_eval()` doesn't create a context that can be returned from, unlike the R function `eval()`. So `return()` might have worked in `do()` because it was based on `base::eval()` but wouldn't have worked in other verbs like `mutate()`. For the same reason, `on.exit()` should have worked in the previous `do()` version but shouldn't work anymore.

Maybe R core needs to export the internal `eval()` primitive function so we can create a new returnable context from C code without the messy stack that R-level `base::eval()` creates.

These caveats should be documented in `rlang::eval_bare()`.

**Comment by ghaarsma** [comment]
This change in behavior between v 0.5.0 and later tripped us up in a significant way.  We have (had) lots of anonymous do functions with returns in them. 

Simple example:
```R
  library(dplyr)

  # Remove duplicate rows in x1, bases on alfabetic order in x2
  l=1e4
  df <- data.frame(x1=1:l,x2=LETTERS[1:26][sample(26,l,replace = TRUE)])
  # create 10 duplicates
  df$x1[sample(l-10,10,replace = FALSE)+10] <- 1:10

  # Does not run in 0.7.2
  group_by(df,x1) %>% do(if (nrow(.)==1) return(.) else {x=arrange(.,x2);return(x[1,])})

  # Change anon do function to make it work
  group_by(df,x1) %>% do(if (nrow(.)==1) . else arrange(.,x2)[1,])
```
Agree with  @daattali, that I don't mind rewriting the code. But this breaks existing functionally. For a R novice or non-github expert its hard to find out code that used to run just fine stopped working or how to fix it.

Don't know if a fix to previous functionality is forthcoming. If not, I'd be happy to put in a pull request to update the documentation.

**Comment by smsaladi** [comment]
This change since v0.5.0 also caused me trouble. An update to the docs or more informative error would be nice.

**Comment by lionel-** [comment]
I think the correct behaviour for `return()` should be to return from the current lexical scope. I.e. it wouldn't return from `do()` but from the function that contains it. I think I see a way of achieving this. 
What do you think @hadley?

Note that it would still break your code because you were using an undocumented and wrong behaviour of `return()`. So it's a good thing that it started to fail verbosely because otherwise the bugs would have been more surprising the moment we fixed return. The error message is plenty informative, unless you were using dplyr inside a function and in that case it makes it clear what the bug is: tidy eval thinks there is no function to return from even though there is one.
