### ISSUE TITLE
select() with list argument

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2817]
``` r
dplyr::select(list(1:3))
#> Error in select.list(list(1:3)): select.list() cannot be used non-interactively
```

This still happens even if I override `select.list` in the package. I guess the `utils::select.list()` function takes precedence for some reason.

This affects the emil and lplyr downstream packages.

**Comment by krlmlr** [comment]
Note that this works as expected when `select()` is defined in a script:

``` r
select <- function(x, ...) UseMethod("select")

select.default <- function(x, ...) "select.default"

select.list <- function(x, ...) "select.list"

select(letters)
#> [1] "select.default"
select(1:3)
#> [1] "select.default"
select(list(1:3))
#> [1] "select.list"
```

**Comment by krlmlr** [comment]
Asked on R-pkg-devel: https://stat.ethz.ch/pipermail/r-package-devel/2017q2/001608.html

**Comment by lionel-** [comment]
I think if you export a `select.list()` function from dplyr it should work. Note that the roxy directive `@export` doesn't export it but only register it in the namespace, so you'd have to do it with `@rawNamespace`.

If I'm not mistaken, dispatch occurs in two passes. The first pass scans the search path for dotted methods, then the second looks into the namespace of the generic for the list of registered methods. If you're only registering a `select.list()` method, it will never be called because the first scan always picks up the pseudo-method from the utils package.

**Comment by krlmlr** [comment]
I see. Actually, this works for the select package, but e.g. not for emil which selectively [imports `select()`](https://github.com/cran/emil/blob/49d80dafe66d339b83303c1442e01a226a6bd598/NAMESPACE#L157). It seems that if we introduce a new `select()` generic the emil package breaks and we can't do anything about it.

How about prefixing all the new generics we define (such as `filter()`, `select()`, and `slice()`) with `dplyr`, this would fix quite a few downstream errors:

```r
filter <- function(...) dplyr_filter(...)
dplyr_filter <- function(x, ...) UseMethod("dplyr_filter")
```

CC @hadley

**Comment by hadley** [comment]
I think it's probably too late to make this change.
