### ISSUE TITLE
Database backed tables throw when attempting to `dplyr::mutate()` in a vector value

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2870]
Database backed tables throw when attempting to `dplyr::mutate()` in a vector value.  Related to [sparklyr issue 717](https://github.com/rstudio/sparklyr/issues/717) and [dplyr issue 2830](https://github.com/tidyverse/dplyr/issues/2830).  Re-submitting as a much simpler example (adding a constant column, so is order independent) that is now free of `sparklyr` dependencies.

``` r
# set up
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
packageVersion("dbplyr")
#> [1] '1.0.0'

d <- data.frame(x = 1:3)
v <- rep(1, nrow(d))

# expected behavior
d %>% 
  mutate(y = v)
#>   x y
#> 1 1 1
#> 2 2 1
#> 3 3 1

# db vector behavior (throws)
dS <- dbplyr::memdb_frame(x = 1:3)
dS %>%
  mutate(y = v)
#> Error in rsqlite_send_query(conn@ptr, statement): near ",": syntax error
```

**Comment by edgararuiz** [comment]
Hey @JohnMount, can you post the query that results from passing the following code please?

```
show_query(dS %>% mutate(y = v) )
```

**Comment by JohnMount** [comment]
Sure, here you are:

```r
show_query(dS %>% mutate(y = v) )
#> <SQL>
#> SELECT `x`, (1.0, 1.0, 1.0) AS `y`
#> FROM `jjbrkkcdlz`
```

**Comment by edgararuiz** [comment]
This is a very interesting problem.  The issue is that this kind of operation inside `mutate` is in essence uploading data to the database.  And the only way I'm able I can think we can do this in SQL is to essentially create a Temp table and then join it to the main query.  This requires a sort of out of sync operation of moving the `y` variable's data to the beginning of the query and then bring it in as a join.  This is very similar to the challenges of creating temp tables for the larger DB vendors, I come back to a possible solution using `tbl_lazy()` somehow to hold on to the data that can then be passed as a variable table in the final query.

**Comment by MZLABS** [comment]
I agree: the only reliable way to do this on DB backends (and Spark) is a join. But beyond the implementation details that also requires keys (which there may not even be).  Would the right answer possibly be to throw if the mutate value is coming from outside the DB and is not a scalar?

**Comment by MZLABS** [comment]
Actually it would be really nice if the db-backends gave a nicer error message in the case where one tries to insert a vector value from `R` and the length of the vector is neither 1 nor the number of rows in the table.

``` r
# set up
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
packageVersion("dbplyr")
#> [1] '1.0.0'

d <- data.frame(x = 1:3)
dS <- dbplyr::memdb_frame(x = 1:3)
v <- rep(1, 2)

# Would like the following two exceptions to cary similar messages

tryCatch(
  d %>%
    mutate(y = v),
  error = function(e) { print(e) }
)
#> <Rcpp::exception in mutate_impl(.data, dots): Column `y` must be length 3 (the number of rows) or one, not 2>

tryCatch(
  dS %>%
    mutate(y = v),
  error = function(e) { print(e) }
)
#> Error in rsqlite_send_query(conn@ptr, statement): near ",": syntax error
```

**Comment by hadley** [comment]
The only thing I can do here is throw a better error message, and even then it's going to be a lot of work because I'll need to carefully consider where it is ok to include vectors in generated sql (i.e. after `IN`) and where it is not ok.  Given that this is a relatively rare use case, and you already get an error (albeit not a clear one), this is unlikely to ever rise to the top of my to do list.

However, I'd be happy to review a PR. If someone else wanted to implement it, I think the best place to start would be to add a `allow_vector_values` to `translate_sql_` and thread it through all the functions calls until it gets to `escape()` and then `sql_vector()`. In `sql_vector()` if `length(x) > 1` and `allow_vector_values = FALSE`, you'd throw an error.  I suspect prohibiting vector values just at the top level would be sufficient but I'd need to think deeply about that to be sure.
