### ISSUE TITLE
enquo causes an error but substitute works

### ISSUE THREAD

**Issue by 33Vito** [tidyverse/dplyr#2918]
Hi, 

Just reporting an issue I found. I thought _enquo_ and _substitute_ are equivalent. However, 

This works: 

```r
ff2 <- function(var1, var2) {
  var <- substitute(var1:var2)
  select(mtcars, !!var)
}

ff2(mpg,hp)
```

This does not:

```r
ff <- function(var1, var2) {
  var <- enquo(var1:var2)
  select(mtcars, !!var)
}

ff(mpg,hp)
```

I know I can swap _var1_, _var2_ with just _var1:var2_, but would like to know the difference between _enquo_ and _substitute_ here.

**Comment by lionel-** [comment]
`enquo()` is much simpler than `substitute()`. Its only purpose is to capture the code supplied as argument. It thus takes a bare symbol representing that argument. By contrast, `substitute()` accepts complex expressions and proceeds to substitute any locally defined symbol.

To reproduce `substitute()` behaviour with quosures, you can "substitute" manually by unquoting within a new quosure:

```r
quo(UQ(enquo(var1)) : UQ(enquo(var2)))
```

I'm using `UQ()` instead of `!!` to avoid issues of operator precedence with `:`
