### ISSUE TITLE
group_by() does not like POSIX date objects.

### ISSUE THREAD

**Issue by doorisajar** [tidyverse/dplyr#293]
Using the hflights example... save your workspace and script files before running this; the last line will crash your R instance. 

```
library(hflights)
library(dplyr)
library(lubridate)

hflights$Date <- paste(hflights$Year, hflights$Month, hflights$DayofMonth, sep = "-")
hflights$POSIX <- parse_date_time(hflights$Date, "%Y%m%d")

hflights_df <- tbl_df(hflights)
hflights_df

# This one is fine.
group_by(hflights_df, Date)

# This one is not fine!
group_by(hflights_df, POSIX)
```

**Comment by modqhx** [comment]
Same here.. 
```
df$fb_post_created <- as.strptime(df$blog_created, "%Y-%m-%d %H:%M:%S", tz="America/New_York")
```
On using filter command, I get: 
```
Error: column 'blog_created' has unsupported type : POSIXlt, POSIXt
```

**Comment by MGousseff** [comment]
same here

**Comment by cderv** [comment]
@MGousseff this issue is more than one year old now. And it seems ok for the first asker. 
You should provide a new [reprex](http://reprex.tidyverse.org/) if you think this is still the same issue. 
Do not hesite to ask on [SO](https://stackoverflow.com/questions/tagged/r) or [RStudio community](https://community.rstudio.com/) to improve the chance of quick answer for getting some help.
