### ISSUE TITLE
Can't join by list columns

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/dplyr#2957]
When trying to join by list columns I get the following (incorrect!) error message:

```
Error in left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) : 
  Can't join on 'X' x 'X' because of incompatible types (list / list)
```

Below an example:

```
library(dplyr)

x <- tribble(
  ~ X,
  list(1),
  list(1:2),
  list(3)
)

y <- tribble(
  ~ X,
  list(1),
  list(1:2),
  list(5)
)

left_join(x, y, by = "X")
```

It would be great if it was possible to join by list columns, or at least the error message would inform that this is not possible.

**Comment by bhive01** [comment]
Hello, you can in fact do this as I just recently discovered, but it's definitely more clunky than anticipated:
https://stackoverflow.com/questions/45062277/join-across-within-nested-dataframes
I'm not sure your example makes a lot of sense because if you're joining by the list column, what are you joining? You need another data column. 

```r
x <- tribble(
  ~ X,
  list(1),
  list(1:2),
  list(3)
) %>%
		mutate_all(funs(hash = map_chr(., digest::digest)))

y <- tribble(
  ~ X,
  list(1),
  list(1:2),
  list(5)
) %>%
		mutate_all(funs(hash = map_chr(., digest::digest)))

dplyr::left_join(x, y) 
```

**Comment by krlmlr** [comment]
Thanks for reporting. https://github.com/tidyverse/dplyr/issues/2355 is the canonical issue for this problem.
