### ISSUE TITLE
Relax Rcpp check in R/zzz.R

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2966]
Perhaps compare only the first three places of the version number?

Request by @eddelbuettel.

**Comment by eddelbuettel** [comment]
There is more:
- optionally silence the test alltogether -- i.e. when I develop with Rcpp and have different (changing) minor versions (because that's what I do, and having different versions to _differentiate_ builds is a Good Thing (TM)) -- as I don't need reminders about different versions.   Other folks may feel the same.
- I have yet to see a crash caused by this in 10 years with Rcpp, apart from one or so inadvertent API change so the whole idea strikes me (strictly personally speaking) as wrongheaded.  YMMV.
- `s/Request/Suggestion/`

**Comment by eddelbuettel** [comment]
This has now been brought up by CRAN, and it has been requested that the check be removed.

You could keep it behind something like  `if (getOptions(dplyrDebugMode, default=FALSE))`

**Comment by eddelbuettel** [comment]
```patch
diff --git a/R/zzz.r b/R/zzz.r
index 8d83ee9..66bbc64 100644
--- a/R/zzz.r
+++ b/R/zzz.r
@@ -3,12 +3,11 @@ Rcpp_version <- utils::packageVersion("Rcpp")
 R_version <- R.version.string
 
 .onLoad <- function(libname, pkgname) {
-  if (Rcpp_version != utils::packageVersion("Rcpp")) {
-    warning(
+  if (getOption("dplyrDebugMode", FALSE) && Rcpp_version != utils::packageVersion("Rcpp")) {
+    packageStartupMessage(
       "Installed Rcpp (", utils::packageVersion("Rcpp"), ") different from ",
       "Rcpp used to build dplyr (", Rcpp_version, ").\n",
-      "Please reinstall dplyr to avoid random crashes or undefined behavior.",
-      call. = FALSE
+      "Please reinstall dplyr to avoid random crashes or undefined behavior."
     )
   }
 
```

**Comment by eddelbuettel** [comment]
This issue is **not closed** for as long as you have the offensive (to Rcpp) text in there.
