### ISSUE TITLE
select no longer allows you to create new variables

### ISSUE THREAD

**Issue by Robinlovelace** [tidyverse/dplyr#2986]
I think this used to work on the previous version of **dplyr**. Was this breaking change intended? Please close if so (I know you can get the answer using mutate):

``` r
library(dplyr)
#> Warning: Installed Rcpp (0.12.12) different from Rcpp used to build dplyr (0.12.11).
#> Please reinstall dplyr to avoid random crashes or undefined behavior.
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
iris <- as_tibble(iris)  # so it prints a little nicer
names(iris)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width" 
#> [5] "Species"
# select(iris, a = Sepal.Length) # no problem
select(iris, a = Sepal.Length/Sepal.Width)
#> Error in overscope_eval_next(overscope, expr): object 'Sepal.Length' not found
```

Reporting as this affected some code that used to work in case this was not the intended behaviour.

**Comment by lionel-** [comment]
I don't think this has ever worked the way you intended it. If it worked before, it was circumstantial and your code was probably silently broken.

`select()` has different semantics: data symbols like `Sepal.Length` represents column positions, so your `/` call was actually computing base on scalar integers. I'm surprised you never got an error of some kind.

Anyway, this code now fails with a "not found" error because all calls are now evaluated outside of the data context. This change makes it easier to have calls like `var <- "Sepal"; select(iris, starts_with(var))`.

**Comment by Robinlovelace** [comment]
Thanks. It did work: 

https://github.com/cyipt/cyipt/commit/f1a2c7f0665e1905f1d3122ed5e01756beed1da6#diff-e88337e1bf1782d71fa7184f01441009R286

That generated this: https://github.com/cyipt/cyipt/blob/master/model-uptake.md

In any case I can see that's not what `select()` was designed to do, hence saying 'close if it is intentional'. I posted in the assumption that use cases that change would be useful for developers.
