### ISSUE TITLE
add_tally or add_count feature to specify the new variable name

### ISSUE THREAD

**Issue by andresimi** [tidyverse/dplyr#3001]
Feature request: 
When we use add_tally or add_count it generates a new variable named "n". It would be nice to have an argument where we could specify the new variable name. I think the code would be clearer.

Thanx

**Comment by lionel-** [comment]
Maybe it'd make sense to allow `:=`?

**Comment by philstraforelli** [comment]
Would be nice if this option could be extended to `count()` and `tally()` as well.

**Comment by hadley** [comment]
I think `count()` and `tally()` are already sufficiently complicated. If you want to specify the name, just do the summary yourself.

**Comment by jzadra** [comment]
My two cents, since I encounter this issue often:

I agree that it is unnecessary for `count()` and `tally()` where only one count column is generated.  

However for `add_count()`, given that often multiple count columns are added, being able to name the new column would be much cleaner, since ending up with `n`, `nn`, `nnn` is no good, and having to do a

```
df %>%
add_count(x) %>%
add_count(y) %>%
rename(countx = n,
county = nn)
```

is prone to breakage since `n`/`nn` is dependent on order (and even doing renames in between seems messy).

naming the output of `add_count()` like `add_count(countx = x)` doesn't seem overly complicated.
