### ISSUE TITLE
inner_join() and SET_STRING_ELT() error

### ISSUE THREAD

**Issue by ThierryO** [tidyverse/dplyr#3012]
I'm being bugged with a strange error. One of the unit tests of my package yields `Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'character'`. I have no idea what is going wrong.

The strange thing is that the error is not reproducible, even though I'm using a stable Docker image (including all dependencies) in a CI environment. In [this run](https://app.wercker.com/INBO-Natura2000/n2kanalysis/runs/build/598353f93b92d9000166d0ca?step=59835476f250ac0001bd3328) it failed, but in [this run](https://app.wercker.com/INBO-Natura2000/n2kanalysis/runs/build/598367f133541e0001f89cc6?step=5983687bf250ac0001be1691) is doesn't fail. Both runs start from the same commit of my package.

**Comment by lianos** [comment]
I think I'm having the same issue! 

@ThierryO: does your test case involve using `group_by`?

This has been a sneaky one because it felt like it would sometimes work and sometimes not, but what I have (very strangely) found is that rerunning the code block that fails on the third time reliably makes it work.

I have tested this on two different machines (linux and macOS sierra) and the same thing happens.

I've tried to make a reproducible example using smaller simulated data, but I just couldn't figure it out, so I am providing an `*.rda` file that has two data.frames that can be downloaded via [this dropbox link](https://dl.dropboxusercontent.com/u/877320/dfs.rda).

You will need to fire up a new R session, then:

```r
library(dplyr)
nms <- load('~/tmp/dfs.rda')

tx.info <- tx.info.all %>%
  group_by(gene_id) %>%
  mutate(txname=sprintf("%s_%d", symbol, seq(n()))) %>%
  ungroup %>%
  ## mutate(txname='xxx') %>%
  transmute(feature_type="enstid",
            feature_id=transcript_id,
            name=txname,
            meta=transcript_type) %>%
  inner_join(tchrom.info, by=c("feature_id"="ensembl_transcript_id"))
```

The first time I run that dplyr chain, I get this error:

```
Error in inner_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) (from RcppExports.R#122) :
   Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'raw'
```

The second time I run it I get this error:

```
Error in inner_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) (from RcppExports.R#122) :
   Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'list'
```

The third time I run it, it works, and subsequent reruns also work.

If I restart R and run again, I keep getting the same fail, fail, success, success, success, ... success pattern.

Now restart R and get rid of the `group_by %>% mutate %>% ungroup` bits, things work:

```r
library(dplyr)
nms <- load('~/tmp/dfs.rda')

tx.info <- tx.info.all %>%
  mutate(txname='xxx') %>%
  transmute(feature_type="enstid",
            feature_id=transcript_id,
            name=txname,
            meta=transcript_type) %>%
  inner_join(tchrom.info, by=c("feature_id"="ensembl_transcript_id"))
```

**Comment by bhive01** [comment]
@lianos Thanks for the example and the exact data. Sadly, I'm unable to get the problem to happen even in a fresh session, but(!) my session_info() differs slightly from you, perhaps in a meaningful way(?).

``` r
Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       AQUA                        
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-08-15                  

Packages ------------------------------------------------------------------------------------------------------
 package    * version    date       source                          
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                  
 base       * 3.4.1      2017-07-07 local                           
 bindr        0.1        2016-11-13 cran (@0.1)                     
 bindrcpp   * 0.2        2017-06-17 cran (@0.2)                     
 compiler     3.4.1      2017-07-07 local                           
 datasets   * 3.4.1      2017-07-07 local                           
 devtools     1.13.0     2017-05-08 CRAN (R 3.4.0)                  
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                  
 dplyr      * 0.7.2.9000 2017-08-01 Github (tidyverse/dplyr@65db321)
 glue         1.1.1      2017-06-21 cran (@1.1.1)                   
 graphics   * 3.4.1      2017-07-07 local                           
 grDevices  * 3.4.1      2017-07-07 local                           
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                  
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                  
 methods    * 3.4.1      2017-07-07 local                           
 pkgconfig    2.0.1      2017-03-21 cran (@2.0.1)                   
 R6           2.2.2      2017-06-17 cran (@2.2.2)                   
 Rcpp         0.12.12    2017-07-15 cran (@0.12.12)                 
 rlang        0.1.1.9000 2017-08-01 Github (tidyverse/rlang@ff87439)
 stats      * 3.4.1      2017-07-07 local                           
 tibble       1.3.3      2017-05-28 cran (@1.3.3)                   
 utils      * 3.4.1      2017-07-07 local                           
 withr        1.0.2      2016-06-20 CRAN (R 3.4.0)          

```

**Comment by lianos** [comment]
@bhive01 thank you for taking the time to run and test my example and for pointing out that this (whatever it is) may be fixed in development.

I just `devtools::install_github("tidyverse/dplyr")` and tried again, and things ran smoothly the first time for me.

My dplyr version (and commit) match up with yours (`@65db321`).

I reckon the problem @ThierryO originally reported would also be fixed by now, but it would be interesting to confirm that.

Thanks again!

**Comment by krlmlr** [comment]
Thanks. It seems that #2976 is also related to an ASAN failure in a downstream package. Please open a new issue if problems persist.
