### ISSUE TITLE
copy_to and temporary tables

### ISSUE THREAD

**Issue by xhudik** [tidyverse/dplyr#3035]
sc <- spark_connect(master="local")
     copy_to(sc, iris, temporary=FALSE)
     DBI::dbSendQuery(sc,"show tables")@sdf %>% collect()

I get

| tableName | isTemporary |
-- | --
| iris | TRUE|

I suppose I should got **permanent** table instead of temporary

**Comment by edgararuiz** [comment]
Hi @xhudik , do you have this issue on other databases that are not Spark?  By definition, tables created in a Spark session are temporary because they will be lost as soon as the session is closed.   To make data permanent using `sparklyr`, you'll need to use one of the `spark_write...` functions, check out this page https://spark.rstudio.com/reference/index.html#section-spark-data.  If you believe that this is still an issue, I'd recommend opening an issue in the `sparklyr` repo instead of here.  Thanks.

**Comment by xhudik** [comment]
auch - i didnt know that spark creates temporal tables by default. I'm closing the issue - thx!
