### ISSUE TITLE
`select()` doesn't work with labelled logical vector when package `haven` is loaded

### ISSUE THREAD

**Issue by salim-b** [tidyverse/dplyr#3108]
I just stumbled upon a quite strange glitch in dplyr's `select()`:  
When selecting a logical vector of class `"labelled"`, the following error message is thrown – but only when the `haven` package is loaded at the same time:
```
`x` must be a numeric or a character vector`
```
If the logical vector is of any other class, everything's fine.

reprex:
``` r
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(haven)

df <- data_frame(logi_var = rep(T, 5))

attr(x = df$logi_var, which = "class") <- "labelled"

df %>% select(logi_var)
#> Error: `x` must be a numeric or a character vector

attr(x = df$logi_var, which = "class") <- "labelledd"

df %>% select(logi_var)
#> # A tibble: 5 x 1
#>   logi_var
#>      <lgl>
#> 1     TRUE
#> 2     TRUE
#> 3     TRUE
#> 4     TRUE
#> 5     TRUE
```

addendum: I'm using `dplyr 0.7.2` and `haven 1.1.0` with `R 3.4.1` on Ubuntu 16.04 LTS.

**Comment by foo-bar-baz-qux** [comment]
I get the same error, but I don't think this is an issue with `dplyr` (or `haven`).

Specifically, I believe what's happening is that the when printing a tibble, it will convert to a data.frame first, in the process calling the `labelled` constructor function  in the `haven` package to create the `labelled` data type.

According to the `haven` docs, for `labelled` vectors, only character and numeric vector inputs are allowed, while `rep(T, 5)` is going to produce a logical vector, causing the error. So the error is actually from`haven`. Essentially, `haven` labelled vectors aren't designed to store logical vectors, and they are supposed to also have a `labels` attribute as well. By setting the attribute directly without calling the `labelled` constructor, you need to make sure it the data has all the attributes you need, otherwise the behavior is going to be inconsistent/undefined since it's outside the scope of what `haven` or `dplyr` is expecting.

I think it's advisable to use the `labelled` constructor function instead when creating the tibble:
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(haven)

df <- data_frame(logi_var = labelled(rep(1, 5), c(A = 1, B = 2)))

df %>% select(logi_var)
#> # A tibble: 5 x 1
#>    logi_var
#>   <dbl+lbl>
#> 1         1
#> 2         1
#> 3         1
#> 4         1
#> 5         1
df$logi_var
#> <Labelled double>
#> [1] 1 1 1 1 1
#> 
#> Labels:
#>  value label
#>      1     A
#>      2     B
haven::as_factor(df$logi_var)
#> [1] A A A A A
#> Levels: A B
```

**Comment by salim-b** [comment]
@foo-bar-baz-qux Thanks for the explanation!

> Essentially, haven labelled vectors aren't designed to store logical vectors

But why not? Is there any specific reason to not support labelled logical vectors?

To be honest, before your post I didn't know anything about the interplay between `haven` and `dplyr` relying on some "standard" defined by what the `labelled()` function expects/allows. I just saw the `label` and `labels` attributes in some variables and found them to be very handy since e.g. RStudio automatically displays the `label` attribute when viewing a dataframe. In the current situation a user like me defining those attributes for a logical vector (which might admittedly be a little naive, but still: it's just attributes, they can be used for anything) simply gets confronted with some cryptical error message when trying to `select()` on it. I don't think this is a good situation... :confused:

**Comment by foo-bar-baz-qux** [comment]
I'm not sure why logical vectors aren't supported right now, I'm not that familiar with `haven`. You could use `1` for `TRUE` and `0` for `FALSE` right now, but you might also want to start an issue in the `haven` package to see if this might be a feature that can be added in the future.

**Comment by salim-b** [comment]
> you might also want to start an issue in the haven package to see if this might be a feature that can be added in the future

Did that in https://github.com/tidyverse/haven/issues/315 :slightly_smiling_face:

**Comment by hadley** [comment]
In general, you shouldn't construct your own objects that are somewhat similar to existing objects and then expect them to work. If you don't use the constructor, you're on your own.
