### ISSUE TITLE
Rstudio Connection issues w/ SAS SPDS 

### ISSUE THREAD

**Issue by jjacks12** [tidyverse/dplyr#3161]
I'm attempting to connect with a SPD server & use the tibble functionality provided in dbplyr.

I've set up an appropriate ODBC DSN as prescribed through SAS for the SPD server but upon connection I get the following errors:

"Parse Failure: invalid dictionary member"
"Parse Failure: select valye from #dictionary.macros where (name='SYSVLONG')"
"SQL Passthru experssion contained errors."

I can query for a listing of tables but whenever I attempt to pull a tbl:

"Error <SQL> 'SELECT * FROM (table name) as zzz1 WHERE (0=1)'"
    "nanodbc/nanodbc.cpp:1581:"

I've attempted SAS support but weren't of much help - I do know the DSN has been set up properly as I can link in tables from the SPD server in microsoft access.

**Comment by edgararuiz** [comment]
Hi @jjacks12 , this is more likely because `dplyr` will need a custom SQL translation for SAS.  From what I think it the SAS documentation for their SQL syntax, their standard is similar enough to what we already have in dbplyr for other databases, that most of the work would be to find the differences from the base that we use.  The issue is that we would need a DB to test against, which we don't ahve at this time.  You are welcome to contribute to `dbplyr` via a PR to add this translation, if interested, this article would be a good place to start: http://support.sas.com/documentation/cdl/en/proc/61895/HTML/default/viewer.htm#sql-overview.htm .  And of course, I'll be happy to help you during the process.
