### ISSUE TITLE
collect() makes for inconsistent output when tibble is empty

### ISSUE THREAD

**Issue by ilyaminati** [tidyverse/dplyr#3183]
These two examples produce different outputs depending on whether `collect()` is called, and it requires special error handling. Could they be unified?

```
> pool %>% tbl("mytable") %>% filter(id==5) %>% collect() %>% count()
# A tibble: 0 x 0

> pool %>% tbl("mytable") %>% filter(id==5) %>% count()
# Source:   lazy query [?? x 1] # Database: postgres 9.6.1 [foo]
       n   
<dbl> 
1     0
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by ilyaminati** [comment]
```
con <- DBI::dbConnect(
  drv = RPostgreSQL::PostgreSQL(),
  dbname = creds$db_name,
  host = creds$host,
  user = creds$user,
  password = creds$password,
  port = creds$port
)

copy_to(con, nycflights13::flights, "flights",
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)
flights_db <- tbl(con, "flights")
flights_db %>% filter(year==9999) %>% collect() %>% count()
flights_db %>% filter(year==9999) %>% count()
```

**Comment by ilyaminati** [comment]
@hadley just noting that the reprex is now available

**Comment by hadley** [comment]
I now see

``` r
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RPostgres::Postgres())
DBI::dbWriteTable(con, "mtcars", mtcars, overwrite = TRUE)

db <- tbl(con, "mtcars")
db %>% filter(cyl == 100) %>% collect() %>% count()
#> # A tibble: 1 x 1
#>       n
#>   <int>
#> 1     0
db %>% filter(cyl == 100) %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: postgres [hadley@localhost:5432/hadley]
#>   n              
#>   <S3: integer64>
#> 1 0
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
I suspect you'll need to switch to RPostgres to get the more consistent behaviour.
