### ISSUE TITLE
filter not retaining rows with NA values

### ISSUE THREAD

**Issue by gtumuluri** [tidyverse/dplyr#3196]
Filter is removing rows with NA values on inequality condition. While it is not hard to add to the condition to keep those rows, it does mean you almost always have to write explicit code as absence of NA can't be assured.

```
mydf <- data.frame(x = 1:5, y = c(letters[1:3], rep(NA, 2)))
mydf
  x    y
1 1    a
2 2    b
3 3    c
4 4 <NA>
5 5 <NA>

filter(mydf, y != 'a')
  x y
1 2 b
2 3 c

packageVersion('dplyr')
[1] ‘0.7.2’
```

**Comment by batpigandme** [comment]
Hi,
So, from what I understand, this is by design/due to the way R deals with `NA`s which I can't describe any better than Hadley and Garrett do in the [Missing values](http://r4ds.had.co.nz/transform.html#missing-values) sub-section of **Filter Rows with `filter()`** in r4ds 😬!

Ultimately, as you described as well: 
> `filter()` only includes rows where the condition is `TRUE`; it excludes both `FALSE` and `NA` values. If you want to preserve missing values, ask for them explicitly...

Hopefully this helps clarify a bit!

**Comment by gtumuluri** [comment]
At least an option like `keep.na = TRUE` or something can be added with default value of `FALSE`?

**Comment by hadley** [comment]
You need to be explicit `filter(mydf, is.na(y) | y != "a")`
