### ISSUE TITLE
Summarize & calculate difference between 2 dates given a condition

### ISSUE THREAD

**Issue by Lopa2016** [tidyverse/dplyr#3198]
DummyData <-AllPaidClaims %>%
  group_by(C_ID, M_ID,
        IND) %>%
  summarise(max_ad_date=max(max_ad_date_id),
            max_DIS=max(max_DIS_DATE),LOS=n_distinct(SER_C_DATE[CL_CCT_IND =="Y"]
            LOS=(max_ad_date
                 -max_ad_date)[CL_CCT_IND=="N"])

I want to have C_ID,M_ID & a LOS column created where LOS=difference between max_ad_date & max_DIS_DATE when CL_CCT_IND=="N" & LOS=count(distinct SER_C_DATE ) when CL_CCT_IND=="Y".  

For the difference calculation I get the following error:

Error in summarise_impl(.data, dots) : 
  Column `LOS` must be length 1 (a summary value), not 5

I am new to R would be great if I can get some help on this.

Here's a sample of the data I am using:

C_ID | M_ID | max_ad_date_id | max_DIS_DATE | SER_C_DATE_ID | CL_CCT_IND

1.02E+08 | 3874931 | ######## | ######## | 24MAY2015:00:00:00 | N
1.02E+08 | 3874931 | ######## | ######## | 24MAY2015:00:00:00 | N
1.02E+08 | 3874931 | ######## | ######## | 25MAY2015:00:00:00 | N
1.02E+08 | 3874931 | ######## | ######## | 25MAY2015:00:00:00 | N
1.02E+08 | 3874931 | ######## | ######## | 25MAY2015:00:00:00 | N
1.03E+08 | 3998668 | ######## | ######## | 28JAN2015:00:00:00 | N

**Comment by Lopa2016** [comment]
Hi ,

I have attached a sample data with my code. Hope this might help out?

**Comment by batpigandme** [comment]
Hi Lopa,

If you could do this as a reprex (see links above) then I can actually run your code to see what's happening. Since this doesn't seem to be a dplyr bug, it's not really a package issue, so if you could bring your reprex and question over to the [RStudio community](https://community.rstudio.com/) boards, it'll be easier to help you over there. 

The [Where to ask](https://www.tidyverse.org/help/#where-to-ask) section of the tidyverse help page does a great job of describing the _where_ of getting help (github issues are for problems). Because the tidyverse community is much bigger than just the main developers/maintainers, we try to avoid clogging GH issues as much as possible!

Thanks

**Comment by Lopa2016** [comment]
Thanks :+1:
