### ISSUE TITLE
ggplot2 in R version 3.4.2

### ISSUE THREAD

**Issue by PeterBolo** [tidyverse/dplyr#3224]
I am having problems loading ggplot2 in R version 3.4.2

`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’
In addition: Warning message:
package ‘ggplot2’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘ggplot2’

**Comment by cderv** [comment]
Hi, 

Your issue does not seem to me related to `dplyr`. This issue board is for `dplyr` and `dbplyr` related issues. For non-`dplyr` related question, you can find help on [Stackoverflow with R tag](https://stackoverflow.com/questions/tagged/r) 

However, I can say that your issue seems related to a non-installed `Rcpp`. I suggest to try these options:
*  Reinstall ggplot2 from CRAN in a clean session. It should install all missing dependencies.
* (Re)install `Rcpp` individually. if already install it could be a corrupted install.

If none of this works, I suggest to post your question on [SO with tag ggplot2 and R](https://stackoverflow.com/questions/tagged/ggplot2+r). The R community will help you.
