### ISSUE TITLE
bind_rows should have col_type argument

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3278]
So you could prespecify the types of the columns.  For performance and safety.

**Comment by krlmlr** [comment]
I'm not sure, we can already do:

```r
tibble(
  x = character(), y = integer(), z = list()
) %>%
  bind_rows(a, b)
```

to presprecify column types. Do we need to implement a safer coercion logic?

**Comment by hadley** [comment]
I think so - this is about providing a common interface across `read_csv()`, `convert_types()`, `map_c()` etc.

**Comment by RichardJActon** [comment]
As I just recently mentioned in #1485 I think it would be useful to have an option in `bind_rows` that instead of coercing factors to character vectors lets you specify that you want a new factor with levels from both of the original dataframes/tbls so you know don't have to manually make new factors. However, letting you specify types would likely also solve this, depending on how it handled factors with different levels in the source dfs. 

Although I suppose you would probably want warning if you are altering factor levels as a result of a bind, so maybe an explicit `relevel-factors=TRUE` / `refactor=TRUE` like argument should be required to suppress a warning about releveling factors.

Perhaps a short-form like `inherit-col-types` that lets you specify that you want the same datatypes as the original dfs (assuming all the columns have matching types) would be handy?

**Comment by mkoohafkan** [comment]
Could this a different approach to tibble's [`as_tibble_row`](https://github.com/tidyverse/tibble/issues/205)? If we could specify certain column types as "list" in `bind_rows` it would probably override the need for `as_tibble_row` for most use cases.

**Comment by romainfrancois** [comment]
@hadley is this `vctrs::vec_rbind` ?

**Comment by hadley** [comment]
Yup
