### ISSUE TITLE
dbplyr - Oracle SQL Translation does not accommodate Oracle timestamps.

### ISSUE THREAD

**Issue by aswan89** [tidyverse/dplyr#3284]
When using `dplyr` with a remote Oracle database the SQL translation does not correctly accommodate for Oracle `timestamp` datatypes. Specifically, filtering a tibble pointed at an Oracle table on a date time field (Oracle type `timestamp`, Tibble type `<dttm>`) results in a rejected query.

Date-time strings can be converted to Oracle `timestamp` with the `to_timestamp` function combined with an appropriate formatting string as outlined here: https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions193.htm

I connected to the external database by using the `ROracle` package with the workaround specified here:
https://db.rstudio.com/databases/oracle/#dplyr-translation

```r
sql_translate_env.OraConnection <- dbplyr:::sql_translate_env.Oracle
sql_select.OraConnection <- dbplyr:::sql_select.Oracle
sql_subquery.OraConnection <- dbplyr:::sql_subquery.Oracle 

con <- dbConnect(dbDriver("Oracle"), 
                 dbname = "Database", 
                 user = rstudioapi::askForPassword("User")), 
                 password = rstudioapi::askForPassword("PW"))

table <- tbl(con, in_schema("SCHEMA","TABLE"))

results <- table %>%
  select(
    string,
    dateTime
  ) %>%
  filter(dateTime > Sys.time() - (10*60)) %>%
  show_query()
#> <SQL>
#>SELECT *
#>FROM (SELECT "string" AS "string", "dateTime" AS "dateTime"
#>FROM (SCHEMA.TABLE) ) "limdezpiqk"
#>WHERE ("dateTime" > SYS.TIME() - (10.0 * 60.0))
```
I would expect the SQL to look more like the following:

```r
#> <SQL>
#>SELECT *
#>FROM (SELECT "string" AS "string", "dateTime" AS "dateTime"
#>FROM (SCHEMA.TABLE) ) "limdezpiqk"
#>WHERE ("dateTime" > TO_TIMESTAMP('2018-01-04 12:32:24 CST', 'YYYY-MM-DD HH24:MI:SS TZD'))
```

**Comment by edgararuiz** [comment]
Thanks @aswan89 .  First, a bit of good news.  The new version of `dbplyr`, 1.2.0, includes the workaround you have at the top of your script, so you won't need to do that once you upgrade.  The new version became available today.

Regarding dates, you're right, data/time support is very limited today.  I plan to work on expanding that soon.  In the meanwhile, a tip I have is to use the native Oracle current date call, instead of Sys.time(), `dplyr` will pass that function as-is to Oracle, something like this may help: `filter(TO_TIMESTAMP(field) > SYSTIMESTAMP)`

**Comment by aswan89** [comment]
I just installed the update and the `dbplyr` fixes work as advertised, as does passing the `to_timestamp()` function through `filter()`. Thank you for the quick response and attention on updating dplyr's Oracle capabilities!

**Comment by edgararuiz** [comment]
Great! I'm glad that worked for you!
