### ISSUE TITLE
group_id pronoun

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3341]
From https://github.com/tidyverse/dplyr/issues/1185#issuecomment-289910817.

Not sure if this should be a function (like `row_number()`) or a pronoun (like `.data`).

**Comment by dfrail24** [comment]
Since group_indices is already used to generate a unique id for each group, why can't it just be modified so we can use it inside a mutate function?
At least for others who commented in #1185 and myself, I think it makes more sense to do `mutate(g = group_indices())` and append it to the original data frame than it just returning a vector of integers.

**Comment by romainfrancois** [comment]
#1185 is ✅ with #3490 which is ready to be merged.

**Comment by romainfrancois** [comment]
there's no close command for this particular issue in #3490

**Comment by krlmlr** [comment]
Thanks, added.

**Comment by dfrail24** [comment]
@romainfrancois Hey, thanks for putting your time into this - really appreciate what you've done.
I'll be one of the first to use it once it's merged :)
