### ISSUE TITLE
Issue with querying data on HIVE 

### ISSUE THREAD

**Issue by youcc** [tidyverse/dplyr#3358]
Get the following error when querying data on HIVE 

```r
library(DBI)
library(dplyr)
con <- dbConnect(odbc::odbc(), 
                 Driver="hive", 
                 Host = "xxxx", 
                 Port = "xxx", 
                 UID = "xx", 
                 PWD = rstudioapi::askForPassword("Database password:"))

tbl(con, "mytable")
```
Error message:
>tbl(con, "mytable")
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: 42S02: [RStudio][SQLEngine] (31740) Table or view not found: HIVE..mytable

I assume the error is due to the extra "." between HIVE and my table name. Don't know how to fix it.

Thanks!

**Comment by cderv** [comment]
Hi @youcc , just a thought because when I started using dplyr for database I encountered this issue. 
Is your table _mytable_ in the default schema ? if not (ex. myschema.mytable), you'll have to use `in_schema`.
```r
library(dplyr)
library(dbplyr)
con <- dbConnect(odbc::odbc(), 
                 Driver="hive", 
                 Host = "xxxx", 
                 Port = "xxx", 
                 UID = "xx", 
                 PWD = rstudioapi::askForPassword("Database password:"))

tbl(con, in_schema("yourschema", "mytable"))
```

To know that, the new connection tab in RStudio will help you find where your table is exactly. 

Not sure it is the issue but worth mentioning.

**Comment by youcc** [comment]
@cderv Thank for reminding me to use dbplyr! Initially, I thought it could be the settings of schema, but I couldn't figure out how to set schema using dplyr only.
