### ISSUE TITLE
package ‘lm’ is not available (for R version 3.4.3) getting this issue while installing the lm package.Please help.

### ISSUE THREAD

**Issue by BishtDinesh** [tidyverse/dplyr#3381]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/manipulatr> or http://stackoverflow.com.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
Due to the lack of information, it's not clear what the problem is. However, it sounds like it's unrelated to dplyr. It's likely you're trying to _use_ [`lm()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html) rather than install it (it's not a package that I know of). Either way, this isn't the appropriate forum in which to discuss it further, as it's neither a bug nor a feature request for the dplyr package.
