### ISSUE TITLE
Using recode_factor With Quasi-quotation

### ISSUE THREAD

**Issue by stufield** [tidyverse/dplyr#3388]
I'm trying to implement quasi-quotation with `dplyr::recode_factor()`. I would like to dynamically re-level the factor levels _AND_ map the individual values. In the `reprex` below the original values are `[A, B, C]`s and the levels are `A B C` (default). I would like to map: `A -> Amigo, B -> Be, and C -> Cool` as well as reorder the factor levels to `Be Cool Amigo`. Using `dplyr::recode()` works with quasi-quotation, but it ignores the re-leveling defined by the `level_key` object. I can achieve the re-leveling using `recode_factor()` by hard coding the arguments, however this will not work for the implementation I have in mind. Is this a bug? Am I using the (!!!) incorrectly? Apologies in advance if this has already been addressed and I missed it.
Thank you,
Stu 

```r
  library(magrittr)
  library(dplyr)
  set.seed(100)
  x <- sample(head(LETTERS, 3), 10, replace = TRUE) %>% factor
  x
  level_key <- list("Be", "Cool", "Amigo") %>% set_names(c("B", "C", "A"))    # set factor re-level 
  level_key
  dplyr::recode(x, !!!level_key)              # no re-leveling; desired B C A :(
  dplyr::recode_factor(x, B = "Be", C = "Cool", A = "Amigo")   # correct levels; but no quasi-quotation :(
  dplyr::recode_factor(x, !!!level_key)     # error with recode_factor :(
```

**Comment by batpigandme** [comment]
Hi @stufield,

This sort of question might be a better fit for https://community.rstudio.com until we can figure out if it's really a bug in dplyr. Do you mind asking it over there?

There are more eyes (including some 💪 quasi-quoters) over there, so you'll definitely be able to get an answer more quickly, and, like I said, we can always circle back and reopen the issue here.

Thanks.
