### ISSUE TITLE
dplyr behaves differently if plyr is loaded

### ISSUE THREAD

**Issue by vsbuffalo** [tidyverse/dplyr#347]
Something I noticed today (after a bit of hair pulling) :-)

```
library(dplyr)
> iris %.% group_by(Species) %.% summarize(p=mean(Petal.Length))
Source: local data frame [3 x 2]

       Species     p
 1     setosa 1.462
 2 versicolor 4.260
 3  virginica 5.552
> library(plyr)
iris %.% group_by(Species) %.% summarize(p=mean(Petal.Length))
      p
1 3.758
```

My `sessionInfo()` is below. I'd be happy to take a look at debuggin this and supplying a patch if that would help, but it may be something quite simple. Thanks for `dplyr`, I love it!

```
> sessionInfo() R version 3.0.3 (2014-03-06)
Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] plyr_1.8.1     dplyr_0.1.3    devtools_1.4.1

loaded via a namespace (and not attached):
 [1] assertthat_0.1 digest_0.6.4   evaluate_0.5.1 httr_0.2       memoise_0.1
 [6] parallel_3.0.3 Rcpp_0.11.1    RCurl_1.95-4.1 stringr_0.6.2  tools_3.0.3
[11] whisker_0.3-2
```

**Comment by mattwg** [comment]
I know this is an old thread but I still get caught out even with the warning.  I silence the library function so that when I call it in an RMarkdown document it doesn't spill the warnings onto the screen - when I forget both are loaded I get the summarise from plyr even when loading dplyr second.  It would be very helpful to put all the **ply() functions into dplyr - they are the things I guess most folks are using from plyr - in particular the m*ply() functions - is there is a way to do the equivalent of mdply() this in dplyr?

**Comment by svannoy** [comment]
I've also been getting bit by this, partly for the same reason as mattwg above (trying to keep things quiet in RMarkdown), and also because of the multiple packages that load plyr. 

I've decided now to always qualify summarize and mutate with dplyr::summarize and dplyr::mutate, is there any danger or disadvantage (other than extra typing) to doing this?

**Comment by hadley** [comment]
@svannoy it's only a problem when you do `library(plyr)` not when other packages important plyr functions for their own purposes

**Comment by svannoy** [comment]
Thanks, much easier to get rid of those!


*****************************
@stevenvannoy
stevenvannoy.wordpress.com

**Comment by Alectoria** [comment]
+1 for merging plyr and dplyr or rename their functions. I run multiple scripts in a session that import plyr and/or dplyr and am constantly running into conflicts (warning are easily overlooked when scripts are processed). I have started to explicitely detach both of them at the end of a script but it would be nicer to have one conflict-free solution.
