### ISSUE TITLE
case_when() warning in overlapping conditions

### ISSUE THREAD

**Issue by bobokdalibor** [tidyverse/dplyr#3522]
---

Hi, would it be possible to have a warning when the case_when() runs into overlapping conditions? Example from help:

```r
x <- 1:50
case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ as.character(x)
)
```
This one would give warnings for number 35, because it's dividable by 5,7,and 35 so it fulfills multiple conditions.

**Comment by cedricbatailler** [comment]
I think it would go against the intended behavior. 

The logic is explained in the doc: `case_when` is equivalent to multiple `if else` statement where order matters. Following your logic, anytime a user use a final `TRUE` condition as "else", it would throw a warning because it overlaps everything else.

**Comment by romainfrancois** [comment]
Yes, @bobokdalibor you'd have to implement your own `case_when` for that case.
