### ISSUE TITLE
recode do not preserve variable label

### ISSUE THREAD

**Issue by larmarange** [tidyverse/dplyr#3590]
```
x <- 1:3
attr(x, "label") <- "variable name"
y <- recode(x, `3` = 2L)
```

Label attribute has been lost (`y` do not have any label attribute).

Note: it is not specific to label attribute, but to any label attached to `x`.

**Comment by romainfrancois** [comment]
`recode` does not know specifically how to handle these attributes, not sure just copying them is the right answer. I'd suggest instead of a free attribute you structure your object in an S3 class, and define a recode method for that class, so that the method can take all the right decisions: 

``` r
library(dplyr)
x <- structure(1:3, class = "myclass", label = "variable name")

recode.myclass <- function(.x, ..., .default = NULL, .missing = NULL){
  res <- recode(unclass(.x), ..., .default = .default, .missing = .missing)
  attr(res, "label") <- attr(x, "label")
  res
}
recode(x, `3` = 2L)
#> [1] 1 2 2
#> attr(,"label")
#> [1] "variable name"
```

Created on 2018-05-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by larmarange** [comment]
Added to `labelled` package: https://github.com/larmarange/labelled/blob/master/R/recode.R

**Comment by larmarange** [comment]
Note: the code added to `labelled` package cover `labelled` vectors imported with `haven` and the `labels` attribute.

However, the `label` attribute (with no `s`, corresponding to variable label) is more generic and could be attributed to any vector (character, factor, integer, etc.) and could therefore not be covered through an S3 class. This specific attribute is imported by `haven`, displayed in **RStudio** viewer...

Therefore, it could be coherent with the `tidyverse` for this specific case to be covered by `recode` directly in `dplyr`.
