### ISSUE TITLE
Support data frame and matrix columns

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3630]
``` r
df <- data.frame(x = 1:2)
df$y <- matrix(1:4, ncol = 2)
df$z <- data.frame(A = 1:2, B = 3:4)
df
#>   x y.1 y.2 z.A z.B
#> 1 1   1   3   1   3
#> 2 2   2   4   2   4
str(df)
#> 'data.frame':    2 obs. of  3 variables:
#>  $ x: int  1 2
#>  $ y: int [1:2, 1:2] 1 2 3 4
#>  $ z:'data.frame':   2 obs. of  2 variables:
#>   ..$ A: int  1 2
#>   ..$ B: int  3 4
```

@romainfrancois could you estimate how much work it would be to support data frame and matrix columns in dplyr? To begin with, I'd imagine that we'd forbid grouping by or joining by these columns, although it would be nice to eventually drop that restriction.

**Comment by romainfrancois** [comment]
- `filter()` and `slice()` should be fairly straightforward

- for `mutate()` and `summarise()` we need to consider the cases: 
  - columns that are in the tibble. This will be easier to reason about once hybrid is cleaned up #3526 
  - and expressions that result in matrices or data frames as in #2326 

Does `group_by(...) %>% summarise( x = some_expression() )` make a (data frame, matrix) column when ` some_epression()` returns a data frame of 1 row ? 

Would `group_by(...) %>% mutate( x = some_epression() )` recycle (df,matrices) of 1 row and otherwise accept (df, matrices) of `n()` rows ?

- `arrange()`, joins and `group_by()` need some way to hash rows of matrices and data frames. As part of #977 and #3497 I've had a look at how R hash implementation. We can take inspiration from `vhash` https://github.com/wch/r-source/blob/trunk/src/main/unique.c#L267 

do we need tools to convert df and matrices columns into columns of the outer tibble ?

I think we can target 0.8.0 for this given 0.7.5 has just been accepted.

**Comment by hadley** [comment]
This isn't super urgent, so might be better to think about for 0.9.0

For `filter()` we'll need to think about `filter(df, z$A == 1)` and `filter(df, y[, 1] == 1)` — I'm not sure how hard that will be.

> Does `group_by(...) %>% summarise( x = some_expression() )` make a (data frame, 
> matrix) column when ` some_epression()` returns a data frame of 1 row ? 

That is a very good question. 

> Would `group_by(...) %>% mutate( x = some_epression() )` recycle 
> (df,matrices) of 1 row and otherwise accept (df, matrices) of `n()` 
> rows ?

Yes, I think so - we need to generalise recycling to make `length()` match to make `NROW()` match.

**Comment by romainfrancois** [comment]
This test will benefit from data frame columns in summarise. 

```r
test_that("data.frame columns are supported in summarise (#1425)", {
  skip("will fix as part of #3630")
  df <- data.frame(x1 = rep(1:3, times = 3), x2 = 1:9)
  df$x3 <- df %>% mutate(x3 = x2)
  res <- df %>% group_by(x1) %>% summarise(nr = nrow(x3))
  expect_true(all(res$nr == 3))
})
```

**Comment by romainfrancois** [comment]
From #3651: 

``` r
library(tidyverse)

bad_df = data_frame(x = c(letters)) %>% 
  mutate(a = array(1:26, 26))

summarize(bad_df, b = { res <- sum(a); .Internal(inspect(res)); res })
#> @7fe48d7616d0 13 INTSXP g0c1 [MARK,NAM(3),ATT] (len=1, tl=0) 351
#> ATTRIB:
#>   @7fe489e228d0 02 LISTSXP g0c0 [MARK] 
#>     TAG: @7fe48682e080 01 SYMSXP g1c0 [MARK,LCK,gp=0x4000] "dim" (has value)
#>     @7fe48d73b478 13 INTSXP g0c1 [MARK,NAM(3)] (len=1, tl=0) 26
#> # A tibble: 1 x 1
#>       b
#>   <int>
#> 1   351
```

Created on 2018-06-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jgellar** [comment]
Thanks @romainfrancois for pointing me to this issue. I have a few comments from the "user" side, after reading through the above discussion.

First for context, I have not worked with data.frame columns before, but I have worked with matrix columns pretty extensively in two contexts: functional data analysis, and Bayesian analysis. In FDA, we have observations that are a vector for each subject - these can be images, signals, or really anything measured over time (usually at a high frequency). In Bayesian analysis, predictions for each subject are draws from a posterior, so instead of one prediction we have a vector for each subject. In each case, these "variables" can be arranged in a matrix, with N rows and a fixed number of columns. We also want to associate each row of the matrix with a particular observation, and typically have other variables related to that observation (age, gender, etc.). This makes for a perfect scenario for matrix-columns, because you can keep the "structured" variable all in one columns, but still have identifiers for each row. Keeping it all in one column makes it easier to access the whole matrix at once, and even perform matrix algebra (which is common).

For me, there are really only two features that would be useful that aren't already part of dplyr: `mutate` to add the matrices to the data.frame/tibble, and a modification to `glimpse` so it describes the column as a matrix (currently I have to use `str` in order to do this).

Some of the features mentioned above (like filtering based on particular columns of the matrix) would be neat tricks, but I can't imagine any practical uses for them. It kind of goes against the purpose of using the matrix column to begin with. Maybe filtering on the rowMeans or rowSums or something like that would be useful? Either way, I would think the way to do that would be to first extract the rowMeans and save it as a column of the data.frame, and then use that for filtering. A **very** useful feature that already works is to be able to filter the data.frame by other variables, and have it only return the rows of the matrix that correspond to that filter.

Anyway, I hope this helps in prioritizing the most useful aspects, because I am looking forward to this feature being implemented.

**Comment by jgellar** [comment]
I see that this issue was closed a few months ago, and it looks like some of the functionality I described above was added. In particular, the following now works:

```
N <- 500
J <- 2000
dat <- tibble(age = sample(1:80, N, replace = TRUE),
              male = rbinom(N, 1, .5),
              pred = matrix(rnorm(N*J), nrow = N))
glimpse(dat)
```

Thank you for implementing this! Two additional questions though:

1. In the output of the `glimpse` statement above, it indicates that `pred` is a 35 x 2000 matrix. I'm not sure where this 35 is coming from... it should be 500 (the number of rows of the data frame). Do you have an explanation?
2. I would like to be able to perform simple `mutate` operations on the matrix, but they don't seem to work. For example, the following gives an error:

```
dat2 <- dat %>%
+   mutate(pred = exp(pred)/(1+exp(pred)))
Error: Column `pred` must be length 500 (the number of rows) or one, not 1000000
```
I would like this code to return a matrix column of the same size as the original one (500 x 2000). Could you implement this functionality? Or if there is already a way to do it using different syntax, how would that work?

Thanks in advance.
