### ISSUE TITLE
Documentation of NA types (NA_real_, etc.) in recode function

### ISSUE THREAD

**Issue by ChrisBeeley** [tidyverse/dplyr#3768]
I was reading issue #3202, which relates to the need to use the correct type of NA on the RHS of the case_when function (i.e. NA_real_, NA_character_) etc. The author indicated that they have never heard of different types of NA and I hadn't either. They opened a PR to add an example to the documentation.

I think I'm observing the same type of issue with recode and I wondered if you would like me to open a PR for the documentation for that, too? NA_character_ appears once in the current documentation but it doesn't really say anything specific about matching up the types. Just thought it would be a bit clearer for people like me.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

starwars %>%
  select(name:mass, gender, species) %>%
  mutate(
    gender = recode(gender, "male" = 1, "female" = 2, .default = NA)
  )
#> Error in mutate_impl(.data, dots): Evaluation error: `.default` must be type double, not logical.
```
Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by cderv** [comment]
You are right. Same type of behaviour. `NA_real_` is needed. `NA_integer_` if you use integer replacement instead. 
``` r
library(dplyr, warn.conflicts = FALSE)
recode(starwars$gender[1:10], "male" = 1, "female" = 2, .default = NA_real_)
#>  [1]  1 NA NA  1  2  1  2 NA  1  1
recode(starwars$gender[1:10], "male" = 1L, "female" = 2L, .default = NA_integer_)
#>  [1]  1 NA NA  1  2  1  2 NA  1  1
```

Created on 2018-08-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

These are not often use as is - I see `NA` a lot. It may be important when developing 📦 or scripts to be thorough with correct typed variable. However, when doing an analyse, R is good because you can  go easily withing thinking about type as there are some automatic conversion like with `paste("number" , 1)` and not necessarily paste("number" ,"1"). I wonder if `should` not help with `NA` on this as it seems to me very specific. When you want, it is easier to use `NA` and if it is a numeric vector, the correct type could be used. It would be an exception for this specific `NA` object. Is this something that would be considered or is it too on the opposite on the choice made for type stable input and output in the tidyverse ? Does {vctrs} make some choices on this ?

**Comment by hadley** [comment]
Allowing logical `NA` to work anywhere will be the job of the vctrs package. We could document a little better in the interim, but my hope is to make the problem go away in the long term.
