### ISSUE TITLE
Suggested new convenience function: recast() 

### ISSUE THREAD

**Issue by foundinblank** [tidyverse/dplyr#3785]
[Tweeted about this earlier this week.](https://twitter.com/foundinblank/status/1034027003689795584) Essentially, I do this a lot, and imagine many others do, too. 

```
... %>% mutate(col1 = as.character(col1)) %>% ... 
... %>% mutate(col2 = as.integer(col2)) %>% ... 
```

It's clunky typing the column name twice, and while there's also `mutate_at(vars(column_name), as.character)`, that also feels clunky too. I propose a convenience wrapper function, `recast()` such that: 

```
... %>% recast(col1,col2, as.character) %>% ...
... %>% recast(col3,col4, as.numeric) %>% ...
```
(Thanks to [JLS_Datascience](https://twitter.com/JLS_DataScience/status/1034389279437463552) for the idea.) 

I'd like to try writing a function for this and then do a PR. I can model it off a similar convenience wrapper (which one?). 

Can I?

**Comment by krlmlr** [comment]
Thanks. Have you seen `mutate_at()`?

**Comment by krlmlr** [comment]
I missed the part where you wrote about `mutate_at()` .

My gut feeling is that such a function should live elsewhere, partly because this functionality already can be achieved with existing tools. The `vars()` is a technical necessity for supporting more than one function, but doesn't add too much cognitive burden IMO.

#3433 is about providing a better interface for passing the functions.

**Comment by hadley** [comment]
And generally, I think you should solve type problems further up the pipeline (e.g. during import)
