### ISSUE TITLE
Error in FUN(X[[i]], ...) :    dims [product 279566] do not match the length of object [125]

### ISSUE THREAD

**Issue by rupesh2017** [tidyverse/dplyr#3792]
new_economic_value %>% group_by(EVTYPE)%>%
+ summarise(total_damage=sum(total_damage)) ->p
> p
# A tibble: 125 x 2
   EVTYPE                 total_damage
   <chr>                         <dbl>
 1 ASTRONOMICAL HIGH TIDE          5  
 2 ASTRONOMICAL LOW TIDE         320  
 3 AVALANCHE                 2100286. 
 4 BLIZZARD                195871181  
 5 COASTAL FLOOD           160407181. 
 6 COASTAL FLOODING         25056300  
 7 COLD AIR TORNADO               50.0
 8 COLD/WIND CHILL            601990  
 9 DENSE FOG                    2842  
10 DENSE SMOKE                   100  
# ... with 115 more rows
> View(p)
Error in FUN(X[[i]], ...) : 
  dims [product 279566] do not match the length of object [125]

>as.data.frame(p)
Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  dims [product 279566] do not match the length of object [125]

**Comment by JohnMount** [comment]
I would guess this is related to the structure issues of column contents of your input data.  Please try the numeric conversion steps I outline [here](https://github.com/tidyverse/dplyr/issues/3791#issuecomment-417939358) to see if it clears the problem.  If that fixes it then I would research what is inserting/causing the matrices and fix the root cause problem.

**Comment by romainfrancois** [comment]
Please provide a reprex so that we can reproduce the problem. We do not have `new_economic_value`. 

If you do not know what a reprex is, please have a look at the reprex 📦 as a way to make one. https://reprex.tidyverse.org

**Comment by romainfrancois** [comment]
Please open a new issue with a reprex.
