### ISSUE TITLE
Reference page: Link to filter() is missing, link to distinct() is duplicated

### ISSUE THREAD

**Issue by peterzsohar** [tidyverse/dplyr#3917]
I think this was meant to be a link to `filter.html` https://github.com/tidyverse/dplyr/blob/743204a956dbe839b6eb771cf20bbf8f1cd81bea/docs/reference/index.html#L131

**Comment by batpigandme** [comment]
Thanks! 

Just expanding a bit, since this took me a second to figure out. We have distinct further down, here we describe and should reference filter:

https://github.com/tidyverse/dplyr/blob/743204a956dbe839b6eb771cf20bbf8f1cd81bea/docs/reference/index.html#L130-L134

![dplyr function reference page basic single-table verbs](https://user-images.githubusercontent.com/831732/47082034-5ab9c580-d1da-11e8-9b19-d4778ab48ebe.png)

**Comment by batpigandme** [comment]
Looks like this has been fixed in the [pkgdown.yml](https://github.com/tidyverse/dplyr/blob/743204a956dbe839b6eb771cf20bbf8f1cd81bea/_pkgdown.yml), but we haven't rebuilt the site yet.
https://github.com/tidyverse/dplyr/blob/323b1995b958c60f16cd510d5d8e4223126b71c9/_pkgdown.yml#L19-L22

**Comment by romainfrancois** [comment]
Looks like this has been fixed with the 0.7.8 release.
