### ISSUE TITLE
Feature request: better feedback for filter and recode

### ISSUE THREAD

**Issue by elbersb** [tidyverse/dplyr#3979]
Hi all,
I switched for most of my data analysis to the tidyverse, but there is a nice feature in Stata that I miss. See this screenshot:
![screenshot 2018-11-20 12 40 55](https://user-images.githubusercontent.com/116477/48792242-c4d5f680-ecc1-11e8-8659-19749a3c0c0d.png)
What I really like is to get some feedback on the operations that I'm doing, especially for subsetting (`filter` in tidyverse) and for recodes.

I run a lot of scripts on a remote server, and log the results. Because I want to know how many cases I lose, I have to either do a `print(nrow(data))` before and after each `filter` call, or use a custom function, such as this: 

``` r
keep <- function(d, ...) {
    dropped <- dplyr::filter(d, ...)
    p <- round((1 - nrow(dropped) / nrow(d)) * 100)
    cat(paste0("Removed ", nrow(d) - nrow(dropped), " rows", " (", p, "%)\n"))
    dropped
}
keep(mtcars, mpg > 20)
#> Removed 18 rows (56%)
```

Especially for exploratory and reproducible analyses, this would be a great feature. Maybe it could be controlled via a global variable? If there's interest, I would be happy to look into this.

**Comment by hadley** [comment]
Unfortunately this feels fundamentally un-R-like so I don't think it would be a natural fit in dplyr. It would make a great package though!

**Comment by elbersb** [comment]
You mean a package that wraps dplyr functions?

**Comment by elbersb** [comment]
In case this is of interest to anyone: https://github.com/elbersb/tidylog

**Comment by JakeRuss** [comment]
Hey @hadley, I respectfully ask that you reconsider this feature request. It feels very "pit of success" to me. As a daily user of `dplyr`, this is something I would deploy while writing up an analysis. Wouldn't having a `.verbose` option be a lightweight addition to the API, rather than having to load a separate package with potentially different function names?

And regarding the un-R-like aspect, I'd contend that piping `%>%` was also un-R-like at the time and yet people willingly adopted it while learning what has become the tidyverse approach. As a user, if you're willing to accept the _tidyverse_ ecosystem, this is a comparatively small jump. Even tibbles print their output differently than base R data.frames. 

If it is still a firm no for you, could you explain how you controlled the nicer printing behavior with `tibble`s? If I recall correctly there was a time when printing a data frame gave different output simply based on having the `tibble` package loaded. I think it would be useful to use a similar strategy here, where people used `dplyr` functions, but the messages only display if `tidylog` is loaded.

**Comment by JakeRuss** [comment]
Sorry, I misunderstood the `tidylog` README earlier. I read it as suggesting `filtered()` or `selected()` as the function names, which is wrong now that I look at it again. My apologies, Hadley.
