### ISSUE TITLE
Able to create an variable called "" in tidyr, which leads to weird behaviour in dplyr

### ISSUE THREAD

**Issue by trueNico** [tidyverse/dplyr#3982]
This issue is related to both tidyr and dplyr (I'm using tidyr_0.8.1 and dplyr_0.7.6). I don't know if I need to report it on both.

**The issue:** If I try, using a wrong syntax, to assign a name to the combined variable created by `unite()` from _tidyr_, I am able to create a variable who's name is "", and this leads to weird behaviours in _dplyr_:

```r
library(tidyr)
d <- data.frame(a=1:3, b=5:7)
d <- d %>% 
  unite(k=a:b, remove=FALSE) # writing k=a:b instead of k,a:b creates the column ""
d
#>       a b
#> 1 1_5 1 5
#> 2 2_6 2 6
#> 3 3_7 3 7
```
```r
d %>% 
  select(a:b) # not getting what I want here
#>       a
#> 1 1_5 1
#> 2 2_6 2
#> 3 3_7 3
```

**Comment by batpigandme** [comment]
The desired behaviour here is that tidyr _not_ allow you to create an unnamed column. This seems to be fixed in the development version (see reprex, below). If you update and it continues to allow it, let me know, and I can move this issue over to tidyr. 

Thanks
``` r
library(tidyr)
d <- data.frame(a = 1:3, b = 5:7)
d <- d %>%
  unite(k = a:b, remove = FALSE)
#> Error in is_string(expr): argument "expr" is missing, with no default
```

<sup>Created on 2018-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by trueNico** [comment]
Ok, will do. Thanks!
