### ISSUE TITLE
dev performance with date-times?

### ISSUE THREAD

**Issue by earowang** [tidyverse/dplyr#3988]
The following snippet using dplyr `v0.7.8` runs pretty fast.

``` r
library(dplyr, warn.conflicts = FALSE)
id <- rep(seq.int(8143667, by = 1, length.out = 4e+3), each = 1e+4)
time <- as.POSIXct("2015-01-01 00:00", tz = "UTC") + seq(0, by = 1800, length.out = 1e+4)
index <- rep(time, 4e+3)
tbl <- tibble(id = id, index = index)
system.time(
  tbl %>% 
    group_by(id) %>% 
    summarise(len = length(index))
)
#>    user  system elapsed 
#>   1.084   0.096   1.181
```

However it runs forever using the most recent dplyr dev.

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

~Sidenote: I use [rtichoke](https://github.com/randy3k/rtichoke) as my R console. When I upgrade **dplyr** to dev version, `print()` on any object returns blank display. But `print()` works fine with RStudio and native R console.~

**Comment by romainfrancois** [comment]
What happens here is that hybrid evaluation does not kick in because `time` is not a trivial vector. So `summarise()` has to pay for materializing all the chunks, calling the `length()` function, and pay for its S3 dispatch every single time. 

There's hope in the horizon with altrep and vctrs, which will happen in the 0.9.* series. 

I suppose `length()` could be better handled in hybrid, however I suppose this is not the end game, otherwise you might as well use `n()`. 

The other issue is more likely to be either related to `tibble`, `pillar` or `rtichoke`. 

Sounds however that there is still some issue in `summarise()` performance, e.g. (using 400 instead of 4000) because I'm not patient: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

id <- rep(seq.int(8143667, by = 1, length.out = 400), each = 1e+4)
time <- as.POSIXct("2015-01-01 00:00", tz = "UTC") + seq(0, by = 1800, length.out = 1e+4)
index <- rep(time, 400)
tbl <- tibble(id = id, index = index)

system.time(g <- tbl %>% group_by(id))
#>    user  system elapsed 
#>   0.080   0.011   0.092

system.time(summarise(g, len = length(index)))
#>    user  system elapsed 
#>   6.593   1.140   7.741

indices <- group_rows(g)

system.time(map_int(indices, ~length(index[.])))
#>    user  system elapsed 
#>   0.046   0.013   0.058
```

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
@earowang can you track down if the `print()` problem happens also without `dplyr`, e.g. by creating and printing a `tibble()` ?

**Comment by earowang** [comment]
After restarting the terminal, I cannot reproduce the `print()` problem. Probably my session was contaminated somehow. Sorry about it.

Replacing `length()` with `mean()`/`min()`/`max()` doesn't help speed improvement. My initial analysis code involves my own function handling date-times. It took 3 seconds for a tibble `[46,102,229 x 8]` with 2,924 groups to get the results. But it is surprisingly slow with the dev version. Just think it's worth reporting.

**Comment by romainfrancois** [comment]
Yes definitely. Thank you. Will 🕵️

**Comment by romainfrancois** [comment]
Is this something you would PR by following the logic of #4134 ?

**Comment by earowang** [comment]
Sure, I'll give it a try.
