### ISSUE TITLE
group_trim()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4010]
When we do this: 

```r
g <- iris %>% 
  filter(Species == "setosa") %>%
  group_by(Species)
```

we still end up with 3 groups because we need to respect the levels. Previous versions would only give one group. 

`group_trim()` would be about giving the ability to re-model the factors. 

- `group_trim(<tidyselect spec>)` where the tidyselect spec would only apply to the grouping variables, e.g. 

```r
g %>%
  group_trim(Species)
```

perhaps we'd need variants with `_all` and `_at` (`_if` does not make much sense)

```
g %>%
  group_trim_at("Species")

g %>% 
  group_trim_all()
```

This is essentially a 4 steps 

 - remember the grouping variables
 - ungroup
 - mutate( + droplevels )
 - regroup

Is dropping the only thing we want or would it make sense to have something to `lump` too ?, or should it be more of a mutate type interface, e.g. 

```
%>% 
  group_trim(f1 = fct_drop(f1), f2 = fct_lump(f2)) 
```

**Comment by yutannihilation** [comment]
Is it possible to leave the original levels as is and trim only the grouping structure on calculation? IMHO, what the users want is probably not that fine-grained control over factors by an extra functions, but something that can be done within `group_by()` like this (and `TRUE` by default for backward-compatibility):

``` r
g <- iris %>% 
  filter(Species == "setosa") %>%
  group_by(Species, .trim = TRUE)
```

In this case, `grouped_df` should remember the decision whether to drop empty groups or not so that it can decide automatically when it gets regrouped later (I expect regrouping will frequently happen if the default of `.preserve` is `FALSE`).

**Comment by romainfrancois** [comment]
> Is it possible to leave the original levels as is and trim only the grouping structure on calculation?

This is essentially the previous behaviour. Unless I don't understand what you mean. But the contract with the new dplyr is that if there is a level, it is represented. That's something we feel strongly about. 

I don't think an argument to `group_by()` is visually strong enough.

**Comment by yutannihilation** [comment]
Ah, oh... Sorry, I terribly misunderstood how the new dplyr works. I thought the `groups` attribute is the master table of the groups and all verbs would work based on that information. Really sorry for the noise....

**Comment by romainfrancois** [comment]
This will be much simpler than ⬆️ and more 💪 will be added to `group_by()` in #4029
