### ISSUE TITLE
Ordering does not work if scales::percent was used

### ISSUE THREAD

**Issue by o1iv3r** [tidyverse/dplyr#4014]
I think I found an error when scales::percent has been used to define a new variable.

A reproducible example below  should help explain my point: It seems inpossible to determine whether share_percent is below a certain threshold.

```r
dummy_data <- data_frame(state=c("A","B"),share=c(.1,.9))
dummy_data <- dummy_data %>% mutate(share_percent=scales::percent(share))

# The check works
dummy_data %>% filter(state=="A") %>% select(share) < .09
dummy_data %>% filter(state=="A") %>% select(share) < .1
dummy_data %>% filter(state=="A") %>% select(share) < .11

# Always false
dummy_data %>% filter(state=="A") %>% select(share_percent) < .09
dummy_data %>% filter(state=="A") %>% select(share_percent) < .1
dummy_data %>% filter(state=="A") %>% select(share_percent) < .11

# Check not correct
dummy_data %>% filter(state=="A") %>% select(share_percent) < .09*100
dummy_data %>% filter(state=="A") %>% select(share_percent) < .1*100
dummy_data %>% filter(state=="A") %>% select(share_percent) < .11*100
```

**Comment by batpigandme** [comment]
For future reference, it's a bit easier for the maintainers if you use [reprex](http://reprex.tidyverse.org/) (short for **repr**oducible **ex**ample) since, that way, we can see both the input and the output of the code. 

In this case `scales::percent()` is returning a character class. I can't quite tell if this is the expected behaviour from the scales docs. For the [number formatters](https://scales.r-lib.org/reference/number_format.html) (which includes `percent()`) the [**value**](https://scales.r-lib.org/reference/number_format.html#value) section reads:

> `*_format()` returns a function with single parameter x, a numeric vector, that returns a character vector.

Either way, the behaviour is reproducible without dplyr (see second reprex, below), so I don't think this is the right place for the issue. If this _is_ unexpected behaviour (cc @dpseidel), I can move it over to the scales repo.

``` r
library(dplyr)

dummy_data <- data_frame(state=c("A","B"),share=c(.1,.9))
dummy_data <- dummy_data %>% mutate(share_percent=scales::percent(share))

dummy_data %>% filter(state=="A") %>% select(share) < .11
#>      share
#> [1,]  TRUE
dummy_data %>% filter(state=="A") %>% select(share_percent) < .11
#>      share_percent
#> [1,]         FALSE

class(dummy_data$share_percent)
#> [1] "character"
```

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

``` r
dummy_data <- data.frame(state=c("A","B"),share=c(.1,.9))
dummy_data$percent_2 <- scales::percent(dummy_data$share)
class(dummy_data$percent_2[1])
#> [1] "character"
```

**Comment by romainfrancois** [comment]
The syntax `dummy_data %>% filter(state=="A") %>% select(share) < .09` is very odd. As @batpigandme said `share_percent` is a character vector, so `<` is lexicographic ordering. 

Consider this : 

``` r
scales::percent(.1)
#> [1] "10.0%"
as.character(.09)
#> [1] "0.09"

"10.0%" < "0.09"
#> [1] FALSE
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by dpseidel** [comment]
Just to confirm, yes, this is the expected scales behavior 🐍. The scales formatter functions (including `percent()` and `percent_format()`) are designed to make creating reader-friendly axis labels easier, hence their returning character vectors. Perhaps I should review the docs to make this more explicit 😄
