### ISSUE TITLE
list the elements of a group 

### ISSUE THREAD

**Issue by danyal123** [tidyverse/dplyr#4044]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by romainfrancois** [comment]
@danyal123 can you please do what the text above guides you to do, instead of leaving it as is. The only information we have here is the title of the issue, and that is not enough to understand what you mean.

**Comment by danyal123** [comment]
I see that in the Data set for R2d2 there are two colors, how do I get to that list if I have a df as follows 
name           color
R2D2          white
R2D2            red
I want to end up with as follows 
name       color
R2D2       white,red

I have tried Groupby but the only get me half way is there a version of summarize that can do this for me

**Comment by romainfrancois** [comment]
This looks more like a question on how to use than an issue. [community](https://community.rstudio.com/) is a much better venue for questions. 

Also, you'd have better chances of having feedback with an actual reprex, (If you've never heard of a reprex before, start by reading https://www.tidyverse.org/help/#reprex.). This will help us see what you've effectively tried, instead of second guessing. 

For example, few options here: 

``` r
library(dplyr)
r2d2 <- tibble(
  name = c("R2D2", "R2D2"), 
  color = c("white", "red")
)
r2d2
#> # A tibble: 2 x 2
#>   name  color
#>   <chr> <chr>
#> 1 R2D2  white
#> 2 R2D2  red

r2d2 %>% 
  group_nest(name)
#> # A tibble: 1 x 2
#>   name  data            
#>   <chr> <list>          
#> 1 R2D2  <tibble [2 × 1]>
r2d2 %>% 
  group_by(name) %>% 
  summarise(color = list(color))
#> # A tibble: 1 x 2
#>   name  color    
#>   <chr> <list>   
#> 1 R2D2  <chr [2]>
r2d2 %>% 
  group_by(name) %>% 
  summarise(color = paste(color, collapse = ", "))
#> # A tibble: 1 x 2
#>   name  color     
#>   <chr> <chr>     
#> 1 R2D2  white, red
```

<sup>Created on 2018-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Please open a thread on [community](https://community.rstudio.com/) if you need more information.
