### ISSUE TITLE
Undocumented change: preservation of class attribute

### ISSUE THREAD

**Issue by heavywatal** [tidyverse/dplyr#4051]
The class attribute is lost in the released 0.7.8, and preserved in the dev version:

```r
x = as_tibble(iris)
class(x) = c("myclass", class(x))
x %>% dplyr::filter(Sepal.Length < 5) %>% class()

# 0.7.8
# [1] "tbl_df"     "tbl"        "data.frame"

# 0.7.99.9000
# [1] "myclass"    "tbl_df"     "tbl"        "data.frame"
```

It can be a side effect of the changes in `grouped_df` (or `slice()`), and happens with the stable tibble 1.4.2 and other verbs like `mutate()`. Anyway it is favorable to me and seems to be consistent with the upcoming tibble with subclass support. I just hope it is documented more explicitly so that I can give a clear direction to issues like GuangchuangYu/tidytree#7.

**Comment by yutannihilation** [comment]
Is the preservation of class really an intended change? If so, I'll file the below as a new issue; for regrouping purpose, `group_by(..., add = TRUE)` might be better replaced because `group_by()` doesn't respect the original classes.

``` r
library(dplyr, warn.conflicts = FALSE)

x <- as_tibble(iris)
class(x) <- c("myclass", class(x))
x %>%
  add_count(Species) %>%
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Thanks, it's really a good news to me then :) I'll file a new issue.
