### ISSUE TITLE
Column classes and attributes not preserved after arrange()

### ISSUE THREAD

**Issue by hafen** [tidyverse/dplyr#4079]
The current CRAN version of dplyr (0.7.8) preserves column classes and attributes but this is not done in the dev version and is not documented as a breaking change. I presume this is a bug and not another breaking change.

### dplyr_0.7.99.9000:

``` r
f <- function(x) structure(as.list(x),
  class = c("listified-column", "list"),
  attr1 = 1, attr2 = 2)

df <- dplyr::data_frame(a = rev(letters), b = f(1:26))
class(df$b)
#> [1] "listified-column" "list"
attributes(df$b)
#> $class
#> [1] "listified-column" "list"            
#> 
#> $attr1
#> [1] 1
#> 
#> $attr2
#> [1] 2

df2 <- dplyr::arrange(df, a)
class(df2$b)
#> [1] "list"
attributes(df2$b)
#> NULL
```

### dplyr 0.7.8:

``` r
f <- function(x) structure(as.list(x),
  class = c("listified-column", "list"),
  attr1 = 1, attr2 = 2)

df <- dplyr::data_frame(a = rev(letters), b = f(1:26))
class(df$b)
#> [1] "listified-column" "list"
attributes(df$b)
#> $class
#> [1] "listified-column" "list"            
#> 
#> $attr1
#> [1] 1
#> 
#> $attr2
#> [1] 2

df2 <- dplyr::arrange(df, a)
class(df2$b)
#> [1] "listified-column" "list"
attributes(df2$b)
#> $class
#> [1] "listified-column" "list"            
#> 
#> $attr1
#> [1] 1
#> 
#> $attr2
#> [1] 2
```

**Comment by yutannihilation** [comment]
I think this is basically not a dplyr's fault; the custom class should have the `[` method to preserve its attributes. Otherwise, you'll see the attributes are lost even with sorting in the base-R way. That said, considering this can break the existing code, it would be better to include this in the breaking changes section of NEWS.

c.f. https://github.com/tidyverse/dplyr/issues/3923

``` r
library(dplyr, warn.conflicts = FALSE)

f <- function(x) {
  structure(as.list(x),
            class = c("listified-column", "list"),
            attr1 = 1, attr2 = 2)
}

df <- tibble::tibble(a = rev(letters), b = f(1:26))

attributes(df$b[rev(1:26)])
#> NULL

# define [ method
`[.listified-column` <- function(x, i, j, ..., drop = TRUE) {
  cls <- class(x)
  atrb <- attributes(x)
  x <- NextMethod()
  structure(x, class = cls)
  attributes(x) <- atrb
  x
}

attributes(df$b[rev(1:26)])
#> $class
#> [1] "listified-column" "list"            
#> 
#> $attr1
#> [1] 1
#> 
#> $attr2
#> [1] 2

dplyr::arrange(df, a) %>%
  { attributes(.$b) }
#> $class
#> [1] "listified-column" "list"            
#> 
#> $attr1
#> [1] 1
#> 
#> $attr2
#> [1] 2
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment]
Thanks. @yutannihilation is right. I need to mention this in the Breaking changes section. 

The previous versions were just dumbly copying attributes, but that might not be at all what the custom class wants. Now whenever we need to take a subset of a vector that is not trivial (including reordering), we fall back to R's `[` so that the implementer of `[.<class>` can control what happens.
