### ISSUE TITLE
Should `tbl_vars()` add grouping metadata with grouped tibble?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#4106]
Currently `select()` uses the unexported `sel_vars()` to create variables passed to tidyselect. These variables contain the metadata necessary for `group_cols()` to figure out the grouping variables.

While this works for `select()`, `group_cols()` can't be used in other selecting functions like `tidyr::gather()`. Support for grouped tibbles in `tbl_vars()` would solve this.

**Comment by romainfrancois** [comment]
Do we still need this ?

It's kind of a mess: 

- `tbl_vars()` is generic with at least implementations in `dplyr` and `dbplyr`
- `group_vars()` too
- `tbl_nongroup_vars()` calls `tbl_vars()` and `group_vars()`
- `sel_vars()` calls `tbl_vars()` and `group_vars()`

Perhaps we can export `sel_vars()` instead of changing `tbl_vars()` ?

**Comment by lionel-** [comment]
Yes we still need this. Not sure what's the best API for it.
