### ISSUE TITLE
sels() and acts()

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#4169]
Once we have https://github.com/r-lib/rlang/issues/726, `sels()` would take selections, `acts()` would take actions, and they'd return a data frame.

Is `acts()` is really needed? Most of the time this could be just `tibble()` with data-masking within other dplyr verbs, i.e. `mtcars %>% morph(df_col = tibble(cyl, am))`.

**Comment by hadley** [comment]
Also needs https://github.com/tidyverse/dplyr/issues/2326

Maybe `sels()` should be `cols()`? We'd also have `cols_if()`?

We also need some helper to make it easy to apply one function to multiple columns. That could maybe look like `cols(starts_with("x"), mean)` or `col_(mean)(starts_with("x"))`. The idea of using `col_()` here is to match colwise functions from funs that might look like `col_min()`, `col_max()` etc. But then `col_()` and `cols()` are probably too similar, so that `sels()` would be better.

**Comment by yutannihilation** [comment]
> Is `acts()` is really needed?

IMO, rather than `sels()`, `acts()` (mutate semantics) and its scoped variants (`_if`, `_at`) are needed, considering:

* we might also want to use predicates
* we might want to apply functions to modify data (and rename colnames?)

For example:

* `acts(...)`: just a short cut for `tibble()`
* `acts_at(.vars, .act, .rename)`: `.act` for modifying data, and `.rename` for renaming
* `acts_if(.predicate, .act, .rename)`: ditto

**Comment by lionel-** [comment]
Summary of relevant discussion in https://github.com/tidyverse/tidyselect/issues/86

* We can unify `_if` and `_all` into `_at` selection semantics
* `pick()` would be a good name for selections.
* Perhaps `map_dfc()` should be used for transformations instead of bundling those in `pick()`.
* Another approach is a function operator as outlined in Hadley's message above.
* Aliases for common operations such as taking the mean of columns would be useful.

These would be equivalent:

```r
data %>% summarise(df_col = cols_mean(starts_with("d"), na.rm = TRUE))

data %>% summarise(df_col = colwise(mean)(starts_with("d"), na.rm = TRUE))

data %>% summarise(df_col = map_dfc(pick(starts_with("d")), mean, na.rm = TRUE))
```

**Comment by hadley** [comment]
@lionel- pointed out that `cols_mean()` (as defined here) would only work inside functions with tidyselect semantics, which I think means that we should remove that option from consideration.

**Comment by lionel-** [comment]
`cols_mean()` will work everywhere because we will register data in addition to variables.

**Comment by lionel-** [comment]
oh or did you mean that it would only work within data mask contexts? I remember mentioning yesterday that this would make them different from e.g. normal R functions like `mean()`. They would minimally need a `with_data()`:

```r
with_data(data, cols_mean())
```

**Comment by hadley** [comment]
If we're going to "claim" the `col_` prefix to mean columnar, I think `col_mean(data)` would have to work.  So I think that implies it would be:

```R
data %>% summarise(df_col = cols_mean(pick(starts_with("d")), na.rm = TRUE))
```

**Comment by lionel-** [comment]
That makes sense. So that'd be a simple wrapper around `map_dfc()`?

```r
function(.data, ...) map_dfc(.data, base::mean, ...)
```

Slight note, I find a `cols_` prefix would be a little more suggestive of a tibble return.

**Comment by lionel-** [comment]
The advantage of `col_mean()` over `map_dfc(pick())` is that it can be hybridised.

**Comment by lionel-** [comment]
Need to think about df-cols with lazy backends. Might need special support in `mapping()`.

**Comment by hadley** [comment]
Resolved by `across()`
