### ISSUE TITLE
`case_when()` removes names from returned lists

### ISSUE THREAD

**Issue by rvg02010** [tidyverse/dplyr#4194]
Updating some code and wanted to use `case_when()`, except it seems to be unable to return named lists?

Example:
```
broken_function <- function(value) {
  dplyr::case_when(
    value == TRUE ~ dplyr::lst(a = 1, b = 2),
    value == FALSE ~ dplyr::lst(a = 2, b = 3),
    TRUE ~ dplyr::lst(a = 3, b = 4)
  )
}

broken_function(TRUE)
#> $<NA>
#> [1] 1
#> 
#> $<NA>
#> [1] 2
```

**Comment by hadley** [comment]
I think that reveals a completely different bug because the input and output length should be the same, and I would think it would make more sense to preserve the names of the input not the names of the output. 

It doesn't look like you actually need a vectorised function, so you might instead try something like this:

```R
broken_function <- function(value) {
  if (value) {
    list(a = 1, b = 2)
  } else {
    lst(a = 2, b = 3)
  }
}
```

**Comment by acnb** [comment]
I had a problem with not returned names in lists as well  (https://stackoverflow.com/questions/57463924/losing-names-when-using-lists-as-results-of-dplyrcase-when). I wanted n lists (with names) as output for n inputs. This is unexpected because lists are usually OK in the tidyverse. If this is not the case this should be documented?

**Comment by edonnachie** [comment]
I also encountered this problem. I agree with acnb that either the documentation should be updated or a bugfix implemented.
