### ISSUE TITLE
Should summarise_all() name the syms ?

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4203]
```r
library(dplyr, warn.conflicts = FALSE)

tbl <- tibble(g = 1:3, x = 1:3)
tbl %>% 
  group_by(g) %>% 
  summarise_all(list(mean = mean))
#> # A tibble: 3 x 2
#>       g  mean
#>   <int> <dbl>
#> 1     1     1
#> 2     2     2
#> 3     3     3
tbl %>% 
  group_by(g) %>% 
  summarise_at(c(x = "x"), list(mean = mean))
#> # A tibble: 3 x 2
#>       g x_mean
#>   <int>  <dbl>
#> 1     1      1
#> 2     2      2
#> 3     3      3
```

So that the `_all()` also make a `x_mean` similar to what would happen with more than 1 variable: 

``` r
library(dplyr, warn.conflicts = FALSE)

tbl <- tibble(g = 1:3, x = 1:3, y = 1:3)
tbl %>% 
  group_by(g) %>% 
  summarise_all(list(mean = mean))
#> # A tibble: 3 x 3
#>       g x_mean y_mean
#>   <int>  <dbl>  <dbl>
#> 1     1      1      1
#> 2     2      2      2
#> 3     3      3      3
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
@lionel- any opinion on this ?

**Comment by lionel-** [comment]
In the scoped replacements we should probably return a df-col when passed a list of functions. Here that would be `tibble(mean = tibble(x = ..., y = ...))`. This way we don't have to combine names and we have a structure that's indexable and easily reshaped. And the tibble-col strategy works with both mutate and summarise.

So I think we should probably not worry too much about the current scoped variants, since they will be retired?

**Comment by romainfrancois** [comment]
Fine by me, I'll just close this then.
