### ISSUE TITLE
Lubridate and setdiff are incompatible

### ISSUE THREAD

**Issue by MichaelAdolph** [tidyverse/dplyr#4231]
I tried to split a dataset with sample_frac/sample_n and setdiff like this:

     test = data.frame(useless_data = c(1,2,3,4,5,6,7,8,9))
     set.seed(42)
     training = test %>% sample_n(7)
     validation = test %>% setdiff(training)

It works perfectly (i.e. Validation is a 2-entry data Frame) as Long as lubridate is not loaded. As soon as the lubridate package is loaded, setdiff does not work anymore, Validation is now the full test data.frame.

**Comment by batpigandme** [comment]
For future reference, it's always helpful to include a full reprex which will show input and output. You can overcome this by prefixing `setdiff()` with the desired namespace (in this case, `dplyr::setdiff()`).

I don't think this is expected behaviour, though, so we should probably be throwing a warning somewhere.

``` r
suppressPackageStartupMessages(library(tidyverse))
test <- data.frame(useless_data = c(1, 2, 3, 4, 5, 6, 7, 8, 9))
set.seed(42)
training <- test %>% sample_n(7)
validation1 <- test %>% setdiff(training)
dim(validation1)
#> [1] 2 1

library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
validation2 <- test %>% setdiff(training)
dim(validation2)
#> [1] 9 1

validation3 <- test %>% dplyr::setdiff(training)
dim(validation3)
#> [1] 2 1
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by MichaelAdolph** [comment]
Hi, sorry for the missing reprex.
Throwing an warning would be helpful, but of Course, specifing the Namespace could have come to my mind... .
Should I close this or better leave this open until a warning message is implemented?

**Comment by batpigandme** [comment]
Let's leave it open - @hadley, @lionel, should I move it to generics?

**Comment by hadley** [comment]
Already reported in https://github.com/tidyverse/lubridate/issues/693
