### ISSUE TITLE
Function to replace values for specific rows

### ISSUE THREAD

**Issue by skranz** [tidyverse/dplyr#425]
I wonder if there is a possibility to add a general function to change values only for specific rows that satisfy a filter condition? Here is a simple example of such a function, I have in mind:

```
replace.if = function(.data,...,.if=NULL) {

  .if = substitute(.if)
  if (!is.null(.if)) {
    rows = eval(.if,.data)
    d = .data[rows,]
    d = mutate(d,...)
    .data[rows,] = d
  } else {
    .data = mutate(.data,...)
  }
  .data
}
# Examples
library(dplyr)
dat = cars[1:10,]
replace.if(dat, dist=dist*100, .if= speed==4)
replace.if(dat, dist=dist*100)
```

I think a quick implementation of such partial replacements would be really useful in many situations and this functionality is a very convenient feature of data.table. On the other hand, I don't know how hard it is to generally implement such a function in dplyr given that there are so many possible data sources. I also don't know a good verb as function name, perhaps 'modify'?

**Comment by kstohr** [comment]
As a newbie, I agree.. this would be a great function and much simpler than current code options.

**Comment by bramtayl** [comment]
Maybe I'm being dense, but when I use mutate_if, I need to run as.data.table first.

**Comment by skranz** [comment]
Hi @bramtayl,

I am not sure whether your question would not be better filled as an issue in dplyrExtras. Anyway, do you have a simple example that fails? The simple example in the documentation of dplyrExtras works on my computer for data frames:
```
  library(dplyrExtras)
  # Test mutate_if
  set.seed(123456)
  n = 10
  df = data.frame(
    a= sample(1:3,n,replace=TRUE),
    b= sample(1:100,n,replace=TRUE),
    x=rnorm(n)
  )
  mutate_if(df,a==3,x=100)
```

BTW:
The following issue may be related https://github.com/hadley/dplyr/issues/942. @astamm discusses the possibility that `mutate_if` from dplyrExtra could be probelmatic when chaining operations and he provides a alternative implementation of `mutate_if` that could be less problematic (that version may yield different output than mutate_if in dplyrExtras since it may change the row order, however).

**Comment by bramtayl** [comment]
library(pipeR)
library(dplyr)
I don't think it's a problem with chaining, it happens with and without chaining.

a = c(1, 2, 3)
b = c("my momma", "takes care", "of me")
c = c("you", "and", "me")

#works
abc = data.frame(a, b, c) %>>%
  mutate_if(a == 1, b = "my pappa")

abc = data.table(a, b, c) %>>%
  mutate_if(a == 1, b = "my pappa")

#does not work
abc = data_frame(a, b, c) %>>%
  mutate_if(a == 1, b = "my pappa")

#does not work, even without chaining
abc = data_frame(a, b, c)
abc = mutate_if(abc, a == 1, b = "my pappa")

#does not work
abc = data_frame(a, b, c) %>>%
  as.data.table %>>%
  mutate_if(a == 1, b = "my pappa")

#works
abc = data_frame(a, b, c) %>>%
  as.data.frame %>>%
  mutate_if(a == 1, b = "my pappa")


#Error in `:=`(b, "my pappa") : 
#  Check that is.data.table(DT) == TRUE. 
#  Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. 
#  See help(":=").

**Comment by skranz** [comment]
I also get the error. Looks like there are some problems of data.table self-awareness in case a dplyr tbl_df is converted to a data.table with as.data.table().

While I have no clue how to solve the deeper problem,  I included a simple work-around in mutate_if: now a tbl_df is fist converted to a data.frame and then to a data.table. The new version works for me in the example. I uploaded the new version of dplyrExtras to github.

**Comment by tyokota** [comment]
It would be great if nested ifelse functions didn't look hard to read when using hard returns+indent. In my work with complex surveys, I usually need to use more than one conditional statement per variable. The workaround I am using is to remove the indent and adding/subtracting spaces to align my ifelse statements so that my code doesn't extend to the right to the point that I would need to scroll right manually to see all the nested conditional statements. In SAS, the conditional statements are easy to read as they are lined up. If not a mutate_if, a dplyr solution would be great for the purposes of sharing and reproducabity.

**Comment by mygitforcoursera** [comment]
I am getting a similar error but it is just using the base dplyr package, not the dplyrExtras. Here's the few preceding lines of code to the error : 
> mss_df = data.table(mean_std_slect)
> mean_set = data.table()
> for(i in 1:30){
+     for(h in 1:6){
+         tmp <- dplyr::summarise_each(mss_df[which((mss_df$activity == h) & (mss_df$subject == i))],funs(mean))
+         mean_set <- dplyr::bind_rows(mean_set,tmp)
+     }
+ }
> is.data.table(mean_set)
[1] FALSE
> is.data.table(mss_df)
[1] TRUE
I'm taking a course in R and this is the very last step I had to do before turning in the project, yay irony, and while I don't expect a resolution in time, i'll work around it, but I found this thread while searching the error and thought it might be relevant.

**Comment by bramtayl** [comment]
I'm not sure you need for loops;

```{r}
activity_lookup = data_frame(activity = 1:length(act_list),
                                               activity_name= act_list)

mean_set = 
  mean_std_slect %>%
  group_by(subject, activity) %>%
  summarise_each(funs(mean)) %>%
  left_join(activity_lookup)
```

Unless I'm misunderstanding your code.

**Comment by coolbutuseless** [comment]
Adding my support for 'mutate_if' type of function.  My use case:
Large data.frame where different variables need to get set based upon a status.  There are quite a number of status, so nested `ifelse()` becomes pretty awful.  Currently it's something like:

```r
mydata %<>% mutate(
  type = ifelse(status > 12, "big", type),
  rf   = ifelse(status > 12, 12.3, rf),
  zz   = ifelse(status > 12, 1, zz),
. 
.
.
  type = ifelse(status == 17, "anom", type),
  rf   = ifelse(status == 17, 16.1, rf),
  zz   = ifelse(status == 17, 2, zz),
.
.
)
```

with a `mutate_if()` this would become:
```r
mydata %<>% mutate_if(status > 12,
   type = 'big',
   rf   = 12.3,
   zz   = 1
) %>% mutate_if(status == 17,
   type = 'anom',
   rf   = 16.1,
   zz   = 2
)
```

**Comment by kevinushey** [comment]
Here's a simple definition of `mutate_when` that would accomplish your proposal with a somewhat nice syntax:

```R
data <- data.frame(status = 1:20, a = 0, b = 0)

mutate_when <- function(data, ...) {
  dots <- eval(substitute(alist(...)))
  for (i in seq(1, length(dots), by = 2)) {
    condition <- eval(dots[[i]], envir = data)
    mutations <- eval(dots[[i + 1]], envir = data)
    data[condition, names(mutations)] <- mutations
  }
  data
}

library(magrittr)
data <- data.frame(status = 1:20, a = 0, b = 0)

mutate_when <- function(data, ...) {
  dots <- eval(substitute(alist(...)))
  for (i in seq(1, length(dots), by = 2)) {
    condition <- eval(dots[[i]], envir = data)
    mutations <- eval(dots[[i + 1]], envir = data)
    data[condition, names(mutations)] <- mutations
  }
  data
}

data %>% mutate_when(
  status > 10, list(a = 1, b = 2),
  status > 15, list(a = 3, b = 4)
)
```

Although it's not going to be as performant as something done on the C++ side could be.

**Comment by kendonB** [comment]
+1 for in place mutation using mutate_if. There are genuine use cases for this when there are data errors. Data errors are everywhere.

**Comment by elikesprogramming** [comment]
@hadley could you please elaborate on why "dplyr will never support in-place mutation of data"? why do you feel so strongly against it?

In my use case, `ifelse` does not work, because I need to use a function that triggers an error if the argument is `NA`. Using `ifelse`, the whole vector (including NAs) is passed to that function and not only the rows I need (when the condition is TRUE or FALSE). [See question in SO](http://stackoverflow.com/questions/36392134/create-new-variable-defined-only-for-a-subset-of-the-data-using-dplyr)

**Comment by hadley** [comment]
@elikesprogramming I've done it elsewhere many times so I'm not going to do it again, sorry. Sounds like you need a vectorised function.

**Comment by skranz** [comment]
Just for info: 
I just renamed the `mutate_if` function in dplyrExtras to `mutate_rows`. For backward compatibility the orginal name `mutate_if` can still be used, however.

The reason is that dplyr 5.0 introduced a new function `mutate_if` with quite different purpose and behavior than the `mutate_if` function in dplyrExtras.

I guess if you load dplyrExtras, by default the `mutate_if` function from dplyrExtras should be used, instead of the new `mutate_if` function from dplyr. So hopefully, old code that relies on dplyrExtras `mutate_if` does not break. Nevertheless, it seemed prudent to change the function name in dplyrExtras to reduce confusion and future errors.

**Comment by klmr** [comment]
Here’s a use-case for `mutate_if` that hasn’t been mentioned in this thread before as far as I can see, and for which an `ifelse` solution is even less efficient (to an appreciable extent) and more convoluted.

```r
> rna_tail_modifications
             Gene Modification Length
            <chr>        <chr>  <int>
1  WBGene00004044            C      1
2  WBGene00002027            N      1
3  WBGene00021902                   0
4  WBGene00017016            N      3
5  WBGene00018638            T      2
…
> rna_tail_modifications %>% mutate_if(Modification == 'N', Modification = '', Length = 0)
             Gene Modification Length
            <chr>        <chr>  <int>
1  WBGene00004044            C      1
2  WBGene00002027                   0
3  WBGene00021902                   0
4  WBGene00017016                   0
5  WBGene00018638            T      2
…
```

In other words: replace values in more than one column based on the condition. For comparison, here’s how I have to do this at the moment:

```r
rna_tail_modifications %>%
    mutate(Modification = ifelse(Modification == 'N', '', Modification),
           Length = ifelse(Modification == 'N', 0, Length))
```

This is an example I run into on a fairly regular basis. The above data is an excerpt from an actual current project.

**Comment by jjm319** [comment]
I have exactly this use case, based on a data flag i have to remove certain rows of data. Why is this not the way to do this and how should it be done? I never got a clear explanation of the "proper" way.

**Comment by kendonB** [comment]
Remove rows with ``filter``. For higher quality and speed responses to ``how do I do things`` questions, use stackoverflow. The proposed ``mutate_when`` would provide a more efficient replacement for ``mutate`` with ``if_else`` in the case when there is more than one variable to replace values for.

**Comment by jjm319** [comment]
Oh thanks, i was not quite clear, i had to keep the rows because row location was important, but used a complicated (for me) replace which statment to replace some of my data with -9999 when the wind was from the wrong direction. Had to use about 20 of these for each observation.

mutate(EddyP.f,LE = replace(LE, which(dt >= start & dt<=end & wind_dir >260), -9999))->EddyP.f
mutate(EddyP.f,LE = replace(LE, which(dt >= start & dt<=end & wind_dir <90), -9999))->EddyP.f

I think a simple statement like advocated in this thread is the way to go and was just wondering why Hadley is so hostile to it and how he thinks it should be done. But either way i think the mutate_rows function is great. So just wanted to add my support.

**Comment by hadley** [comment]
Because that's already trivial to solve with `case_when()` (or at least will be once `case_when` works inside `mutate()`):

```R
EddyP.f %>% mutate(,
  LE = case_when(
    dt <= start | dt >= end ~ LE,
    wind_dir > 260 ~ NA,
    wind_dir < 90  ~ NA
  )
)
```

Replacing with -9999 seems like a bad idea.

**Comment by jjm319** [comment]
I like that solution, thanks Hadley. I did not know how to do that, still learning. As for the missing data indicator, i agree that NA is better but the software i use to process the data requires missing observations to be -9999

**Comment by ahcyip** [comment]
@skranz have you seen dplyr::recode ?

**Comment by jdevgrell** [comment]
Hi, I'm a SAS programmer learning how to use R, and I came across this thread because I'm looking for functionality that mimics the SAS data step IF...END logic (basically, the same issue that's discussed in this thread). I want to use a single conditional statement within dplyr mutate to create multiple new columns (or recode existing ones), without needing to always re-specify the conditional logic for each variable. I've found that the data.table package allows this pretty easily, as in the example below. But I'm not seeing how the dplyr case_when() or recode() functions allow something like this, because they both seem to only work on one variable/vector at time. Unless I'm mistaken, to do something like I have below, I'd still need to use the mutate_rows function, right?

NewData2[!is.na(LIB_1_1_Answer) & !is.na(LIB_1_2_Answer),
         `:=`(
         LIB_Conserv_Neg1 = LIB_1_1_Answer,
         LIB_Conserv_Neg2 = LIB_1_2_Answer,
         LIB_Conserv_Pos1 = LIB_1_3_Answer,
         LIB_Conserv_Pos2 = LIB_1_4_Answer,
         LIB_Liberal_Neg1 = LIB_1_5_Answer,
         LIB_Liberal_Neg2 = LIB_1_6_Answer,
         LIB_Liberal_Pos1 = LIB_1_7_Answer,
         LIB_Liberal_Pos2 = LIB_1_8_Answer)
         ]

**Comment by tonyntang** [comment]
I think something like mutate_when() in the following example 
```
mutate_when(condition_is_true,
            x = var1,
            y = var2)
```
might be better than

```
mutate(x = case_when(condition_is_true ~ var1,
                     TRUE ~ x),
       y = case_when(condition_is_true ~ var2,
                     TRUE ~ y))
```

**Comment by DavisVaughan** [comment]
Since this seems to be something people are still interested in, here is my attempt at tackling the problem. This solution draws from @kevinushey's solution, [this SO question](https://stackoverflow.com/questions/34096162/dplyr-mutate-replace-on-a-subset-of-rows/), and the implementation of `case_when()`. There are two functions involved, with full implementations at [this gist](https://gist.github.com/DavisVaughan/24cbc404c09e75d3bf23467d15a7d42d). _Neither modify in place._

`mutate_rows()` uses a ` .predicate` to determine which rows to modify, and allows you to specify multiple columns to update when that predicate is true.

```r
data <- data_frame(status = 1:20, a = 0, b = 0)

# mutate_rows(.data, .predicate, ...)
# where status == 4, set a = 5 and b = 6
mutate_rows(data, status == 4, a = 5, b = 6)
```

`mutate_when()` takes two sided formulas, and is a mix of @kevinushey's answer and `case_when()`. It repeatedly calls `mutate_rows()`, which could probably be improved.

```r
# mutate_when(.data, ...)
# where status == 4, set a = 5 and b = 6
# where status == 2, set a = 6 and b = 8
data %>% mutate_when( 
    status == 4 ~ vars(a = 5, b = 6),
    status == 2 ~ vars(a = 6, b = 8)
)
```
