### ISSUE TITLE
SymbolString, encoding loss, ...

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dplyr#4291]
Follow up on #4266

**Comment by krlmlr** [comment]
Unlike symbols, strings know about their encoding -- but it has to be defined correctly when the string is constructed. Symbols are supposed to come in the native encoding.

The purpose of the `StringSymbol` class was to encapsulate names so that the correct recoding is retained even if occasionally these names need to be converted to symbols.

Do you want me to look at the problem a bit closer?

**Comment by romainfrancois** [comment]
I guess, but this imo has too many uses of `Rcpp::String` which individually preserve/release CHARSXP. 

If you can replicate the problems from #4263, you'd be in a better position to handle it I suppose. 

I did not manage to make it fail using Winston's hints from #4266 and I don't have immediate access to a windows machine.

**Comment by romainfrancois** [comment]
SymbolString is no more in the codebase.
