### ISSUE TITLE
Provide logical alternatives for rowwise operations.

### ISSUE THREAD

**Issue by abalter** [tidyverse/dplyr#4294]
Apparently, [`rowwise` is a bad idea and will no longer be maintained](https://github.com/tidyverse/dplyr/issues/3144).

What is now the recommended way to create new columns with max, min, sum, mean, etc. of all or select rows?

**Comment by romainfrancois** [comment]
`rowwise()` is still maintained, just labelled as questioning because we no longer believe in its potential. 
@jennybc webinar addresses a selection of techniques, and usually the tool to use comes from `purrr`. 
https://www.rstudio.com/resources/webinars/thinking-inside-the-box-you-can-do-that-inside-a-data-frame/

Having said that, you can still use `rowwise()`, it's still tested and so on.

**Comment by moodymudskipper** [comment]
see also `pmax`, `pmin`, `rowSums`
