### ISSUE TITLE
mutate() ignores list columns silently

### ISSUE THREAD

**Issue by grayskripko** [tidyverse/dplyr#4340]
``` r
library(tidyverse)
tibble(a=list(tibble(b=2))) %>% mutate(c=dim(a))
#> # A tibble: 1 x 1
#>   a               
#>   <list>          
#> 1 <tibble [1 x 1]>
```

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Why is that? Why doesn't it throw an error or a warning?

**Comment by cderv** [comment]
Let’s go step by step on what is going on here. 

we create the data

``` r
library(tidyverse)
tab <- tibble(a=list(tibble(b=2)))
tab
#> # A tibble: 1 x 1
#>   a               
#>   <list>          
#> 1 <tibble [1 x 1]>
```

We get a tibble with one list column here.

In you example, you are trying to apply `dim()` on column `a`
but `dim()` on a list gives NULL

``` r
dim(tab$a)
#> NULL
```

so it is as if you are asking for this

``` r
tab %>%
  mutate(c = NULL)
#> # A tibble: 1 x 1
#>   a               
#>   <list>          
#> 1 <tibble [1 x 1]>
```

and mutating with a NULL value delete the column if it exists or do nothing otherwise.

I believe, you want to apply `dim()` on each tibble in your list column `a`
Indeed, dim on a tibble gives a value

``` r
dim(tab$a[[1]])
#> [1] 1 1
```

If you want to apply `dim()` on each tibble inside the list column, you need
to iterate on elements. This is how to work with list column in tibble.

``` r
tab %>%
  mutate(c = map(a, dim))
#> # A tibble: 1 x 2
#>   a                c        
#>   <list>           <list>   
#> 1 <tibble [1 x 1]> <int [2]>
```

Then you’ll get a result with a new c column also, a list colum here. 

There is no warning or error because there is no reason too. `mutate()` does not ignore list column at all.

You could be interested in the webinar [How to Work with List Columns](https://www.rstudio.com/resources/videos/how-to-work-with-list-columns/)
<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Hope it helps

**Comment by grayskripko** [comment]
I missed that. `dim(any_list) -> NULL` then `mutate(c = NULL` will destroy the column.
These list columns are great but pretty tricky.
Thanks for the help, @cderv
