### ISSUE TITLE
Error when using tbl column index 

### ISSUE THREAD

**Issue by RamiKrispin** [tidyverse/dplyr#4465]
Hi,

I am getting to following error when trying to calculate the mean of tbl specific column while using the column index value:

`> x <- as.tbl(mtcars)`
`> mean(x[,2])`
`[1] NA`
`Warning message:`
`In mean.default(x[, 2]) : argument is not numeric or logical: returning NA`

On the other hand, it works when using the column name:
`> mean(x$cyl)`
`[1] 6.1875`

Any suggestions on how to solve this issue? 

Thanks,
Rami

**Comment by cderv** [comment]
Hi, 

the behavior by default of a `tibble` is a bit different from a data.frame. One of the difference is that it is type stable when you select a column, even by indexed. See this [help page](https://tibble.tidyverse.org/reference/subsetting.html) about `[` for tibble.

> `[` always returns a tibble by default, even if only one column is accessed.

This what happening in your example. Here is some examples.

``` r
library(dplyr, warn.conflicts = FALSE)
x <- as.tbl(mtcars)
```

indexing a tbl gives you a data.frame
because tibble don’t drop by default, like data.frame

``` r
class(x[, 2])
#> [1] "tbl_df"     "tbl"        "data.frame"
class(x[, 2, drop = TRUE])
#> [1] "numeric"
```

you can’t applky mean on a tibble

``` r
mean(x[,2])
#> Warning in mean.default(x[, 2]): l'argument n'est ni numérique, ni
#> logique : renvoi de NA
#> [1] NA
```

you need to apply on a vector. Here is different working way

``` r
mean(pull(x, cyl)) # pull allow you to pull a vector
#> [1] 6.1875
mean(x[,2, drop = TRUE]) # tbl does not drop by default
#> [1] 6.1875
mean(x[,2]$cyl)
#> [1] 6.1875
mean(x[,"cyl"], drop = TRUE)
#> Warning in mean.default(x[, "cyl"], drop = TRUE): l'argument n'est ni
#> numérique, ni logique : renvoi de NA
#> [1] NA
mean(x$cyl)
#> [1] 6.1875

summarise(x, m = mean(cyl))
#> # A tibble: 1 x 1
#>       m
#>   <dbl>
#> 1  6.19
summarise(x, m = mean(cyl)) %>% pull(m)
#> [1] 6.1875
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

Do not hesitate to ask this type of question in https://community.rstudio.com. There is a lot of people to help. 

Hope it helps.

**Comment by romainfrancois** [comment]
Thanks @cderv for the detailed explanation.
