### ISSUE TITLE
Reverse order of `dplyr::recode()` to match `forcats::fct_recode()`

### ISSUE THREAD

**Issue by sowla** [tidyverse/dplyr#4473]
As mentioned in https://github.com/tidyverse/forcats/issues/134

> The order of the new and old names for fct_recode and recode are reversed. That is to say, fct_recode(data, new_name = "old_name") but recode(data, old_name = "new_name").

``` r
example_vector <- letters[1:5]
forcats::fct_recode(example_vector, new_name = "a")
#> [1] new_name b        c        d        e       
#> Levels: new_name b c d e
dplyr::recode(example_vector, a = "new_name")
#> [1] "new_name" "b"        "c"        "d"        "e"
```

<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Hadley mentioned that he believes the fct_recode API should stay the same and I should open an issue in dplyr

> I am now sure that the tidyverse standard way should be new_name = old_name because that matches the syntax of mutate(). And when relabelling factors, it should be new_level = "old_level" because old_level is not an existing variable.

**Comment by romainfrancois** [comment]
@sowla I tagged this with the `tidy-dev-day` label as well

**Comment by hadley** [comment]
I think this is probably a bit big for TDD, particularly since if we're going to rewrite it, we'd use vctrs.

**Comment by andrasberczi** [comment]
The thing that makes this hard is that when you want to specify the new name on the left hand side (such as `dplyr::recode(example_vector, new_name = "a")` ), you won't know the type of `new_name`. That is a problem, because if you want to replace something by a number, you won't know if the user have provided that number as a character or as a numeric.

A possible solution can be using the [vctrs](https://github.com/r-lib/vctrs) package to determine the type of the input vector and then cast `new_name` to that type.
An additional difficulty can be when the user passes an integer to `new_name` (eg.: 10L). In this case probably the "L" part should be "cut" or maybe throw an error message?

**Comment by andrasberczi** [comment]
I was trying to finish my solution I started on tidy dev day and I realised that we cannot know in the reversed order if the user have provided a character or a numerical value as written above (eg.: we want to replace "a" by 1 or "1"). One solution can be that the type of the new value has to be the same as the input values, but that would be a restriction compared to how the function works now. What do you think @hadley @romainfrancois ?

**Comment by hadley** [comment]
@andrasberczi yeah, I think we'll probably need to totally rethink the design of this function.

**Comment by hadley** [comment]
Closing this issue here, because it requires a full rethinking of `recode()`, which is going to happen in the funs package, https://github.com/r-lib/funs/issues/29.
