### ISSUE TITLE
Can't pass additional arguments to group_modify() function

### ISSUE THREAD

**Issue by earcanal** [tidyverse/dplyr#4509]
I have some code which seems to have broken since `group_map()` became `group_modify()`. Converting to `group_modify()` only partially resolves this as my function also requires additional arguments. Under the old `group_map()` my function received args passed in `...`, but I get an error for the same function under the new `group_modify()`.

The docs indicate I should be able to do this:

> ...  Additional arguments passed on to .f

Is this a regression, or am I doing something wrong?

```
# dplyr_0.8.3
library(tidyverse)

m <- function(x, y, a, b) {
  tibble(z = z)  
}

mtcars %>%
  group_by(cyl) %>%
  group_modify(m, 1, 2) %>%
  ungroup

Error in (function (.x, .y)  : unused arguments (1, 2)
```

**Comment by cderv** [comment]
I think there is indeed an issue in `group_modify`
https://github.com/tidyverse/dplyr/blob/ec0949254dbbfab3d836d3633d15ec9b3dd724dd/R/group_map.R#L153-L166

the `...` are passed to a new  `fun` of two arguments `.x` and `.y` but then a re-pass in `group_map` applied on `fun` and this is where the error comes from because `fun` does not expect more than its two arguments.

I don't think the dots need to be passed in the second case and it should be
```r
chunks <- group_map(.tbl, fun, keep = keep)
```

**Comment by billdenney** [comment]
I experienced the same issue just now.  @cderv, I came up with the same fix before coming to the issue, so I included both of our names in the NEWS file.

**Comment by cderv** [comment]
Oh thanks ! I forgot about that one and forgot to do a PR 🤦‍♂ 
Thank @billdenney ! it was not necessary to mention me in NEWS but I appreciate it. 👍
