### ISSUE TITLE
Calculation of lagged factor variables became much slower between 0.7.4 and 0.8.3

### ISSUE THREAD

**Issue by mpelath** [tidyverse/dplyr#4561]
Not much I can add to what's below, except that based on what else I've been seeing, I don't believe this is specific to the lag function, but rather a more general issue with grouped mutates involving factor variables.

``` r
library(tidyverse)
data <- data <- tibble(x = rep(seq(1, 10000), each = 10),
                       t = rep(seq(1, 10), 10000),
                       y = as_factor(rep(c("A","B","C","D","E"), 20000)))
system.time(result <- data %>%
              arrange(x, t) %>%
              group_by(x) %>%
              mutate(y_lag = lag(y)) %>%
              ungroup()) 

# dplyr 0.8.3
# user  system elapsed 
# 2.59    3.34    5.99 

# dplyr 0.7.4
# user  system elapsed 
# 0.05    0.02    0.06
```

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mpelath** [comment]
Workaround is to create a version of the original data with the grouping variable, a shifted version of the "time" variable, and the variable to be lagged, and then left join that to the original data.  This takes about the same amount of time as in 0.7.4, at least in this example.

**Comment by romainfrancois** [comment]
It would be interesting to break down these timings per operation. I'm seeing this on my machine with the `dev_0_9_0` branch: 

``` r
library(tidyverse)
data <- data <- tibble(x = rep(seq(1, 10000), each = 10),
  t = rep(seq(1, 10), 10000),
  y = as_factor(rep(c("A","B","C","D","E"), 20000)))
system.time(result <- data %>%
    arrange(x, t) %>%
    group_by(x) %>%
    mutate(y_lag = lag(y)) %>%
    ungroup()) 
#>    user  system elapsed 
#>   1.780   0.015   1.794
```

**Comment by hadley** [comment]
I pulled the pieces apart to make it more obvious where the performance work needs to happen:

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)

df <- tibble(
  g = rep(1:10000, each = 10),
  y = factor(rep(c("A", "B", "C", "D", "E"), 20000))
)

df_g <- group_by(df, g)
x_g <- unname(split(df$y, df$g))

all.equal.tbl_df <- all.equal.default

system.time(mutate(df_g, z = dplyr::lag(y)))
#>    user  system elapsed 
#>   2.518   0.008   2.529
system.time(lags <- lapply(x_g, dplyr::lag))
#>    user  system elapsed 
#>   1.347   0.002   1.351
system.time(vec_c(!!!lags))
#>    user  system elapsed 
#>   0.565   0.001   0.567

# Use simpler vctrs implementation
lag2 <- function(x) {
  vec_slice(x, c(NA, 2:vec_size(x)))
}
system.time(mutate(df_g, z = lag2(y)))
#>    user  system elapsed 
#>   1.004   0.003   1.008
system.time(lags <- lapply(x_g, lag2))
#>    user  system elapsed 
#>   0.109   0.000   0.109
system.time(vec_c(!!!lags))
#>    user  system elapsed 
#>   0.590   0.002   0.592

# Use base R implementation
lag3 <- function(x) {
  x[c(NA, 2:vec_size(x))]
}
system.time(mutate(df_g, z = lag3(y)))
#>    user  system elapsed 
#>   0.936   0.002   0.939
system.time(lags <- lapply(x_g, lag3))
#>    user  system elapsed 
#>   0.070   0.000   0.071
system.time(vec_c(!!!lags))
#>    user  system elapsed 
#>   0.587   0.001   0.590

ints <- lapply(lags, as.integer)
system.time(vec_c(!!!ints))
#>    user  system elapsed 
#>   0.004   0.000   0.004 
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So we have a few problems:

* The current implementation of `lag()` is inefficient for the simple case where `default = NA`. I've made a note to resolve that in https://github.com/r-lib/funs/issues/34

* `vec_slice()` is mildly inefficient (0.1 vs 0.07) probably because vctrs doesn't have a fast C path for factors yet. That's being tracked at https://github.com/r-lib/vctrs/issues/705

* `vec_c(!!!x)` is seriously inefficient for a vector of factors. This will also be fixed in https://github.com/r-lib/vctrs/issues/705; I'm confident we should be able to get very good performance for this case where all the levels are the same because the levels vectors point to the same object in memory.

These are now all tracked elsewhere, so I'm going to close this issue.
