### ISSUE TITLE
Incorrect output from summarize when counting NA

### ISSUE THREAD

**Issue by jonspring** [tidyverse/dplyr#4585]
I am summarizing NA's in a data set but getting odd results depending on whether I count missingness before or after I count non-missingness. Using dplyr 0.8.3.

```
my_data <- structure(list(cont_dt = structure(c(1, NA_real_, NA_real_
    ), class = c("int"))), row.names = c(NA, 
    -3L), class = "data.frame")

library(dplyr)
my_data %>%  
  summarise(na      = sum(is.na(cont_dt)),   # 2: good
            cont_dt = sum(!is.na(cont_dt)),  # 1: good
            missing = sum(is.na(cont_dt)))   # 0: WAT
```

**Comment by cderv** [comment]
I think this is because you modify the column `cont_dt` inside the summarize and the new value is used in your last calculation. `mutate`works the same. if you use a new column name this is ok. 
In fact, the order in which you ask column creation is important, all the more when writing over an existing column. I think it is by design. 

``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

my_data <- tibble::tribble(
  ~cont_dt,
  "1",
  NA,
  NA
)

# column cont_dt is modified suring summarise
my_data %>%  
  summarise(
    na      = sum(is.na(cont_dt)),   
    cont_dt = sum(!is.na(cont_dt))
  )
#> # A tibble: 1 x 2
#>      na cont_dt
#>   <int>   <int>
#> 1     2       1

# if using nex column name
my_data %>%  
  summarise(na      = sum(is.na(cont_dt)),  
            cont_dt2 = sum(!is.na(cont_dt)), 
            missing = sum(is.na(cont_dt)))  
#> # A tibble: 1 x 3
#>      na cont_dt2 missing
#>   <int>    <int>   <int>
#> 1     2        1       2
```

<sup>Created on 2019-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hope it helps.

**Comment by jonspring** [comment]
Thank you, that's a very helpful explanation for something that had me stuck for a long time! To see what is in front of one's nose needs a constant struggle.
