### ISSUE TITLE
dplyr forward compatibility for rlang function switch_lang()

### ISSUE THREAD

**Issue by fungs** [tidyverse/dplyr#4600]
rlang 0.4.0 remove function switch_type. For that reason, dplyr 0.7.8 fails with rlang 0.4.0 with the following error (German locale).

```
Fehler in switch_lang(call, inlined = , namespaced = , recursive = eval_bare(call,  : 
  konnte Funktion "switch_lang" nicht finden
Ruft auf: <Anonymous> ... switch_type -> partial_eval -> switch_type -> lang_partial_eval
Ausführung angehalten
```

I'm not sure if version dependencies can be corrected in some way.

**Comment by lionel-** [comment]
Unfortunately we can't specify dependencies in that direction but we're going to try a new kind of warning that suggests updating downstream packages that are known not to be compatible.

I've only recently took conscience of the extent of this problem so I'll be less proactive into removing deprecated functions.

In general, please update all your packages rather than a subset to avoid this kind of problems.
