### ISSUE TITLE
cannot load dplyr after installing to custom library location

### ISSUE THREAD

**Issue by jangorecki** [tidyverse/dplyr#4641]
There seems to be an issue when installing dplyr to custom library path.
```sh
mkdir -p ./dplyr/r-dplyr
Rscript -e 'install.packages("dplyr", lib="./dplyr/r-dplyr")'
#also installing the dependencies ‘backports’, ‘ellipsis’, ‘zeallot’, ‘utf8’, ‘vc
#trs’, ‘cli’, ‘crayon’, ‘fansi’, ‘pillar’, ‘purrr’, ‘assertthat’, ‘pkgconfig’, ‘R
#6’, ‘tibble’, ‘tidyselect’, ‘BH’, ‘plogr’
#...
#* DONE (dplyr)
R
#R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
library("dplyr", lib.loc="./dplyr/r-dplyr")
#Error: package or namespace load failed for ‘dplyr’:
# .onLoad failed in loadNamespace() for 'pillar', details:
#  call: loadNamespace(name)
#  error: there is no package called ‘crayon’
list.files("./dplyr/r-dplyr/crayon/")
# [1] "ANSI-256-OSX.png" "ANSI-8-OSX.png"   "DESCRIPTION"      "help"            
# [5] "html"             "INDEX"            "LICENSE"          "logo.png"        
# [9] "logo.svg.gz"      "Meta"             "NAMESPACE"        "NEWS.md"         
#[13] "R"                "README.markdown" 
list.files("./dplyr/r-dplyr/pillar/")
#[1] "DESCRIPTION" "help"        "html"        "INDEX"       "Meta"       
#[6] "NAMESPACE"   "NEWS.md"     "R"          
library("pillar", lib.loc="./dplyr/r-dplyr")
#Error: package or namespace load failed for ‘pillar’:
# .onLoad failed in loadNamespace() for 'pillar', details:
#  call: loadNamespace(name)
#  error: there is no package called ‘crayon’
library("crayon", lib.loc="./dplyr/r-dplyr")
"package:crayon" %in% search()
#[1] TRUE
```
Installation goes successfully AFAIK, packages are there, but for some reason cannot be loaded. Using current CRAN version. Is there anything I should be aware of when attempting to install to custom library? The issue seems to be related to the way how `pillar` attempts to load `crayon`.

**Comment by jangorecki** [comment]
setting `.libPaths("./dplyr/r-dplyr")` just for the time to attach `dplyr` (and then removes custom lib from libPaths) resolves the problem of attaching dplyr, but then during print I am getting another error, related to a different package:
```r
print(head(ans, 3))
#Error in loadNamespace(name) : there is no package called ‘fansi’
```
I have to keep `.libPaths` pointing to my new custom library to make it work, and that undermines the library location R's feature.

**Comment by hadley** [comment]
Can you easily provide a traceback?

**Comment by jangorecki** [comment]
```r
mkdir -p ./dplyr/r-dplyr
Rscript -e 'install.packages("dplyr", lib="./dplyr/r-dplyr")'
R
library("dplyr", lib.loc="./dplyr/r-dplyr")
#Error: package or namespace load failed for ‘dplyr’:
# .onLoad failed in loadNamespace() for 'pillar', details:
#  call: loadNamespace(name)
#  error: there is no package called ‘crayon’
traceback()
#6: stop(msg, call. = FALSE, domain = NA)
#5: value[[3L]](cond)
#4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
#3: tryCatchList(expr, classes, parentenv, handlers)
#2: tryCatch({
#       attr(package, "LibPath") <- which.lib.loc
#       ns <- loadNamespace(package, lib.loc)
#       env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
#   }, error = function(e) {
#       P <- if (!is.null(cc <- conditionCall(e))) 
#           paste(" in", deparse(cc)[1L])
#       else ""
#       msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
#           sQuote(package), P, conditionMessage(e))
#       if (logical.return) 
#           message(paste("Error:", msg), domain = NA)
#       else stop(msg, call. = FALSE, domain = NA)
#   })
#1: library("dplyr", lib.loc = "./dplyr/r-dplyr")
```

**Comment by hadley** [comment]
@jangorecki would you mind re-running with `--vanilla`? I suspect the chances are low that you are loading tibble/pillar/crayon in your .Rprofile, but it's worth eliminating as a possible cause.

@gaborcsardi does this ring any bells? I have a vague recollection we've stumbled across this before in the context of packages loaded in the current session (but that doesn't look to be the case here since installation is done with `Rscript`).

@krlmlr I took a quick look at pillar, but we're not doing anything special with package loading, right? (We had a similar problem with tidyverse but that was we were manually attaching packages without [checking the path](https://github.com/tidyverse/tidyverse/issues/171))

**Comment by gaborcsardi** [comment]
Well, I am not sure what this is, do dplyr/pillar/etc. do something special about package loading?

But in general, the `lib` argument of `library()` will get you into trouble, more often than not. This is because some dependencies, even imported ones, are not loaded together with the package, not just dplyr, but in many packages. And then later, when R tries to load them on demand, they are not found, because that library that you used in `lib` is gone, or R finds the "wrong" version of the dependency in another library, etc.

If you want to use an isolated installation, I suggest that you install _all_ recursive dependencies into the same library (which is not the default in `install.packages()`), and then use only this library, plus the system library. (The system library should only contain the base and recommended packages.)

**Comment by jangorecki** [comment]
running the same on `r-base` docker image, I think this address _vanilla_ and _isolation_
```sh
docker pull r-base
docker run -it --rm r-base
dir.create("./tmplib")
install.packages("dplyr", lib="./tmplib")
library("dplyr", lib.loc="./tmplib")
#Error: package or namespace load failed for ‘dplyr’:
# .onLoad failed in loadNamespace() for 'pillar', details:
#  call: loadNamespace(name)
#  error: there is no package called ‘crayon’
```

**Comment by gaborcsardi** [comment]
This is a side effect of `lib.loc`, really. Here is the relevant stack for pillar, which is a bit simpler then dplyr and produces the same error:

```
 1: loadNamespace("pillar", lib.loc = "./tmplib/")
 2: runHook(".onLoad", env, package.lib, package)
 3: tryCatch(fun(libname, pkgname), error = identity)
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatchOne(expr, names, parentenv, handlers[[1]])
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: fun(libname, pkgname)
 8: assign_crayon_styles()
 9: make_style_fast("underline")
10: crayon::make_style
11: getExportedValue(pkg, name)
12: asNamespace(ns)
13: getNamespace(ns)
14: loadNamespace(name)
```

`loadNamespace()` itself passed on `lib.loc` to the underlying `loadNamespace()` calls when it loads imported packages, but crayon is not imported from pillar, but it is loaded in `pillar:::.onLoad()`, via `::`, which triggers another `loadNamespace()` call, and of course this time without the `lib.loc` argument.

This could be addressed in `loadNamespaces()` by putting `lib.loc. on the library path, and then removing it in `on.exit()`, instead of trying to pass it downstream, as the latter fails when packages are loaded on-demand from `.onload()`.

This might be considered as a `loadNamespace()` bug, I don't know. But even if it is a bug, and it will be fixed, or we work around it in pillar, `lib.loc` is still very dangerous, because dependencies that are loaded on demand via `::` will fail. In some sense it is actually better to fail at the package load already, instead failing later with some undefined behavior.
