### ISSUE TITLE
What is the best solution to keep row names following use of dplyr::arrange functions?

### ISSUE THREAD

**Issue by jafarilab** [tidyverse/dplyr#4887]
I think it sounds a kind of bug in dplyr that there is no possibility to keep row names after using arrange, arrange_all or arrange_if. I usually have to use rownames_to_column and, after using arrange again, use column_to_rownames. It also happens after using mutate_all. 
Is it possible to ask the maintainer to solve this problem? 
I think the point of arranging is working with the row names after the sorting.

---

I know the following solution but I think it is crazy and time-consuming.
```r
df %>%
    rownames_to_column('gene') %>%
    filter_if(is.numeric, all_vars(. >= 8)) %>%
    column_to_rownames('gene')
```

**Comment by romainfrancois** [comment]
This appears to be fixed in the development version. 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  filter_if(is.numeric, all_vars(. >= 1))
#>                 mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
#> Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
#> Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
#> Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
#> Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
#> Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
```

<sup>Created on 2020-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

For future reference, we prefer that you use [reprex](https://reprex.tidyverse.org) to share code, so that we can reproduce the code easily. 

See also: https://resources.rstudio.com/rstudio-conf-2020/object-of-type-closure-is-not-subsettable-jenny-bryan
