### ISSUE TITLE
between() no longer warns for factors

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#4929]
This used to give a warning, now it is silent. Is this intended?

``` r
dplyr::between(factor(1:5), 1, 3)
#> [1]  TRUE  TRUE  TRUE FALSE FALSE
```

<sup>Created on 2020-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@romainfrancois can you take a look at what happened here? It looks like the warning disappeared when you did the Rcpp rewrite. If it's simple to re-add, I think that would be be safest, otherwise we can consider a vctrs rewrite, which I think would be more dangerous because it's likely to have greater effects.
