### ISSUE TITLE
Taking the prototype of a grouped-df changes the order of grouping variables

### ISSUE THREAD

**Issue by lionel-** [tidyverse/dplyr#5040]
```r
gdf <- dplyr::group_by(mtcars, cyl, am, vs)

dplyr::group_vars(gdf)
#> [1] "cyl" "am"  "vs" 

dplyr::group_vars(gdf[0, ])
#> [1] "cyl" "vs"  "am" 
```

**Comment by DavisVaughan** [comment]
This seems to be because of the ordering in this `intersect()` call. 
https://github.com/tidyverse/dplyr/blob/792f9b1f96373dc1ee90a613ebba8c5aec4e7269/R/grouped-df.r#L213

It affects other methods too, which also use this ordering, like `$<-`.

``` r
library(dplyr, warn.conflicts = FALSE)

gdf <- group_by(mtcars, cyl, am, vs)

group_vars(gdf)
#> [1] "cyl" "am"  "vs"

gdf2 <- gdf
gdf$cyl <- 1

group_vars(gdf)
#> [1] "cyl" "vs"  "am"
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll work on a fix
