### ISSUE TITLE
`group_map()` family behavior is inconsistent with empty data frame

### ISSUE THREAD

**Issue by tzakharko** [tidyverse/dplyr#5046]
`group_map()` family invokes the closure when the input data frame is empty:

```r
tibble() %>% group_walk(~ { print("hello!") })

tibble(x=integer()) %>% group_by(x) %>% group_walk(~ { print("hello!") })
```

I consider this to be inconsistent behavior since `group_map()` otherwise does not invoke the closure for empty groups, this is not how purrr `map()` behaves either, and ultimately, runs contrary to the usual `map` semantics in FP.

**Comment by romainfrancois** [comment]
This isn't the choice that has been made here for type stability reasons. 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble() %>% 
  group_walk(~ { print("hello!") })
#> [1] "hello!"
```

In this first example, the expression `~ { print("hello!") }` applies to all the tibble, it just happens to have 0 rows and zero columns. you get one group of 0 rows. 

```
tibble(x=integer()) %>% 
  group_by(x) %>% 
  group_walk(~ { print("hello!") })
#> [1] "hello!"
```

Here the situation is somewhat different, and to maintain type stability, we have to do something special when there are 0 groups. In that case, we pretend there is one group of 0 rows so that the type of the results is consistent. 

This might be more relevant to `group_map()` than `group_walk()`. Alternatively you can use `group_split()` and use `purrr::walk()` instead: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

tibble(x=integer()) %>% 
  group_by(x) %>% 
  group_split() %>% 
  walk(~ { print("hello!") })
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tzakharko** [comment]
Thanks Romain! I think this is a rather interesting case because it exposes the ambiguities that can easily arise from the way R deals (or doesn't) with types. I have to say, I am not sure that I follow your explanation about type stability, in my understanding zero groups is no groups (and thus it surprises me that `group_by() %>% group_map()` etc.  should do something different than  `group_by() %>% group_split() %>% map()`). And of course, there is an ambiguity in what "zero-length data frame" actually means  — it can be either "no data" or "data of length zero" depending on what the user wants. 

Also, to make things more complicated, this is not the behavior you see with other dplyr predicates. For instance:

  ```r
tibble() %>% mutate(y=1)
tibble(x=integer()) %>% mutate(y=1)
tibble(x=integer()) %>% group_by(x) %>% mutate(y=1)
tibble(x=integer()) %>% group_by(x) %>% summarize(y=n())
```

The behavior here seems to be "zero-length data" is "no data" rather than "data of length zero" that `group_map()` takes.
