### ISSUE TITLE
Drop default() methods

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#5083]
There are probably few packages that rely on this fallback now, and it gives an unhelpful error message. 

``` r
dplyr::group_by(mean)
#> Warning: `group_by_()` is deprecated as of dplyr 0.7.0.
#> Please use `group_by()` instead.
#> See vignette('programming') for more help
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Error in UseMethod("group_by_"): no applicable method for 'group_by_' applied to an object of class "function"
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by julianstanley** [comment]
Hi @hadley, in the meantime, do you (or anyone else) have recommendations about what to do to avoid this warning?

I ask because, in plotly, the following code shows that warning (related to [PR mentioned above](https://github.com/ropensci/plotly/pull/1800)):

```R
library(plotly)
library(dplyr)
txhousing %>% plot_ly() %>% group_by(city)
```

Even after I changed all instances of `group_by_` in the package to `group_by`. 

I assume this is related to this issue, right? Since a plotly object isn't a dataframe, it triggers `.default()`? But quite a few of the tests in `plotly` use that general pattern, so they are all showing warnings. 

Plotly does have a method that converts a plotly object to a dataframe (`plotly_data()`). Should users just use that before piping to dplyr methods from now on?

```R
txhousing %>% plot_ly() %>% plotly_data() %>% group_by(city)
```

(I'm new to this so, if I'm completely off base here, please let me know :smile:)

**Comment by hadley** [comment]
I think this is probably a plotly issue so I’d recommend filing it there.

**Comment by simarjeetugra** [comment]
No Sir Same problem came when I use biblioshiny
