### ISSUE TITLE
select() does not preserve attributes for data frames

### ISSUE THREAD

**Issue by stibu81** [tidyverse/dplyr#5294]
According to the documentation, `select()` should preserve attributes ("Data frame attributes are preserved." in section Value). However, this seems to work only for tibbles, not for data frames. This is an reproducible example:

```
mtcars_df <- mtcars
attr(mtcars_df, "test") <- TRUE
mtcars_tib <- as_tibble(mtcars_df)
attr(mtcars_df, "test")
attr(mtcars_tib, "test")

attr(dplyr::select(mtcars_df), "test")
attr(dplyr::select(mtcars_tib), "test")
```

With dplyr 0.8.5, all the four calls of `attr()` return `TRUE` as expected. But with dplyr 1.0.0, `attr(dplyr::select(mtcars_df), "test")` returns `NULL`.

The result does not change, if some columns are selected.

**Comment by lionel-** [comment]
Right, currently the restoration when selecting columns is performed by `[.tbl_df`. Maybe we should call `dplyr_reconstruct()` in `dplyr_col_select()`, for consistency with other verbs.

**Comment by morganBaCT** [comment]
I think the same issue is happening with filter. it removes my unit attributes if I filter anything. Will this be fixed in a new release?

**Comment by hadley** [comment]
@morganBaCT can you please file a new issue with a reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df1 <- structure(data.frame(x = 1), y = 2)
df2 <- structure(tibble(x = 1), y = 2)

attr(select(df1, x), "y")
#> NULL
attr(select(df2, x), "y")
#> [1] 2
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Avi-Kenny** [comment]
I just stumbled upon the same issue, but for mutate()
