### ISSUE TITLE
Sporadic "can't slice a scalar" error when using filter

### ISSUE THREAD

**Issue by atakanekiz** [tidyverse/dplyr#5307]
I'm having a persistent (yet difficult to reproduce) problem. When I try to create a minimal reprex, my code doesn't fail. Interestingly, the exact code that fails, all of a sudden starts working when I mess around a bit. I'm at a loss. I will try to summarize the behaviour below

I have prepared an `sf`/`data.frame` using US Census data (via `tidycensus` package). I'm trying to `filter` based on race and create spatial plots. The code fails at the filter step:

```
library(dplyr)
library(ggplot)

# Works
df <- filter(iris, Species %in% c("setosa", "virginica")

# Fails
df <- filter(census, race %in% c("black", "white")

```

`traceback()` gives the following output:

```
17: vec_slice(data, i)
16: .row_names_info(x, type = 0L)
15: row.names %||% .row_names_info(x, type = 0L)
14: dplyr_new_data_frame(data)
13: dplyr_reconstruct(vec_slice(data, i), data)
12: dplyr_row_slice.data.frame(.data, loc, preserve = .preserve)
11: dplyr_row_slice(.data, loc, preserve = .preserve)
10: filter.data.frame(., race %in% c("black", "white"))
9: filter(., race %in% c("black", "white"))
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: totalpop %>% filter(race %in% c("black", "white"))

```

**However**, if I use the `subset()` function before `filter`, the failing code ***sometimes*** works:

```
a <- subset(census, race %in% c("black", "white))

# Works 
df <- filter(census, race %in% c("black", "white")

```

`sessionInfo()` output is as follows:

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.1 dplyr_1.0.0  

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11   knitr_1.28        magrittr_1.5      tidyselect_1.1.0  munsell_0.5.0     colorspace_1.4-1  R6_2.4.1         
 [8] rlang_0.4.6       fansi_0.4.1       tools_4.0.0       grid_4.0.0        gtable_0.3.0      xfun_0.14         sessioninfo_1.1.1
[15] cli_2.0.2         withr_2.2.0       ellipsis_0.3.1    assertthat_0.2.1  tibble_3.0.1      lifecycle_0.2.0   crayon_1.3.4     
[22] purrr_0.3.4       vctrs_0.3.1       glue_1.4.1        compiler_4.0.0    pillar_1.4.4      generics_0.0.2    scales_1.1.1     
[29] pkgconfig_2.0.3  
```

**Comment by atakanekiz** [comment]
Loading the `sf` package seemed to solve the problem. Does that mean `dplyr::filter()` is having hard time subsetting `sf` objects?

**Comment by lionel-** [comment]
It's probably the `sfc` lists. In the tidyverse there are two ways of declaring a custom list is really a list and not a scalar object like a model object `lm(y ~ x)`. You can either:

* Add `"list"` to your class vector (preferred solution because then your list can dispatch on `.list` methods).

* Implement `vctrs::vec_proxy()`. This is what `sfc` lists do.

The downside of the latter solution is that the package that implements the method must be loaded in R for the method to take effect. And unfortunately, loading a saved dataset with columns created by certain packages does not load the package in memory.

Note that this isn't specific to `vec_proxy()`, many methods will be missing and you can't really safely work with your sf data frames or geometry columns without the package being loaded in memory. To be safe, you need a `stopifnot(rlang::is_installed("sf"))`. This will cause an error if sf is not installed, and load it in memory otherwise.
