### ISSUE TITLE
Does if_else always evaluate both 'true' and 'false' regardless of 'condition'?

### ISSUE THREAD

**Issue by jwilliman** [tidyverse/dplyr#5341]
It appears to me that `if_else` evaluates both the `true` and `false` arguments, and then returns only the one that matches the `condition` argument. This differs from `ifelse` which appears to only evaluate the `true` or `false` argument that matches the `condition` argument. 

This is a problem if `if_else` is being used to avoid evaluating an expression that is know to fail in certain situations. Is this necessary to ensure "that `true` and `false` are the same type."? What would be a `tidyverse` way of handling this? 

``` r

x <- list("a", 1, 2, "b")

sapply(x, function(x) ifelse(is.numeric(x), x + 1, NaN)) 
#> [1] NaN   2   3 NaN
sapply(x, function(x) dplyr::if_else(is.numeric(x), x + 1, NaN))
#> Error in x + 1: non-numeric argument to binary operator
```

<sup>Created on 2020-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hongooi73** [comment]
> This differs from `ifelse` which appears to only evaluate the true or false argument that matches the condition argument.

Eh?

```
> ifelse(c(FALSE, TRUE), 1:2, c(3, stop()))
Error in ifelse(c(FALSE, TRUE), 1:2, c(3, stop())) : 
```

**Comment by lionel-** [comment]
`if_else()` does not have short-circuiting semantics. Use `if ()` if you need short-circuiting. It is necessary to compute both sides of the condition to figure out the return type. The code you have reported is a type error. In my opinion it is also a bit hard to understand because it relies on a strange mix of scalar predicate and recycling.
