### ISSUE TITLE
dplyr mismatch on data

### ISSUE THREAD

**Issue by 1Coleman** [tidyverse/dplyr#5386]
After downloading GWAS data online and extracting the needed columns with awk, the resulting file was saved into excel.
However, 1 am trying to subset some rows (SNPs) generated from another data. Even though, there is match
<img width="593" alt="Screenshot 2020-07-07 at 16 48 39" src="https://user-images.githubusercontent.com/62238530/86747144-8350b580-c076-11ea-90a5-f273a4c5efd3.png">
 between the two dataset, either VLOOKUP in excel or left_join function in dplyr R package returns NA. 

Very strange as these functions works on self generated dataset. I suspect that something is wrong with the GWAS data curated from online. Attached 

Respectfully , your suggestions will be highly appreciated.
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by 1Coleman** [comment]
Great. Indeed Replex is new to me so I will go through as suggested. 
Thank you very much
