### ISSUE TITLE
Should there be a is_rowwise_df() function?

### ISSUE THREAD

**Issue by jmgirard** [tidyverse/dplyr#5391]
A row-wise data frame is implicitly grouped by row, but is not a `grouped_df`. This makes it so that `is_grouped_df()` returns `FALSE` when passed a row-wise data frame, and that is consistent. However, I can't seem to find an equivalent function for the `rowwise_df` class. Should there be a `is_rowwise_df()` function?

```r
library(tidyverse)
rdf <- rowwise(diamonds)
is_grouped_df(rdf)
#> [1] FALSE
is(rdf, "rowwise_df")
#> [1] TRUE
```

**Comment by hadley** [comment]
What are you trying do where this matters? Typically, this question suggests you might be better off with a slightly different approach.

**Comment by jmgirard** [comment]
I am preparing a didactic blog post about row-wise operations and wanted to show when the implicit grouping is and isn't retained. I can use the `is()` function as above, but it seemed like if `is_grouped_df()` isgoing to return `FALSE`, there should be another function that returns `TRUE`.

**Comment by hadley** [comment]
You should definitely use `inherits()`, not `is()` (since `is()` implies S4), but I for the purposes of explanation, I'd think something like `group_rows()` or `group_indices()` or `group_data()` would give you a better sense for what's going on under hood (esp. since it also explains how ungrouped data frames work).

**Comment by jmgirard** [comment]
Good to know about `inherits()`, thanks. Sounds like you don't think `is_rowwise_df()` is needed more broadly, so I guess we can close this.
