### ISSUE TITLE
c_across behaviour surprising (to me) due to everything() auto update

### ISSUE THREAD

**Issue by courtiol** [tidyverse/dplyr#5410]
Since `c_across()` is quite recent, I wanted to share an observation.
In the following, I would have expected "small" to be 1.
```r
> data.frame(x = c(1, 2), y = c(30, 40)) %>%
+   rowwise() %>%
+   mutate(big   = sum(c_across() >= 10),
+          small = sum(c_across() < 10))
# A tibble: 2 x 4
# Rowwise: 
      x     y   big small
  <dbl> <dbl> <int> <int>
1     1    30     1     2
2     2    40     1     2
```
In hindsight, I understand why this is happening: `c_across()` takes `everything()` as `cols` and during the second call "big" is added to content of `everything()`.

This can obviously be avoided by setting "x:y" in the calls to `c_across()` to bypass the calls to `everything()`.

Yet, I wonder if you did really want that multiple calls to `everything()` within a single mutate do update their scope.

**Comment by romainfrancois** [comment]
Yeah, it's a feature that has always been central to what dplyr does, it gets more confusing now because it is easier with `across()` and `c_across()`. 

One thing you can do is make one result out of the 2 by packing them into a data frame, that then gets automatically spliced: 

``` r
library(dplyr, warn.conflicts = FALSE)
data.frame(x = c(1, 2), y = c(30, 40)) %>%
  rowwise() %>%
  mutate(data.frame(
    big   = sum(c_across() >= 10),
    small = sum(c_across() < 10)
  ))
#> # A tibble: 2 x 4
#> # Rowwise: 
#>       x     y   big small
#>   <dbl> <dbl> <int> <int>
#> 1     1    30     1     1
#> 2     2    40     1     1
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
