### ISSUE TITLE
`group_split` drops classes after splitting

### ISSUE THREAD

**Issue by shahronak47** [tidyverse/dplyr#5481]
Taken from this original post on StackOverflow - https://stackoverflow.com/questions/63442620/using-group-split-while-maintaining-data-structure 

```
library(osfr)
library(dplyr)

project_data =  osf_retrieve_user("qs9fc") %>%   osf_ls_nodes() 
class(project_data)
#[1] "osf_tbl_node" "osf_tbl"      "tbl_df"       "tbl"          "data.frame"  

tmp <- project_data %>% group_split(row_number(), .keep = FALSE)
class(tmp[[1]])
#[1] "tbl_df"     "tbl"        "data.frame"
tmp_s <- split(project_data, seq_len(nrow(project_data)))
class(tmp_s[[1]])
#[1] "osf_tbl_node" "osf_tbl"      "tbl_df"       "tbl"          "data.frame" 
```
I'm on R 4.0.0.
```
packageVersion('dplyr')
#[1] ‘1.0.1’
packageVersion('osfr')
#[1] ‘0.2.8’
```
Why `group_split` does not maintain the classes like `base::split` ? 

I found this previous issue https://github.com/tidyverse/dplyr/issues/5165 related but the issue is closed.

**Comment by DavisVaughan** [comment]
`group_split.data.frame()` internally groups the data frame with `group_by()` to compute the rows to group by. It then `ungroup()`s that grouped data frame and splits that object. The implementation was done this way to unify the implementation of the ungrouped, grouped, and rowwise cases. It is this group/ungroup dance where the class is lost.

I think the osfr package should implement `group_by()` and `ungroup()` methods for their subclass. That is what we recommended for tsibble in https://github.com/tidyverse/dplyr/pull/5175, and it works nicely because they don't need a `group_split()` method. For osfr, they'd get a `grouped_osf_tbl` from `group_by()`, and `ungroup()`ing that gives a `osf_tbl` back.

---

I don't particularly like this alternative, but I suppose `group_split_impl()` could be modified to take an already ungrouped `data`, and then we could add an `indices` argument. Then the core of `group_split.data.frame()` would become:

```r
group_split.data.frame <- function(.tbl, ..., .keep = TRUE, keep = deprecated()) {
  gdf <- group_by(.tbl, ...)
  indices <- group_rows(gdf)
  group_split_impl(.tbl, indices, .keep = .keep)
}
```

and `group_split.grouped_df/rowwise_df()` would be:

```r
group_split.grouped_df <- function(.tbl, ..., .keep = TRUE, keep = deprecated()) {
  indices <- group_rows(.tbl)
  .tbl <- ungroup(.tbl)
  group_split_impl(.tbl, indices, .keep = .keep)
}
```

I don't like this because these would then return different things because osfr doesn't have a `group_by()` method. I think these should be consistent, which implies that the current implementation is right.

```r
# Would return a `osf_tbl` with the tweak because `group_split()` would keep the subclass
project_data %>% 
  group_split(row_number(), .keep = FALSE) %>%
  magrittr::extract2(1) %>%
  class()
  
# Would return a `tbl_df` because the `group_by()` drops the subclass
# (as it should)
project_data %>% 
  group_by(rn = row_number()) %>%
  group_split(.keep = FALSE) %>%
  magrittr::extract2(1) %>%
  class()
```
