### ISSUE TITLE
The NULL hypothesis of inconsistent case_when outputs

### ISSUE THREAD

**Issue by geotheory** [tidyverse/dplyr#5572]
Noting the documentation's reference that "NULL inputs are ignored", and yet..

```
x = NULL
case_when(is.null(x) ~ 1, TRUE ~ 2)
#> [1] 1
```

But then there's this - all intended behaviour?

```r
case_when(is.null(x) ~ 1, is.na(x) ~ 2, TRUE ~ 3)
#> numeric(0)
x = c(1,2,NA)
case_when(is.null(x) ~ 1, TRUE ~ 2)
#> [1] 2
case_when(is.null(x) ~ 1, is.na(x) ~ 2, TRUE ~ 3)
#> [1] 3 3 2
```

This is important because given e.g. Shiny inputs we need a more elegant way to handle input variables that can be NULL, NA, atomic or vectors.  Is there no way around `if(is.null(input$foo))...`?

**Comment by courtiol** [comment]
I don't have the same output, I think you had issue in copy/pasting:
```r
    library(dplyr)
    x <- NULL
    case_when(is.null(x) ~ 1, TRUE ~ 2)
    #> [1] 1
    case_when(is.null(x) ~ 1, is.na(x) ~ 2, TRUE ~ 3)
    #> numeric(0)
    case_when(is.null(x) ~ 1, TRUE ~ 2)
    #> [1] 1
    case_when(is.null(x) ~ 1, is.na(x) ~ 2, TRUE ~ 3)
    #> numeric(0)
```

NULL is ignored but is.null(NULL) is not: you did not pass NULL to case_when() but a logical and so no problem on that side.
The inconsistency above between 1 and numeric(o) is that case_when evaluate all condition and is.na(NULL) does not return TRUE or FALSE:
```r
is.na(NULL)
#> logical(0)
```

So just do:

```r
case_when(is.null(x) ~ 1, TRUE ~ 2)
case_when(is.null(x) ~ 1, !is.null(x) && is.na(x) ~ 2, TRUE ~ 3)
case_when(is.null(x) ~ 1, TRUE ~ 2)
case_when(is.null(x) ~ 1, !is.null(x) && is.na(x) ~ 2, TRUE ~ 3)
```

**Comment by geotheory** [comment]
@courtiol Thanks but you didn't update the `x` object as I did.  For clarity:

require(dplyr)
x1 = NULL
case_when(is.null(x1) ~ 1, TRUE ~ 2)
#> [1] 1
case_when(is.null(x1) ~ 1, is.na(x1) ~ 2, TRUE ~ 3)
#> numeric(0)

x2 = c(1, 2, NA)
case_when(is.null(x2) ~ 1, TRUE ~ 2)
#> [1] 2
case_when(is.null(x2) ~ 1, is.na(x2) ~ 2, TRUE ~ 3)
#> [1] 3 3 2

**Comment by courtiol** [comment]
Sorry @geotheory, I had missed your `x=c(1,2,NA)`.
Note that `is.null(c(1, 2, NA))` returns only a single logical (here FALSE).
This is because vectors cannot have NULL elements, so a single test is done.
So first test outside case_when if the object is NULL, then do a case when if it is not.

**Comment by geotheory** [comment]
I appreciate how the situation arises. I was hoping `case_when` would be versatile enough to help make build more elegant handlers for variables that might arrive in any length or value state, but admittedly this is probably not an intended use case.

**Comment by courtiol** [comment]
You probably have understand it @geotheory, but just to recap, as a general rule:

*if the output must in some cases be of different length as input, you must use `if() ... else()` and neither `ifelse()`, `if_else()` nor `case_when()`.*

The latter 3 functions enforce input and output to be of same length **by design** and this can cause problems as you have experienced it. Here is another example of such "problems":
``` r
ifelse(TRUE, 1:2, 3:4)
#> [1] 1

if(TRUE) 1:2 else 3:4
#> [1] 1 2
```

The function `if_else()` form dplyr, would not run in such case, to prevent the automatic resizing that `ifelse()` does.


The point of the latter 3 functions is that they produce composite output (not sure this is the right term for this, but bear with me): picking some elements from `true` and some from `false` to make a new vector of the same length as `test`:
``` r
dplyr::if_else(c(TRUE, FALSE), 1:2, 3:4)
#> [1] 1 4
```

If you don't have vector as input, then the benefit from generating a composite output is moot and I would stick to `if() ... else()` which is more flexible and safer, as you can see it here:

``` r
test_dplyr <- function(x, true, false, missing) dplyr::if_else(x, true, false, missing = missing)

## vector as input
test_dplyr(c(TRUE, TRUE, TRUE), 1:3, 4L, NA_integer_) ## non-composite output but could be!
#> [1] 1 2 3
test_dplyr(c(FALSE, FALSE, FALSE), 1:3, 4L, NA_integer_) ## non-composite output but could be!
#> [1] 4 4 4
test_dplyr(c(FALSE, TRUE, FALSE), 1:3, 4L, NA_integer_) ## composite!
#> [1] 4 2 4
test_dplyr(c(NA, NA, NA), 1:3, 4L, NA_integer_) ## composite!
#> [1] NA NA NA

## scalar as input
test_dplyr(TRUE, 1L, 4L, NA_integer_)
#> [1] 1
test_dplyr(FALSE, 1L, 4L, NA_integer_)
#> [1] 4
test_dplyr(NA, 1L, 4L, NA_integer_)
#> [1] NA

## input and output of different length
## -> cannot do

test_robust <- function(x, true, false, missing) if (!is.na(x) && x) true else if(!is.na(x) && !x) false else missing

## vector as input
## -> cannot do

## scalar as input
test_robust(TRUE, 1L, 4L, NA_integer_)
#> [1] 1
test_robust(FALSE, 1L, 4L, NA_integer_)
#> [1] 4
test_robust(NA, 1L, 4L, NA_integer_)
#> [1] NA

## input and output of different length -> OK
test_robust(TRUE, 1:4, 4L, NA_integer_)
#> [1] 1 2 3 4
test_robust(FALSE, 1:4, 4L, NA_integer_)
#> [1] 4
test_robust(NA, 1:4, 4L, NA_integer_)
#> [1] NA
```

The same applies for `case_when()` and `NULL`.

If you would relax the rule "output must be of same length as input" in `if_else()` (or `case_when()`), then it's not obvious how such functions could generally decide to apply composition or not, but perhaps it would be possible... need more time to think.
