### ISSUE TITLE
filter fails to find existing column values, if matches are stored in variable

### ISSUE THREAD

**Issue by FabianRoger** [tidyverse/dplyr#5728]
I have no idea what is going on here.

```
library(dplyr)
library(ggplot)

data(diamonds)

diamonds <- mutate(diamonds, ID = paste("ID", 1:n(), sep = ""))

set.seed(934)
x <- sample(diamonds$ID, 5)
x
```

![image](https://user-images.githubusercontent.com/5137092/106730756-fe7b4980-660e-11eb-8a06-772a0a301846.png)

**fails**

```
filter(diamonds, ID %in% x)
```
![image](https://user-images.githubusercontent.com/5137092/106730836-194dbe00-660f-11eb-8470-510fe5a29954.png)

**works**

```
filter(diamonds, ID %in% c("ID27448", "ID15133", "ID16866", "ID46332", "ID10482"))
```

![image](https://user-images.githubusercontent.com/5137092/106730973-3edac780-660f-11eb-90f5-d93fe68002be.png)

![image](https://user-images.githubusercontent.com/5137092/106730666-e7d4f280-660e-11eb-9e1f-6a771299be2f.png)

**Comment by zenggyu** [comment]
That's because the dataframe `diamonds` also contains a column named `x` (see `diamonds$x`), and in `filter()` (or `mutate()`, etc.), column names always mask global variables with the same name.

To avoid this, you can tell `filter()` to look for global variables explicitly by adding `!!` before the variable, i.e., `filter(diamonds, ID %in% !!x)`.

I think it is a good practice to always add `!!` before any global variable you use in `filter()`, `mutate()`, etc.

**Comment by FabianRoger** [comment]
omg, thank you. 

I just used the diamonds data for another repex and this drove me absolutely bollocks.
