### ISSUE TITLE
summarise (across(...), var = ...) strangely miscalculate

### ISSUE THREAD

**Issue by Maxime2506** [tidyverse/dplyr#5747]
Hi,
Here a quick example of the issue :

test <- tibble(x = 1:10, weight = 1:10, cl = c(rep("A", 5), rep("B",5)))

test %>% group_by(cl) %>% summarise(across(everything(), mean), ww = sum(weight))
test %>% group_by(cl) %>% summarise(ww = sum(weight))

The first calculation of ww gives a false result. The second gives the good one.

**Comment by romainfrancois** [comment]
Please use [reprex](https://reprex.tidyverse.org) when posting examples, so that: 
 - we immediately see outputs
 - code is nicely formatted
 - you don't get asked to use reprex :-)

**Comment by romainfrancois** [comment]
What's happening here is that the `across()` call expands to `x = mean(x), weight = mean(weight)`: 

``` r
library(dplyr)

test <- tibble(x = 1:10, weight = 1:10, cl = c(rep("A", 5), rep("B",5)))

test %>% 
  group_by(cl) %>% 
  summarise(
    x = mean(x), weight = mean(weight), 
    ww = sum(weight)
  )
#> # A tibble: 2 x 4
#>   cl        x weight    ww
#> * <chr> <dbl>  <dbl> <dbl>
#> 1 A         3      3     3
#> 2 B         8      8     8
```

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

One workaround is to do `ww` before `weight` is modified: 

``` r
library(dplyr)

test <- tibble(x = 1:10, weight = 1:10, cl = c(rep("A", 5), rep("B",5)))

test %>% 
  group_by(cl) %>% 
  summarise(
    ww = sum(weight),
    across(-ww, mean)
  )
#> # A tibble: 2 x 4
#>   cl       ww     x weight
#> * <chr> <int> <dbl>  <dbl>
#> 1 A        15     3      3
#> 2 B        40     8      8
```

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Another way would be to`stitch()` them together into a single data frame so that as far as `summarise()` is concerned, `weight` has not been modified when `ww` is calculated: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs, warn.conflicts = FALSE)

test <- tibble(x = 1:10, weight = 1:10, cl = c(rep("A", 5), rep("B",5)))

stitch <- function(...) {
  new_data_frame(df_list(...))
}

test %>% 
  group_by(cl) %>% 
  summarise(
    stitch(across(everything(), mean), ww = sum(weight))
  )
#> # A tibble: 2 x 4
#>   cl        x weight    ww
#> * <chr> <dbl>  <dbl> <int>
#> 1 A         3      3    15
#> 2 B         8      8    40
```

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Maxime2506** [comment]
Ok, your first solution is quite elegant, I didn't know this one, but my
point wasn't that I didn't know how to bypass this issue.
My point is that it is counter intuitive and misleading.
I keep thinking that it has to be changed in dplyr, but maybe I'm the only
one to find this misleading, am I?
MP

Le mer. 10 févr. 2021 à 14:47, Romain François <notifications@github.com> a
écrit :
