### ISSUE TITLE
<error/tibble_error_assign_columns_non_na_only> when trying to left_join

### ISSUE THREAD

**Issue by cschwab1** [tidyverse/dplyr#5853]
Apologies in advance for not including a reproducible example, but I'm having some issues with dataframes in RStudio. This only started about 15 minutes ago, and previously working with these dataframes was fine, but now when I try to join two dataframes using `left_join(b09g, b11c, by=c("RAUMID"))`, I get the error `Error: Can't use NA as column index in a tibble for assignment`. The full error using `rlang::last_error()` is pasted below: 

```
<error/tibble_error_assign_columns_non_na_only>
Can't use NA as column index in a tibble for assignment.
Backtrace:
    █
 1. ├─gentriclass(b09g) %>% left_join(., b11c, by = c("RAUMID"))
 2. ├─dplyr::left_join(., b11c, by = c("RAUMID"))
 3. └─dplyr:::left_join.data.frame(., b11c, by = c("RAUMID"))
 4.   └─dplyr:::join_mutate(...)
 5.     ├─base::`[<-`(...)
 6.     └─tibble:::`[<-.tbl_df`(...)
 7.       └─tibble:::tbl_subassign(x, i, j, value, i_arg, j_arg, substitute(value))
 8.         └─tibble:::vectbl_as_new_col_index(j, x, value, j_arg, value_arg)

```

Additionally, when I type df$var into the console for just a few select dataframes, a small error message appears next to the text saying `(TypeError) : cannot read property 'substr' of null`. 

I'm pretty new to R and Rstudio, and this hasn't ever happened before — I've tried updating both `tidyverse` and updating to the newest version of RStudio, but nothing seems to help.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by romainfrancois** [comment]
Closing this now, please @cschwab1 open a new issue when/if you can reproduce the problem, and share the problematic code with the help of the [reprex](https://reprex.tidyverse.org/index.html) package.
