### ISSUE TITLE
Error with filter() 

### ISSUE THREAD

**Issue by Brahim-zr** [tidyverse/dplyr#5872]
Hi everyone,

I have a very simple question (I'm new to R) about filtering with dplyr. 

So when I run this code, everything works perfectly: 

Reactance_chatbot <- chatbot_study %>%
  filter(condition == "chatbot") %>%
  select(starts_with("d07_reactance"))

But when I switch the order, and put the select before the filter (see below), I get an error message: 

Reactance_chatbot <- chatbot_study %>%
  select(starts_with("d07_reactance")) %>%
  filter(condition == "chatbot")

Error: Problem with `filter()` input `..1`.
x object 'condition' not found
i Input `..1` is `condition == "chatbot"`.
Run `rlang::last_error()` to see where the error occurred.

<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'condition' not found
i Input `..1` is `condition == "chatbot"`.
Backtrace:
  1. dplyr::select(., starts_with("d07_reactance"))
  2. dplyr::filter(., condition == "chatbot")
 15. dplyr:::h(simpleError(msg, call))

Can someone help me and explain why code nr1 works perfect, but code nr2 is facing an error message? 

Thank you!
Brahim

**Comment by romainfrancois** [comment]
It's hard to say without being able to run the code. I'd suggest preparing such questions with the help of the reprex package next time; https://reprex.tidyverse.org

I guess the second example can't find the `condition` column because you've only selected columns that start with `"d07_reactance"`. 

I would suggest this kind of questions are more suited for https://community.rstudio.com
