### ISSUE TITLE
rowwise mutate overwrites future values in the list column

### ISSUE THREAD

**Issue by Fuco1** [tidyverse/dplyr#5900]
I have a tibble with nested tibbles and I want to perform some operation rowwise on each nested tibble.  To do this I run `mutate` with a block of code.  In the block I re-assigned the variable using `<-`.  For example, the column is called `x` and inside the block I do `x <- normalize(x); list(more_stuff(x))`.  I'm returning a list so it is later reassembled into a column of tibbles.

The minimal example I can provide is this:

First example, x is initialized to `1, 2` and I add 1 to `x` which correctly results in a list with `2, 3`.

```r
tibble(i = 1:2, x = list(1, 2)) %>% rowwise(i) %>% mutate(x = { list(x + 1) }) %>% pull(x)
```

In the second example, I re-assign `x` inside the mutate form.  This however causes all future values of `x` to retain the first row's value (`1`) and the output is `2, 2`.

```r
tibble(i = 1:2, x = list(1, 2)) %>% rowwise(i) %>% mutate(x = { x <- x; list(x + 1)}) %>% pull(x)
```

At least a warning of some sort would be nice since this is fairly unobvious as to why it shouldn't work.

**Comment by romainfrancois** [comment]
I believe this is an off-label use for which we can't really do much. 

Wrapping the code in a `local()` adds an environment for each group, which takes care of the problem: 

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(i = 1:2, x = list(1, 2)) %>% 
  rowwise(i) %>% 
  mutate(x = local({x <- x; list(x + 1)})) %>% 
  pull(x)
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
```

<sup>Created on 2021-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I believe however that a named function leads to code that is more expressive: 

``` r
library(dplyr, warn.conflicts = FALSE)

bump <- function(x) {
  x <- x
  list(x + 1)
}

tibble(i = 1:2, x = list(1, 2)) %>% 
  rowwise(i) %>% 
  mutate(x = bump(x)) %>% 
  pull(x)
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
```

<sup>Created on 2021-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Adding an extra environment always means that all uses have to "pay" for it, and other possibilities like disabling assignment have been discussed in the past but IIRC we ruled them out because of the unnecessary complexity this would bring. 

Perhaps @lionel- or @Hadley would have other views on this.

**Comment by Fuco1** [comment]
Thank you for an comprehensive answer.  For sure this is not an optimal way to express the algorithm, and as you say using functions is generally cleaner.  I'm not very knowledgable about the internals of R, environments and so and therefore debugging what's going on here was very difficult for me.

I find the solution with local/function perfectly fine and basically I'm asking here about:

1. Create a "Best practice".  Somewhere this should be documented as not recommended and/or broken.  Currently it feels like incorrect *behaviour* and therefore a bug, but maybe it is correct according to "rules of R evaluation".
2. Maybe we can at least detect the assignment (is this even possible though... halting problem and all) and print a warning that this might not be what we want.

Thanks!

**Comment by hadley** [comment]
This may technically be a bug but since it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
