### ISSUE TITLE
I have been using tidyverse and ggplot2 for some time but stopped suddenly. This is error message it brings each time I use tidyverse: ```Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  namespace ‘vctrs’ 0.3.6 is already loaded, but >= 0.3.8 is required```

### ISSUE THREAD

**Issue by isaacoluwaseyi** [tidyverse/dplyr#5911]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
You need to make sure that you are in a fresh R session (restart R/RStudio), and then install the latest version of vctrs.

Just an FYI for the future, this type of question is usually better suited to something like community.rstudio.com, since it's not a bug in dplyr, but the above advice should work (if you go on community, you'll see many similar questions with various R packages). 🙂

**Comment by isaacoluwaseyi** [comment]
Thanks I later got the solution here 
<https://stackoverflow.com/questions/67842983/how-to-make-months-of-the-year-my-x-axis-using-xyplot/67850994?noredirect=1#comment119974093_67850994>
