### ISSUE TITLE
bind_rows() Feature Suggestion: Allow coercion to character for non-matching column classes

### ISSUE THREAD

**Issue by RSchwinn** [tidyverse/dplyr#5936]
Please consider adding an argument such as **convert.conflicts.to.char = T** that would convert conflicting columns to character class.

This issue was raised previously. I am reopening it because: (1) it was originally closed under the pretense that the capability already exists, see [https://github.com/tidyverse/dplyr/issues/4281](https://github.com/tidyverse/dplyr/issues/4281). (2) More recently, it was closed citing the limitations of the function. See [https://github.com/tidyverse/dplyr/issues/5907](https://github.com/tidyverse/dplyr/issues/5907). None of the comments in either thread addresses the motivation for not providing this convenience. 

In contrast to`vctrs`, `as.character` ***does*** consider converting from numeric to character to be sensible. Would providing this optional feature make `bind_rows()` too convenient for `dplyr` users?

**Comment by lionel-** [comment]
> Would providing this optional feature make bind_rows() too convenient for dplyr users?

This sort of comment does not encourage discussion. I would refrain in the future, especially if you're interested in getting useful answers.

The point for not allowing implicit coercions of any type to character is that in many cases such combinations arise from programming errors. Characters are unstructured data. Numeric and other types are structured and they are part of a coercion hierarchy defined by a (sometimes vague) notion of substitutability. In principle, implicit coercions should only produce values that can be used interchangeably, e.g. integers to doubles.

If the intention was to convert to character, then it's better to be explicit. Especially since, in the general case, deparsing/formatting operations are many-to-one and there is no single right way to convert to characters. For example, should `as.double(1L)` be formatted as `1` or `1.0`? How many decimals for fractional numbers? Do we drop the `L` for integers?

> Please consider adding an argument such as convert.conflicts.to.char = T that would convert conflicting columns to character class.

Coercions happen all the time. It would be inconvenient to add such an argument to all user and dev facing functions and it would complicate the UI. The alternative would be a global option or preferably some other dynamic mechanism like restarts. This would have effect throughout the whole stack of packages and potentially cause bugs or unexpected results.

We'll keep your proposition in mind but you haven't provided a motivating example where explicit conversion is too inconvenient. I'm closing this issue but feel free to reply with a (preferably short and clear) motivating example.

**Comment by RSchwinn** [comment]
Hi Lionel,

Thank you for taking the time to respond so thoroughly.

In the world of financial data, thousands, if not hundreds of thousands, of entities report periodic regulatory financial data. These entities use a variety of systems, from R and SAS to MS Excel. Often, they submit hundreds of variables following specific statutory schema amounting to terabytes of data everyday.

In almost all cases, the data have the same column names and variable attributes. Sometimes, a specific entity provides data that is systematically different. For example, all fields are saved as character strings. This is easy to identify and adjust for in pre-processing.

The challenge is in data that are usually consistent, but are occasionally not. This could occur because someone opened a CSV in the post-processing stage and accidentally changed a numeric vector into a character string. For example, in the code below, the numeric data is incorrectly coded as a character string for July.

> `df_june = data.frame(date = seq.Date(as.Date("2021-06-01"), as.Date("2021-06-30"), by = "day"),
                  numeric_data = 1:30)
df_july = data.frame(date = seq.Date(as.Date("2021-07-01"), as.Date("2021-07-31"), by = "day"),
                  numeric_data = as.character(1:31))
df_august = data.frame(date = seq.Date(as.Date("2021-08-01"), as.Date("2021-08-31"), by = "day"),
                     numeric_data = 1:31)

df_combined = df_june %>%
  bind_rows(df_july) %>%
  bind_rows(df_august)`

Similar issues exist across many industries. For example, I've personally run into this issue collecting data from police departments across the state of Illinois and looking at NHL data collected from its teams.

In cases like these, when one is working with streams from many sources. An argument that, when triggered, throws a warning and converts otherwise incompatible types to character strings, according to the rules of `as.character`, could be extremely helpful. One of the big advantages of `bind_rows` over is `rbind` is that it allows tables with a different columns names to be combined. Such an argument would add further convenience.

Your reasoning that adding any arguments, such as `convert.conflicts.to.char = F/T`, could cause bugs or unexpected effects in other packages is **completely fair and persuasive**. I totally understand the hesitation and I appreciate the opportunity to make my case. 

PS: Thank you again for taking the time to respond so thoroughly. The previous replies were dismissive and flippant. So, I really appreciate getting your point of view.
