### ISSUE TITLE
Doubt about `percent_rank()`

### ISSUE THREAD

**Issue by brianmsm** [tidyverse/dplyr#5943]
As I see the code of the function: 
https://github.com/tidyverse/dplyr/blob/04454209ea069939d3335c43846c85c725547a89/R/rank.R#L104-L106
How the percentile rank is calculated is only the percentage of values that are less than the value under analysis, and not the percentage of values that are less than or equal to the value of interest, which is the definition of the percentile rank.

``` r
x <- c(1, 1, 2, 2, 5, 100)

# Current work
dplyr::percent_rank(x)
#> [1] 0.0 0.0 0.4 0.4 0.8 1.0

# Expected work
rank(x, ties.method = "max")/sum(!is.na(x))
#> [1] 0.3333333 0.3333333 0.6666667 0.6666667 0.8333333 1.0000000
```

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mine-cetinkaya-rundel** [comment]
Both definitions for percentile rank are accepted, [this Wikipedia article](https://en.wikipedia.org/wiki/Percentile_rank) suggests so, along with a formula that involves a different correction depending on whether you include the endpoint or now.

Different domains use their own definitions for this. For example, I believe the College Board uses a non-inclusive endpoint definition since you can only get up to a 99th percentile on the SATs, not 100th.

Ultimately in the limit, it doesn’t matter but for small datasets it does. (As an aside, this is why I find teaching how to make QQ plots difficult -- if you have a small number of observations to be able to draw the line by hand, then all the calculations are a bit wonky. If large enough to not matter, it’s too large to draw by hand.)

Finally, the docs for the [`quantile()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html) function define many accepted ways of calculating a quantile, which also suggests no one true way of doing this.

I would suggest, however, improving the docs on this function to explicitly state how the percent rank is calculated.

**Comment by DOH-jpd2303** [comment]
Hey! Long time listener, first time (attempted) contributor. May I try this one?

**Comment by brianmsm** [comment]
So, is the fact that the function subtracts 1 in the numerator and denominator with the intention that the percentile range always goes from 0 to 1?

https://github.com/tidyverse/dplyr/blob/04454209ea069939d3335c43846c85c725547a89/R/rank.R#L104-L106

Is there any reference or source I can use for the initial correction where you have range 0 to 1?
