### ISSUE TITLE
Version mismatch between CRAN and dplyr website

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#5948]
As of today, the Latest CRAN version appears to be 1.0.7 (https://cran.r-project.org/web/packages/dplyr/index.html) but the dplyr website says 1.0.6 on top.

<img width="515" alt="Screen Shot 2021-07-16 at 11 37 53 AM" src="https://user-images.githubusercontent.com/5965649/125973165-84353afc-8674-431f-97ce-3e51ef12090d.png">

vs.

<img width="499" alt="Screen Shot 2021-07-16 at 11 37 19 AM" src="https://user-images.githubusercontent.com/5965649/125973088-47deb19c-1d60-4054-b454-f00803581d21.png">

**Comment by batpigandme** [comment]
I wonder if it's similar to what happened with readr where it had to do with the order of operations of adding the version to DESCRIPTION and it being accepted by CRAN. I'm curious bc this definitely happens more often than we catch it, and I'd love to figure out why.
https://github.com/tidyverse/readr/issues/1222

**Comment by yutannihilation** [comment]
dplyr's case seems a bit different. It seems the version is committed to `master` and triggered the pkgdown action correctly, but the build was failed (probably because the cache is corrupted with the binaries for an older version of R?).

commit: https://github.com/tidyverse/dplyr/commit/1e0b8d68e55a8830599e088a53ca6e0aba76da8d
build: https://github.com/tidyverse/dplyr/runs/2827819813?check_suite_focus=true

**Comment by hadley** [comment]
@romainfrancois can you fix this by checking out the 1.0.7 tag locally, installing it, then running `pkgdown::deploy_to_branch()` ?

And probably worth doing (separately in a PR) `use_tidy_github_actions()` to get the latest versions of all the workflows which are less likely to have caching problems.
