### ISSUE TITLE
Getting an error : could not find function "%>%"

### ISSUE THREAD

**Issue by Kbs21** [tidyverse/dplyr#5956]
Hey, I am trying to analyse my data in R and getting an error : 

process_WM(path_to_csv) #thefunction
Error in dplyr::mutate(data, Span_Simple = max(Simple_Task$Set_Size) -  : 
  could not find function "%>%"

Can you please help me with this. I tried reinstalling the dplyr package but it doesn't help, same with the magrittr package

**Comment by romainfrancois** [comment]
This question is probably more suitable for e.g.https://community.rstudio.com however before you go ahead and resubmit there, I would advise to prepare a minimal reproducible example, preferably with the [reprex](http://reprex.tidyverse.org) package so that people who will be willing to help actually can.
