### ISSUE TITLE
`transmute()` shouldn't change order of variables

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#5967]
It seems like the `transmute()` can change the variable order again (see #4693).

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1, g = 2)
df %>% 
  group_by(g) %>% 
  transmute(x)
#> # A tibble: 1 × 2
#> # Groups:   g [1]
#>       g     x
#>   <dbl> <dbl>
#> 1     2     1
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by eutwt** [comment]
It's a relatively small change to make this work. I created a branch where preserve the order (x, g) without breaking any other tests, linked below. I would submit a pull request, except that it looks like this may have been an intentional change since Hadley deleted the test that checks for this functionality in https://github.com/tidyverse/dplyr/pull/4774.

https://github.com/eutwt/dplyr/commit/b40a94a24931a4eb118f9a5274bc00f31cfe7278

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1, g = 2) %>%                                               
  group_by(g) %>%                                                             
  transmute(x = 2)
#> # A tibble: 1 × 2
#> # Groups:   g [1]
#>       x     g
#>   <dbl> <dbl>
#> 1     2     2
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I do wonder if this behavior is intuitive in more complex cases. For example, my branch linked above has the following behavior which may be a little complicated to reason about

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(x = 1, y = 2, z = 3) %>% 
  group_by(y) %>% 
  transmute(z = 10, x = 30)
#> # A tibble: 1 × 3
#> # Groups:   y [1]
#>       z     y     x
#>   <dbl> <dbl> <dbl>
#> 1    10     2    30
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
