### ISSUE TITLE
Comments are removed with `ungroup`

### ISSUE THREAD

**Issue by allumik** [tidyverse/dplyr#5976]
When using `base` function `comment` on tibbles, then grouping and ungrouping removes attributes defined for the tibble, including the "comment" attribute.

Being a `base` function with a **specific attribute name ("comment")**, then it should be explicitly preserved when ungrouping. Because of this, it seems to me that it is a bit different case than in https://github.com/tidyverse/dplyr/issues/3558.

Reprex:
```r
library("dplyr")
data("ToothGrowth")

ToothGrowth <-
  ToothGrowth %>% as_tibble

comment(ToothGrowth) <- "This is a comment"
```
This preserves the comment ...
```r
ToothGrowth %>%
  filter(dose == 0.5) %>%
  mutate(dose = dose + 1) %>%
  comment
```
... while this does not.
```r
ToothGrowth %>%
  group_by(dose) %>%
  ungroup() %>%
  comment
```

**Comment by romainfrancois** [comment]
`ungroup.grouped_df()` calls `as_tibble.grouped_df()`: 

```r
as_tibble.grouped_df <- function(x, ...) {
  new_tibble(dplyr_vec_data(x), nrow = nrow(x))
}
```

The attribute gets lost in `dplyr_vec_data()` : 

```r
dplyr_vec_data <- function(x) {
  out <- vec_data(x)

  if (is.data.frame(x)) {
    new_data_frame(out, n = nrow(x))
  } else {
    out
  }
}
```

**Comment by DavisVaughan** [comment]
At a broader level, this is is a question of whether going from a `tbl_df -> grouped_df` or `grouped_df -> tbl_df` should retain "extra" attributes that aren't related to the tibble / grouped-df. These types of conversions happen in `as_tibble()` or `new_tibble()` / `new_grouped_df()`, making this related to https://github.com/tidyverse/tibble/pull/769

I feel somewhat strongly that `as_tibble()` and `new_tibble()` should strip all "extra" attributes that aren't explicitly related to tibbles, so the current behavior feels correct to me.

I was somewhat surprised that `group_by()` actually keeps the `comment` attribute, but this is because it goes through `new_grouped_df()` which calls `new_tibble()`, and currently that keeps extra attributes (which is what #769 is arguing should be changed). So if that gets merged then `group_by()` would automatically drop that extra attribute and we'd be consistent on both sides of the grouping.

**Comment by allumik** [comment]
I am not vehement on retaining the *comment* attribute itself, as eliminating it would make the tidyverse way of things more coherent, just as @DavisVaughan pointed out. When using `glimpse` instead of `str`, the latter does not even show any attributes currently.

Nevertheless, I would like to see some **docstring-like functionality for tibbles** or dataframes in general. While in shorter scripts and Rmd documents commenting on assignments is adequate, then in larger projects and longer experimental documents there may be a large number of different variants of the same original data. In those cases commenting on data frames has made sense for me, I could just `str` the dataframe to check what kind of comments I have assigned to it, without needing to search for occurrences in code. This retrospection becomes especially taxing after a longer hiatus from working with a codebase, or when things get "quick and dirty". Therefore, in that spirit the `comment` attribute is not just a "extra" attribute, but an already existing functionality which is currently left unused.

I am closing this issue as it does steer into `tibble` territory and more of a general discussion on eliminating technical debt. In my use case I've started keeping a named list of the `ls()` output, but I am open for suggestions for alternative ways of documenting tibbles.
