### ISSUE TITLE
Filtering != treatment of NAs is unintuitive

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/dplyr#6013]
Base `!=` seems to drop NA values.

This does not make sense, and would result in lots of people unintentionally dropping NA values.

```
library(dplyr)

df <- iris %>% 
  as_tibble() %>%
  mutate(Species = as.character(Species)) %>% 
  mutate(Species = ifelse(Species == "setosa", NA, Species)) %>% 
  distinct(Species)

df 

df %>% 
  filter(Species != "virginica") 
```

A proposed solution is that `dplyr` creates it's own `!=` that masks the base `!=` and keeps NAs

**Comment by zenggyu** [comment]
The default behavior is actually consistent with SQL standard.

**Comment by davidhodge931** [comment]
Thanks @DavisVaughan 

This seems like weird behaviour to me for `!=`, as NA is not equal to a specified (non-NA) value. 

I noticed that `filter` does not drop NAs, when `%in%` is used? This does not seem consistent?

```
library(dplyr)
df <- tibble(Species = c(NA, "versicolor", "virginica"))
filter(df, Species != "virginica")
filter(df, !Species %in% "virginica")
```

**Comment by DavisVaughan** [comment]
That is because `%in%` never returns `NA`. It works differently than `!=`

``` r
species <- c(NA, "versicolor", "virginica")

species != "virginica"
#> [1]    NA  TRUE FALSE

!(species %in% "virginica")
#> [1]  TRUE  TRUE FALSE
```

From the docs of `%in%`, it returns:

> A logical vector, indicating if a match was located for each element of x: thus the values are TRUE or FALSE and never NA.

---

> This seems like weird behaviour to me for !=, as NA is not equal to a specified (non-NA) value.

99% of the time in R, missing values _propagate_ through computations. That is the case in `!=` too. A missing value on either side of `!=` results in a missing value in the result

**Comment by eutwt** [comment]
> This seems like weird behaviour to me for `!=`, as NA is not equal to a specified (non-NA) value.

I can see why you would expect that behavior, but it's not as illogical as it may seem. There is a justification, although you may not agree: 

A value of NA is taken to mean there is some underlying value, but that value is not available / missing. It could be equal to the RHS, or it could not be equal to the RHS. We can't say the proposition `3 != NA` is false because we don't know what the value behind NA is. For that reason, `3 != NA` returns `NA` rather than `TRUE`.

**Comment by davidhodge931** [comment]
Thank you for the excellent explanations @DavisVaughan  and @eutwt 

Do you think it is possible and a good idea to add in a na.rm = TRUE argument, so that it always removes NAs whatever operator or %in% is used - and conversely keeps NAs if na.rm = FALSE?

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately this is a long-standing behaviour that matches the behaviour of base `subset()`; change it would cause widespread pain and I don't think introducing a new argument would be worth the development time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Comment by davidhodge931** [comment]
Thanks @hadley
