### ISSUE TITLE
`bind_rows` provide unexpected results when an item is `character(0)`. 

### ISSUE THREAD

**Issue by elong0527** [tidyverse/dplyr#6117]
`bind_rows` provides unexpected results when an item is `character(0)`. 

```r
bind_rows(list(name = "ae_summary", id = character(0)))
# A tibble: 0 × 2
# … with 2 variables: name <chr>, id <chr>
```

I would expect the output is 
```
# A tibble: 1 × 1
#  name      
#  <chr>     
# ae_summary
```

similar to set `id = NULL`

```
bind_rows(list(name = "ae_summary", id = NULL))
# A tibble: 1 × 1
#  name      
#  <chr>     
# ae_summary
```

**Comment by DavisVaughan** [comment]
Supplying `NULL` like that in `bind_rows()` is interpreted as "there is no input here" because `NULL` doesn't correspond to any vector type.

Supplying `character(0)` is interpreted as "here is a length 0 character column".

So you end up with a combination of a length 1 column, `name`, and a length 0 column, `id`. Tidyverse recycling rules will recycle length 1 vectors to the size of any other vector, so `name` is recycled to length 0, which is why you end up with the result you see there.

Ultimately this is all working by design, and is extremely unlikely to be changed.
