### ISSUE TITLE
NA handling in slice_min / slice_max

### ISSUE THREAD

**Issue by kmillar** [tidyverse/dplyr#6177]
`slice_min` and `slice_max` drop rows where the value in the `order_by` column is `NA`, returning fewer than the requested number of rows if `n` is large enough.

It's unclear to me whether this is a bug or just intended behavior that requires documenting.

```r
library(tibble)
library(dplyr)

x <- tibble(a = 1:3, b = c(10, NA, 12))
slice_min(x, b, n = 3)
```

**Comment by hadley** [comment]
Reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(a = 1:3, b = c(10, NA, 12))
df |> slice_min(b, n = 3)
#> # A tibble: 2 × 2
#>       a     b
#>   <int> <dbl>
#> 1     1    10
#> 2     3    12
```

<sup>Created on 2022-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I _think_ this is just a documentation issue as an `NA` value can never be the smallest or largest value.

**Comment by hadley** [comment]
Combining with #6347:

Currently we have an inconsistency depending on the `value` of `with_ties`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tribble(
  ~id, ~x,
  1, NA,
  1, NA,
  2, 1,
  2, NA,
  3, 1,
  3, 1,
  3, NA
)

df |> group_by(id) |> slice_min(x, n = 1, with_ties = TRUE)
#> # A tibble: 3 × 2
#> # Groups:   id [2]
#>      id     x
#>   <dbl> <dbl>
#> 1     2     1
#> 2     3     1
#> 3     3     1
df |> group_by(id) |> slice_min(x, n = 1, with_ties = FALSE)
#> # A tibble: 3 × 2
#> # Groups:   id [3]
#>      id     x
#>   <dbl> <dbl>
#> 1     1    NA
#> 2     2     1
#> 3     3     1
```

<sup>Created on 2022-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

What should happen when there are some `NA`s in a group? What should happen if there are only `NA`s in a group?

**Comment by hadley** [comment]
At a minimum, it feels like we also need an `na.rm` argument here.

**Comment by hadley** [comment]
If we think about these functions strictly, if there's even a single `NA` we can't actually know what row contains the actually the minimum or maximum value, and this would imply that we should always show `NAs` first, before the known values.

But that behaviour seems pretty annoying/useless, and it would be inconsistent with `arrange()` which always puts `NA` values at the end (regardless of whether you're performing an ascending or descending sort). So I think by default we should use missing values to "fill in" the number of requested rows if they're available, and otherwise provide a `na.rm` option to remove rows containing `NA`s from the output.

@eutwt @kmillar does this reasoning make sense to you?

**Comment by eutwt** [comment]
That makes sense to me. So the output of `df %>% slice_min(x, n = slice_n)` would be the same as `df %>% arrange(x) %>% slice_head(n = slice_n)` except possibly with extra rows at the end when there are ties in `x`. 

The next question is, are multiple rows with a missing value for `x` considered ties? i.e., what should this return?

```{r}
df <- tibble(x = c(1, NA, NA))

df %>% slice_min(x, n = 2)
```

**Comment by hadley** [comment]
Yeah, I think we'd consider `NA` to be tied with `NA` in that case.

I think these are the main cases:

```R
# Sufficient unique values; get n rows in output
df <- tibble(x = c(1, 2, 3, NA, NA))
df %>% slice_min(x, n = 2)

# Insufficient values; get fewer than n rows in output
df <- tibble(x = c(1))
df %>% slice_min(x, n = 2)

df <- tibble(x = c(1, NA))
df %>% slice_min(x, n = 2, na.rm = TRUE)

# Ties; get more than n rows in output
df <- tibble(x = c(1, 2, 2))
df %>% slice_min(x, n = 2)

df <- tibble(x = c(1, NA, NA))
df %>% slice_min(x, n = 2)

# Ties and insufficient values happen cancel out
df <- tibble(x = c(1, 1))
df %>% slice_min(x, n = 2)
```

**Comment by eutwt** [comment]
> ```{r}
> # Insufficient values; get fewer than n rows in output
> df <- tibble(x = c(1))
> df %>% slice_min(x, n = 2)
> 
> # Insufficient non-missing values, get NAs in output
> df <- tibble(x = c(1, NA))
> df %>% slice_min(x, n = 2, na.rm = TRUE)
> ```

These two feel at odds. In one the output is truncated when there aren't enough rows, but in the other the output is extended with `NA`s. I think it would also break the mental model a bit to have `slice_m..(na.rm = TRUE)` be the only time in `slice_...` where you get an output whose rows are not all in the input (a row of NAs). 

I was thinking that `na.rm = TRUE` would behave as-if you removed the `NA` rows, like `%>% filter(!is.na(x))`, *before* the `slice_m..()` step. Meaning, the group size when `na.rm = TRUE` would be the number of rows with non-missing values, and then the usual truncate at group-size rule applies using that size. I assume `na.rm = FALSE` would be the default, so that the only time you get an output smaller than the input despite a large-enough `n` is when you've actively chosen a special option.

**Comment by hadley** [comment]
Ooops, I think I messed that up. I meant:

```R
# Insufficient values; get fewer than n rows in output
df <- tibble(x = c(1))
df %>% slice_min(x, n = 2)

# Insufficient non-missing values, get fewer than n rows in output
df <- tibble(x = c(1, NA))
df %>% slice_min(x, n = 2, na.rm = TRUE)

# Insufficient non-missing values, get NAs in output
df <- tibble(x = c(1, NA))
df %>% slice_min(x, n = 2)
```

**Comment by eutwt** [comment]
Ha! Yes that makes sense now
