### ISSUE TITLE
`.by` argument as alternative to `group_by`

### ISSUE THREAD

**Issue by markfairbanks** [tidyverse/dplyr#6214]
_Edit:_ Updated to reflect @DavisVaughan's suggestion [here](https://github.com/tidyverse/dplyr/issues/6214#issuecomment-1073887193).

Any thoughts on implementing a `.by` arg so that functions can operate by group without returning a `grouped_df`?

Basically this:

```r
df <- tibble(x = 1:3, y = c("a", "a", "b"))

df %>%
  mutate(pct = x/sum(x), .by = y)
```

would be equivalent to this:

```r
df %>%
  group_by(y) %>%
  mutate(pct = x/sum(x)) %>%
  ungroup()
```

**Comment by DavisVaughan** [comment]
I have a feeling this would be in the verb itself if we did this, like:

```r
df %>%
  mutate(pct = x/sum(x), .groups = y)
```

**Comment by markfairbanks** [comment]
Makes sense - I'll update the original request.

**Comment by romainfrancois** [comment]
Isn't this [with_groups()](https://dplyr.tidyverse.org/reference/with_groups.html) ?

**Comment by markfairbanks** [comment]
I think a `.groups` arg would be much more intuitive to use. If implemented it would probably supersede `with_groups()`.

**Comment by zenggyu** [comment]
Perhaps also a `.by`/`.groups` argument for `filter()`? I use `filter()` after `group_by()` quite often, when I need to keep/discard entire groups.

**Comment by DavisVaughan** [comment]
In my brain, if we were to add it to one of the major verbs, then we would add it to all of them

**Comment by hadley** [comment]
We've discussed this idea a number of times (I think we'd called it `.by`) but it would be a major change to the way that dplyr works.

**Comment by DavisVaughan** [comment]
@hadley do you have any idea how it would support rowwise? Maybe it wouldn’t? It’s a little tricky because `.by` would either be `NULL` or a tidyselect expression of columns to group by, so it feels like it either wouldn’t support it or we’d have to special case some expression like `.by = .row` (which may be hard to get right in all cases, not sure)

**Comment by hadley** [comment]
@DavisVaughan yeah, we'd either need some special sentinel, or declare it's out of scope.

**Comment by moodymudskipper** [comment]
An additional `.rowwise = FALSE` arg that cannot be `TRUE` if `.by` is set would work too.

FWIW I would love the feature, I'm seeing clients use a lot of code with grouped tibbles that should be ungrouped but they don't bother because they'll regroup it before their next summarise call. In consequence the mutate and filter calls are dangerous and inefficient and the code is cluttered with messages about those groupings, that are unfortunately not acted upon. It would be so much more compact to do simple aggregations for data exploration too.

**Comment by hadley** [comment]
@moodymudskipper supporting different forms of grouping by adding extra arguments to _every_ dplyr verb is not a viable strategy.

**Comment by DavisVaughan** [comment]
I'm also not sure how to support `dplyr::group_by(.drop = FALSE)` with `.by`. Like this? Adding `.drop` everywhere feels very clunky.

```r
df %>% summarise(avg = mean(x), .by = fct, .drop = FALSE)
```

How useful is this?

**Comment by steveharoz** [comment]
I'd like to suggest using `.group_by` instead of `.by`.

1. You're not "mutating by" or "summarizing by". You're "grouping by".
2. It's consistent with the `group_by()` name, so it'd be familiar to people who already use it.
3. Some may conflate the `.by` for joins with this argument.

One change to consider with this approach is that it takes the sequential calling style that's pretty central to tidyverse style and makes it nested. Maybe coding style can alleviate that issue though?

```r
data %>%
    group_by(var1, var2, subject_id) %>%
    summarize(mu = mean(x), sigma = sd(x)) %>%
    ungroup()
```

versus

```r
data %>%
    summarize(
        .group_by = c(var1, var2, subject_id),
        mu = mean(x), sigma = sd(x)
    )
```

**Comment by steveharoz** [comment]
Also, what about autocomplete in RStudio? Will it be able to autocomplete column names for the `.by` parameter like it does for `group_by()`

Autocomplete is pretty critical for those of us who can never remember the names of columns or how to spell them :)

**Comment by DavisVaughan** [comment]
I'm not sure what is so bad about

```r
data %>%
  summarize(
    mu = mean(x), 
    sigma = sd(x),
    .group_by = c(var1, var2, subject_id)
  )
```

I feel like it nicely encapsulates the full operation, and doesn't look overly nested to me. You aren't adding any more nesting than what was already there from the actual summary expressions

**Comment by steveharoz** [comment]
@DavisVaughan  I agree, but even though I've been using R for 6+ years, I still register `c( )` as a function call. That's why I think of it as nested. But that's probably tangential to this threat ;)

**Comment by DavisVaughan** [comment]
Oh I didn't realize you meant that `c()` was the extra level of nesting. Yea that looks "flat" to me, not as another layer of nesting.

Also FWIW the IDE will still autocomplete variable names if you pipe into it with this setup

<img width="812" alt="Screen Shot 2022-07-15 at 10 34 12 AM" src="https://user-images.githubusercontent.com/19150088/179245430-bf950ff6-eba2-4676-9741-4f0ab4f4f5a1.png">
