### ISSUE TITLE
should arrange() show a warning on empty or constant criteria?

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/dplyr#6241]
Should `arrange()` show a warning on empty or constant criteria?
It would warn over some common errors.

Arrange with no arguments:
```r
df1 %>%
  arrange()
```

Trying to arrange by column name:
```r
df1 %>%
  arrange("col1")
df1 %>%
  arrange(col1)
```

Trying to arrange by column position:
```r
df1 %>%
  arrange(1:3)
df1 %>%
  arrange(across(1:3))
```

It would be similar to the warning when `filter` contains an asignment, instead of a condition:
```r
df1 %>%
  filter(col1 = condition)
df1 %>%
  filter(col1 == condition)
```

**Comment by hadley** [comment]
It's typically very tricky to get the logic right for these sorts of hints because we don't want to accidentally send people down the wrong path. So we reserve it for the most common of errors, and unfortunately I don't think this quite rises to that level. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
