### ISSUE TITLE
case_when always tests the commands even the condition don't meet

### ISSUE THREAD

**Issue by seahearman** [tidyverse/dplyr#6250]
when I apply the case_when function, it always test-runs the command even the condition doesn't meet.

```r
df <- data.frame(x=c(1,2,3))
df <- df %>% mutate(y2 = case_when("y1" %in% colnames(df) ~ y1-1))

```

**Comment by andrewbaxter439** [comment]
This seems to be same problem highlighted in #6158 and not possible to fix?

**Comment by DavisVaughan** [comment]
Yea, same rationale as https://github.com/tidyverse/dplyr/issues/6158#issuecomment-1100658352

Plus I'm not sure we _want_ to resolve it. We need to enforce that all of the values on the right hand side of the `~` have compatible types, and the only way to do that is to evaluate them all. That also tells us what the output type should be. The only way to be type stable is to evaluate them all, otherwise something like this could occur where you get different return types based on the conditions, which would be pretty bad in my opinion

```r
library(dplyr)

# This might return 1
x <- TRUE
y <- FALSE
case_when(x ~ 1, y ~ "x")

# This might return "x"
x <- FALSE
y <- TRUE
case_when(x ~ 1, y ~ "x")
```
