### ISSUE TITLE
bind_rows .id column should be factor, not character

### ISSUE THREAD

**Issue by kcarnold** [tidyverse/dplyr#6274]
I sometimes want to group a `bind_rows` result by the `.id` column. But since the column is a `character`, the default grouping ignores the order that I gave the data in, sorting it instead. Silly toy example:

``` r
library(dplyr)
bind_rows(
  c = mtcars,
  a = mtcars,
  .id = 'dataset'
) |> group_by(dataset) |> count()
#> # A tibble: 2 × 2
#> # Groups:   dataset [2]
#>   dataset     n
#>   <chr>   <int>
#> 1 a          32
#> 2 c          32
```

<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'd expect the order to be `c` then `a` in the summary table. I can work around this by, say, `group_by(dataset = as_factor(dataset))`, but I'm wondering why factor isn't default.

**Comment by DavisVaughan** [comment]
This mainly has to do with the fact that `group_by() |> summarize()` and `group_by() |> count()` sort the groups internally.

If the groups weren't sorted at all, and instead were just returned in "order of appearance", then you'd get what you expected out-of-the-box even with the character column. We have discussed this as a potential change to `group_by()` here https://github.com/tidyverse/dplyr/issues/5664#issuecomment-907232443, and it has some nice benefits.

Since this will likely eventually get solved a different way, and because many people probably rely on the ID column to be a character vector, I think we are unlikely to change it to a factor, so I am going to close this issue, but thanks for the report!

**Comment by kcarnold** [comment]
That sounds like a wonderful solution.

(There's a temptation to reply to that thread with a laundry list of breaking changes! I'll resist the urge. But there are definitely some names that could be reconsidered in such an 'edition'.)
