### ISSUE TITLE
Consider how folks will want to program with `join_by()`

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6469]
i.e. it's neither tidy-select not data-masking

**Comment by hadley** [comment]
But it's probably closer to tidy-select so `join_by("x" == "y")` should be equivalent to `join_by(x == y)`

**Comment by hadley** [comment]
And embracing needs to work:


``` r
my_join <- function(x) dplyr::join_by({{x}} == y)
my_join(z)
#> Error in `dplyr::join_by()`:
#> ! `join_by()` expressions cannot contain computed columns, and can only
#>   reference columns by name or by explicitly specifying a side, like `x$col` or
#>   `y$col`.
#> ℹ Expression 1 contains `^z`.

#> Backtrace:
#>     ▆
#>  1. └─global my_join(z)
#>  2.   └─dplyr::join_by(...)
#>  3.     └─dplyr:::parse_join_by_expr(exprs[[i]], i, error_call = error_call)
#>  4.       └─dplyr:::parse_join_by_binary(expr, i, error_call)
#>  5.         └─dplyr:::parse_join_by_name(lhs, i, default_side = "x", error_call = error_call)
#>  6.           └─rlang::abort(message, call = error_call)
```

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I think the issue is that `join_by()` uses `enexprs()`, and I am somewhat confident that is the correct way to do things.

However, we have:
- `{{ }}` as a substitute for `!!enquo()` when we pass on to `enquos()`
- Nothing as a substitute for `!!enexpr()` when we pass on to `enexprs()`

It would be cool if rlang had some `!!enexpr()` shortcut. 

I would love to avoid trying to teach `join_by()` about how to handle quosures nested within the expression, because I feel like that is a path towards pain and weird edge cases

``` r
library(rlang)

simple_join_by <- function(...) enexprs(..., .named = FALSE)
my_join <- function(x) simple_join_by({{x}} == y)
res <- my_join(z)

# This has a quosure in it from `{{x}}` being equivalent to `!!enquo(x)`.
# `join_by()` doesn't know what to do with those.
res
#> [[1]]
#> (~z) == y
res[[1]][[2]]
#> <quosure>
#> expr: ^z
#> env:  global

# Remember when `{{ }}` used to be `!!enquo()` when we passed on to `enquos()`?
# Apply the same principle...but for `enexprs()`
my_join <- function(x) dplyr::join_by(!!enexpr(x) == y)
my_join(z)
#> Join By:
#> - z == y
```

<sup>Created on 2022-09-29 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
> tidy-select so join_by("x" == "y") should be equivalent to join_by(x == y)

That one does work

**Comment by hadley** [comment]
Isn't `quo_squash()` going to be safe for `join_by()` since `join_by()` doesn't evaluate anything? It's not like you can write `a <- 10; join_by(x == y + a)`.

**Comment by hadley** [comment]
Although maybe we'd want this to work too?

```R
x_var <- "x"
dplyr::join_by(x[[x_var]] == y)
```

**Comment by lionel-** [comment]
After switching to `quo_squash()`, maybe use `enquos()` in your implementations too? Even if it is correct in this case, it's probably better to avoid encouraging usage of `enexprs()`.
