### ISSUE TITLE
filter and tidyevaluation behaves weirdly

### ISSUE THREAD

**Issue by yuliaUU** [tidyverse/dplyr#6487]
I am a bit confused with teh following outputs of filter function and {{}} syntax
to reproduce the issue:

```
library(gapminder)
library(tidyverse)
```

1. case 1: this code should not run as quoted column name does not work with {{}}:
```

# Yes here we are passing the quoted column name YES FAIL
filter_gap <- function(col, val) {
  filter(gapminder, {{col}} == val)
}
filter_gap("country", "Canada")
```

2. case 2: making variable <-"country"
 Here too we are passing the quoted column name , but runs I expect not to run
```
filter_gap <- function(col, val) {
  filter(gapminder, {{col}} == val)
}
country <- "country"
filter_gap(country, "Canada")
```
and outputs   A tibble: 12 × 6

but if I replace `country <- "country"` with `xx <- "country"`
```
filter_gap <- function(col, val) {
+     filter(gapminder, {{col}} == val)
+ }
> xx <- "country"
> filter_gap(xx, "Canada")
```
this outputs empty datset

3. case 3: print() inside function

this function works as expected:
```
filter_gap <- function(col, val) {

  filter(gapminder, {{col}} == val)
}
filter_gap(country, "Canada")
```

but if I add print(col) inside:
```
filter_gap <- function(col, val) {
  print(col)
  filter(gapminder, {{col}} == val)
}
filter_gap(country, "Canada")
```
this no longer works, and I have no idea why

**Comment by hadley** [comment]
I think you can understand all these by thinking what happens without tidyeval:

1. `filter(gapminder, "country" == "Canada")` is legitimate, if not very useful code
2. `country <- "country"; filter(gapminder, country == "Canada")` works because dplyr always prefers variables in the data to variables in the environment.
3. Just typing `print(country)` at console doesn't work either.

**Comment by yuliaUU** [comment]
regarding3)  my confusion is inprint() does work:and it prints the name of the column
![image](https://user-images.githubusercontent.com/54612866/193058159-19b86ff3-5bb0-4baf-8918-abb96db6a80e.png)

**Comment by hadley** [comment]
Here's a proper reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

filter_gap <- function(col, val) {
  print(col)
  filter(gapminder::gapminder, {{col}} == val)
}
filter_gap(country, "Canada")
#> Error in print(col): object 'country' not found
```

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If you have `country` lying from earlier it will "work":

``` r
library(dplyr, warn.conflicts = FALSE)

country <- "country"
filter_gap <- function(col, val) {
  print(col)
  filter(gapminder::gapminder, {{col}} == val)
}
filter_gap(country, "Canada")
#> [1] "country"
#> # A tibble: 0 × 6
#> # … with 6 variables: country <fct>, continent <fct>, year <int>,
#> #   lifeExp <dbl>, pop <int>, gdpPercap <dbl>
```

<sup>Created on 2022-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The problem here is because you've forced the evaluation of `col`, you've lost the information that tidyevaluation would use to do variable substitution, so it just inserts the value of `col`, "country".

**Comment by yuliaUU** [comment]
ok! I see! thank you for the explanation- just a small follow up why if I type `print(col)` outside of function - it is not forced and it just gives error, while inside the function the behavior changes

**Comment by yuliaUU** [comment]
oh! now i see! thank you for the explanations!
