### ISSUE TITLE
Error in `vctrs::vec_as_subscript()`: ! `...` must be empty.

### ISSUE THREAD

**Issue by Theresaliu** [tidyverse/dplyr#6516]
When I tried to source my code file,I encountered this proplem

```r
library(recipes)
library(insurance)
library(tidyverse)
library(deeptriangle)
library(keras)
library(tensorflow)
use_condaenv("r-reticulate")

source("analysis/data-prep.R")
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by DavisVaughan** [comment]
As there has been no follow up, I'm going to close this. Feel free to open another issue with a full reprex if you are able to reproduce the problem and still have a question. Thanks!

**Comment by pitb1458777** [comment]
Hello, I'm having the same issue with the dplyr rename function as the user above. For my example, this is from the Help page for ?rename()

```
iris <- as_tibble(iris) # so it prints a little nicer
rename(iris, petal_length = Petal.Length)
```
Which gives the following error message:
```
> rename(iris, petal_length = Petal.Length)
Error in `vctrs::vec_as_subscript()`:
! `...` must be empty.
x Problematic argument:
* call = call
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by DavisVaughan** [comment]
You likely have some incompatible package versions somehow. I would reinstall dplyr and vctrs and then restart R and try again

**Comment by pitb1458777** [comment]
Thank you for your help, Davis; that did the trick. I messed up in one regard, though. I started a new session and had one r file that was not saved, and it's not coming up when I reload the project. Do you have any suggestions?
