### ISSUE TITLE
Grouped `across()` doesn't give good error with bad input

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#6534]
``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(g = 1, x = 1, y = 2, z = 3)

df |> summarise(across(everything(), median()))
#> Error in `summarise()`:
#> ℹ In argument: `..1 = across(everything(), median())`.
#> Caused by error in `is.factor()`:
#> ! argument "x" is missing, with no default

df |> group_by(g) |> summarise(across(everything(), median()))
#> Error in vapply(.x, .f, .mold, ..., USE.NAMES = FALSE): values must be length 1,
#>  but FUN(X[[1]]) result is length 0
```

<sup>Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
The problem seems to occur because it occurs during the across splatting, i.e. in group "0".

**Comment by DavisVaughan** [comment]
Yea the problem is likely that we are trying to add group context to the error message, but there isn't any to add because we haven't set up the group information yet.

Determining whether or not to attempt to add group context to the error message has been a little painful so far, so I feel like we should rethink how it works a little bit. If we are "before" the groups have been set up, we have to specially register the error class as one that doesn't need group context, which seems hard to unconditionally get right (as seen in your example)
https://github.com/tidyverse/dplyr/blob/50c58dd9980b9216c60a1de4da521ee5aa16e2de/R/conditions.R#L63-L72

Maybe we can explicitly set something like `the$needs_group_context` to `TRUE` as soon as we set up the groups, but otherwise default it to `FALSE`, which would greatly simplify some things.

For example, this is the reason `pick()` has to subclass tidyselect errors
https://github.com/tidyverse/dplyr/blob/50c58dd9980b9216c60a1de4da521ee5aa16e2de/R/pick.R#L167-L182

And it is why we have to do this crazy catch-subclass-rethrow pattern with deprecation conditions
https://github.com/tidyverse/dplyr/blob/50c58dd9980b9216c60a1de4da521ee5aa16e2de/R/across.R#L778-L794

**Comment by DavisVaughan** [comment]
@lionel- what do you think about that?

**Comment by lionel-** [comment]
Using a boolean flag in the condition with `%||% FALSE` default instead subclassing seems like a good idea.

**Comment by hadley** [comment]
Are you sure we should just have someway to let the mask know that we've started/ended grouping? Then we could have:

```R
cnd_data <- function(cnd, ctxt, mask_type, call) {
  if (has_group_content()) {
    group_data <- cur_group_data(mask_type)
  } else {
    group_data <- NULL
  }
  ...
```

**Comment by DavisVaughan** [comment]
I think that is basically what im suggesting
