### ISSUE TITLE
Two suggestions for dplyr 1.1.0 .by with mutate

### ISSUE THREAD

**Issue by donboyd5** [tidyverse/dplyr#6581]
.by is a great facility with mutate

Here are two things that would make it even better from my perspective:

- allow creation of an on-the-fly grouping variable -- for example

`df |> mutate(b=a / max(a), .by=stringr::str_starts(name, "south"))`

- alternatively, if a grouping variable can't be created on the fly, it would be nice to be able to create it in the same mutate statement, rather than in separate statements, for example:

`df |> mutate(southornot=stringr::str_starts(name, "south"), b=a / max(a), .by=southornot)`

rather than the following, which appears to be required now:

`df |> mutate(southornot=stringr::str_starts(name, "south")) |> mutate(b=a / max(a), .by=southornot)`

Thanks for considering it, and thanks for the big leap forward in dplyr.

**Comment by DavisVaughan** [comment]
I agree that on-the-fly grouping is a somewhat interesting idea, but for this first release I think we _really_ want to keep `.by` as "pure" tidyselect syntax, rather than trying to mix in some data-masking semantics too, which really muddies the water as to how things would work.

Regarding

```r
df |> mutate(southornot=stringr::str_starts(name, "south"), b=a / max(a), .by=southornot)
```

I don't think that could work either, because `.by` naturally has to be applied _before_ we look at any of the expressions in `...`.
