### ISSUE TITLE
Output for mutate function does not create a new column name as expected 

### ISSUE THREAD

**Issue by moriarais** [tidyverse/dplyr#6592]
I am using mutate function to add a new column in the data. I used 2 variations but both created the column with the wrong name "Domestic_boxoffice" instead of "total_boxoffice ".

See the implementation below:

Option 1: starwars <- mutate(starwars, total_boxoffice = Domestic_boxoffice + Worldwide_boxoffice, .after=Worldwide_boxoffice)

Option 2: starwars %>% mutate(total_boxoffice = Domestic_boxoffice + Worldwide_boxoffice)

![Screenshot_20221209_224010_Chrome](https://user-images.githubusercontent.com/15028409/206793462-b9a1c770-f910-472f-bc08-eb22c87646ce.jpg)

Any idea why this could happen? In the screenshot below you can see that the first print displays the data structure and the second print after the addition of the column

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
