### ISSUE TITLE
add recode unquote splicing example to case_match

### ISSUE THREAD

**Issue by nstjhp** [tidyverse/dplyr#6623]
I see `case_match` is going to supersede `recode` and it looks to have some useful aspects e.g. the grouped LHS, but if I understand the examples correctly because of the 2-sided formulae it might not support unquote splicing (at least of a character vector) which for us is a major shortcut when using `recode`. 

It would be great if the example below from `?recode` where a named character vector is used for unquote splicing with `!!!` is also  included in the `case_match` examples. Assuming this isn't possible, can an example please be added to `case_match` to show how to recreate a similar pattern (e.g. perhaps we have to create a list of expressions or formulae with `paste` or `reformulate`, and then use rlang trickery like `parse_exprs`).
``` r
library(dplyr)
char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)
char_vec
#>  [1] "a" "b" "b" "c" "c" "a" "b" "c" "b" "a"
# Use a named character vector for unquote splicing with !!!
level_key <- c(a = "apple", b = "banana", c = "carrot")
recode(char_vec, !!!level_key)
#>  [1] "apple"  "banana" "banana" "carrot" "carrot" "apple"  "banana" "carrot"
#>  [9] "banana" "apple"
```

<sup>Created on 2022-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
For super simple recodes like this one, you might also consider just using `[` indexing by name

``` r
set.seed(123)

char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)
char_vec
#>  [1] "c" "c" "c" "b" "c" "b" "b" "b" "c" "a"

level_key <- c(a = "apple", b = "banana", c = "carrot")

unname(level_key[char_vec])
#>  [1] "carrot" "carrot" "carrot" "banana" "carrot" "banana" "banana" "banana"
#>  [9] "carrot" "apple"
```

Otherwise, you can build the formulas using `map2()` and `rlang::new_formula()` and then splice them in.

``` r
library(dplyr)

set.seed(123)

char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)
char_vec
#>  [1] "c" "c" "c" "b" "c" "b" "b" "b" "c" "a"

level_key <- c(a = "apple", b = "banana", c = "carrot")

cases <- purrr::map2(
  names(level_key),
  unname(level_key),
  rlang::new_formula
)
cases
#> [[1]]
#> "a" ~ "apple"
#> <environment: 0x7fbc1ada2828>
#> 
#> [[2]]
#> "b" ~ "banana"
#> <environment: 0x7fbc1ada2828>
#> 
#> [[3]]
#> "c" ~ "carrot"
#> <environment: 0x7fbc1ada2828>

case_match(char_vec, !!!cases)
#>  [1] "carrot" "carrot" "carrot" "banana" "carrot" "banana" "banana" "banana"
#>  [9] "carrot" "apple"
```

I actually hesitate to add examples of this right now though, because for "programmatic" uses of `case_when/match()` like this you might be better off with the more programmer friendly variants of `vec_case_when()` and `vec_case_match()` that will eventually be part of vctrs. These are internal to dplyr right now, but will be exported from vctrs later on. That looks like this:

``` r
library(dplyr)

set.seed(123)

char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)
char_vec
#>  [1] "c" "c" "c" "b" "c" "b" "b" "b" "c" "a"

level_key <- c(a = "apple", b = "banana", c = "carrot")

needles <- char_vec
haystacks <- as.list(names(level_key))
values <- as.list(unname(level_key))

dplyr:::vec_case_match(needles, haystacks, values)
#>  [1] "carrot" "carrot" "carrot" "banana" "carrot" "banana" "banana" "banana"
#>  [9] "carrot" "apple"
```

Once these are implemented I planned to come back and add dplyr examples that show how to use them for programmatic use cases
