### ISSUE TITLE
`distinct()` Grouping example is unclear and incomplete 

### ISSUE THREAD

**Issue by asadow** [tidyverse/dplyr#6654]
The #Grouping example [@](https://dplyr.tidyverse.org/reference/distinct.html) does not make it clear how groups affect `distinct()`. Grouping variables are only included if a variable is specified inside `distinct()`:

``` r
library(tidyverse)
df <- tibble(
  g = c(1, 1, 3),
  x = c(1, 1, 1),
  y = c(3, 1, 1)
) %>% 
  group_by(g)
## Includes g in variables used by distinct()
df %>% distinct(x)
#> # A tibble: 2 × 2
#> # Groups:   g [2]
#>       g     x
#>   <dbl> <dbl>
#> 1     1     1
#> 2     3     1
## Does not include g in variables used by distinct()
df %>% distinct()
#> # A tibble: 3 × 3
#> # Groups:   g [2]
#>       g     x     y
#>   <dbl> <dbl> <dbl>
#> 1     1     1     3
#> 2     1     1     1
#> 3     3     1     1
```

<sup>Created on 2023-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I created this issue as I expected `distinct()` to include grouping variables whether or not arguments are specified inside `distinct()`.

**Comment by hadley** [comment]
Link to dev docs: https://dplyr.tidyverse.org/dev/reference/distinct.html

I don't understand your confusion because in your examples it seems like all the outputs do containing the grouping variables?

**Comment by asadow** [comment]
> 

Based on the documentation, I would expect `df %>% distinct()` to behave as `df %>% distinct(g)`.

Essentially the confusion is that the following is written in the docs:

# Grouping -------------------------------------------------
# The same behaviour applies for grouped data frames,
# except that the grouping variables are always included

By "included" I presumed "included in the variables used for finding distinct rows". But from your comment I think you mean "included in the outputted data".

**Comment by DavisVaughan** [comment]
@hadley 

`df` is grouped by `g` so I think I'd expect `g` to be "distinct-ed" but `1` still appears twice

```r
df %>% distinct()
#> # A tibble: 3 × 3
#> # Groups:   g [2]
#>       g     x     y
#>   <dbl> <dbl> <dbl>
#> 1     1     1     3
#> 2     1     1     1
#> 3     3     1     1
```

**Comment by DavisVaughan** [comment]
I think it has to do with this early exit
https://github.com/tidyverse/dplyr/blob/5811f1010076946bd2131b46dd3710c27401ef78/R/distinct.R#L81

**Comment by DavisVaughan** [comment]
I think the problem is mostly that `distinct()` with no args chooses to "retain all variables" (i.e. that special early exit). I feel like that is slightly inconsistent as an edge case.

`distinct()` with no args is theoretically equivalent to doing `vec_unique_loc()` on a data frame with 0 cols but >=0 rows. This always returns only the 1st row as the "unique location".

```r
> vctrs::vec_unique_loc(mtcars[,0])
[1] 1
```

This is what would happen if we removed that early exit and would also fix the inconsistency it causes in this issue

**Comment by DavisVaughan** [comment]
Oh, I think I misunderstood how `distinct()` works when not given any inputs. It does the opposite of what I was thinking. Rather than computing uniqueness using 0 columns, it computes uniqueness using _all_ of the columns.

So when you do `gdf %>% distinct()` it is _technically_ doing the right thing (as documented) because it computes uniqueness using _all_ of the columns (the group cols plus non-group cols).

It is just confusing that:

```r
# Uses group cols and `x` and `y`
gdf %>% distinct(x, y)

# Uses group cols and `x`
gdf %>% distinct(x)

# Uses group cols? Nope. Uses group cols AND EVERYTHING ELSE.
gdf %>% distinct()
```

But unfortunately I don't think there is any way to avoid that weirdness.

This will be less confusing if we encourage `.by` and get away from grouped-dfs some.

**Comment by DavisVaughan** [comment]
Turns out the current behavior was explicitly requested here:
https://github.com/tidyverse/dplyr/issues/2476

I think I can justify it:
- `distinct(df)` with no `...` should compute uniqueness using all available variables
- `distinct(gdf, ...)` computes the uniqueness of `...` _within_ the groups of `gdf`

So when you combine the two as `distinct(gdf)`, you get `...` using all variables except the group variables, and the uniqueness of those is computed _within_ the groups of `gdf`, which altogether becomes identical to just supplying all of the variables of `gdf` to `distinct()` to begin with.

I'm now voting for no changes. I think changing behavior here is probably too risky, and would just make things even less consistent.

**Comment by asadow** [comment]
> @hadley
> 
> `df` is grouped by `g` so I think I'd expect `g` to be "distinct-ed" but `1` still appears twice
> 
> ```r
> df %>% distinct()
> #> # A tibble: 3 × 3
> #> # Groups:   g [2]
> #>       g     x     y
> #>   <dbl> <dbl> <dbl>
> #> 1     1     1     3
> #> 2     1     1     1
> #> 3     3     1     1
> ```

Since we both had this intuition, it's worth reworking the documentation, specifically:

> Grouping -------------------------------------------------
The same behaviour applies for grouped data frames,
except that the grouping variables are always included
