### ISSUE TITLE
`mutate()` fails on class `c("ggeffects", "data.frame")`

### ISSUE THREAD

**Issue by mattansb** [tidyverse/dplyr#6691]
(This use to work)

`ggeffects` data frames (from @strengejacke 's `{ggeffects}` package) can no longer be used within `mutate()`:

``` r
library(ggeffects)
library(dplyr, warn.conflicts = FALSE)

m <- lm(mpg ~ factor(cyl), mtcars)

gge <- ggpredict(m, "cyl")

class(gge)
#> [1] "ggeffects"  "data.frame"

as.data.frame(gge)
#>   x predicted std.error conf.low conf.high group
#> 1 4  26.66364 0.9718008 24.75894  28.56833     1
#> 2 6  19.74286 1.2182168 17.35520  22.13052     1
#> 3 8  15.10000 0.8614094 13.41167  16.78833     1

mutate(gge) # very minimal example
#> Error in colnames(x)[1] <- focal_term: replacement has length zero
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
This problem is unrelated to dplyr. In `mutate()` we use a pattern of `data[loc]` (i.e. 1 dimensional column selection with `[`) and since ggeffects inherits from base R data frames it inherits the `[.data.frame` method, which drops attributes.

The issue can be reproduced without dplyr at all:

``` r
library(ggeffects)

m <- lm(mpg ~ factor(cyl), mtcars)

gge <- ggpredict(m, "cyl")

class(gge)
#> [1] "ggeffects"  "data.frame"

names(gge)
#> [1] "x"         "predicted" "std.error" "conf.low"  "conf.high" "group"

gge[c("x", "predicted")]
#> Error in colnames(x)[1] <- focal_term: replacement has length zero
```

<sup>Created on 2023-02-07 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Thanks Davis!
