### ISSUE TITLE
if_else throws `false` must be a vector, not `NULL`. error for dplyr 1.1.0

### ISSUE THREAD

**Issue by chrarnold** [tidyverse/dplyr#6728]
For dplyr v1.1.0, code that worked before now breaks:

```r
library(dplyr)
basename = NULL
dplyr::if_else(is.null(basename), "plot", basename)
# Error in `dplyr::if_else()`:
# ! `false` must be a vector, not `NULL`.
```
The message doesnt make sense to me here because even though `basename` is `NULL`, it never goes into the `false` block. The idea is here: Return a string with a folder name. If the user didnt set one (`basename = NULL`), return a default (`"plot"`), otherwise return whatever the user put there.

Is this a deliberate (breaking) change and if so, what's the rationale here?

**Comment by DavisVaughan** [comment]
The `true` and `false` arguments are always evaluated, regardless of whether their values are seen in the result.

Both of them are used to compute the common type of the result, for example:

``` r
library(dplyr)

# Only the `true` block is used in the result, but we look at `true` and `false` to figure
# out that the common type is double
typeof(if_else(TRUE, 1L, 2))
#> [1] "double"
```

This means that both `true` and `false` must be compatible vector types, so that `if_else()` can be guaranteed to be type stable, and `NULL` isn't a vector type.

Your example is probably better as a simple if statement:

```r
if (is.null(basename)) {
  # do something with "plot"
}
```

**Comment by chrarnold** [comment]
Well, for sure I can transform it to a proper if... else statement or, what I do now, just base R `ifelse` for it (which works and is concise), but my main point is that this behavior actually changed in dplyr 1.1.0 and I did not find this change documented (or missed it) and it may be something others also relied on (in a package context, as here, for exampel)
