### ISSUE TITLE
Corner cases with `.data` and `.env`

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#6750]
_Edit: updated the issue since I oversaw first that `.data` was also the first arg name._

These are artificial cases but since the `.data` and `.env` pronouns are used essentially for robustness and eliminating ambiguity I think maybe those might be dealt with and documented so we can count on this robustness a bit more. Moreover `.data` is not a completely absurd name for a data frame column.

``` r
library(dplyr, w=F)

# fails because of `.data` arg as it should, would fail also if there was a `.data` column
band_members %>% mutate(.data = 1)
#> Error in UseMethod("mutate"): no applicable method for 'mutate' applied to an object of class "c('double', 'numeric')"

# succeeds, but should it ?
band_members %>% mutate(.env = 1)
#> # A tibble: 3 × 3
#>   name  band     .env
#>   <chr> <chr>   <dbl>
#> 1 Mick  Stones      1
#> 2 John  Beatles     1
#> 3 Paul  Beatles     1

# fails because looks in global env
band_members %>% mutate(.env = band_members, foo = .env$band)
#> Error in `mutate()`:
#> ℹ In argument: `foo = .env$band`.
#> Caused by error in `eval_bare()`:
#> ! object 'band' not found

# succeeds, looks in data
band_members %>% mutate(.env = band_members, foo = .env)
#> # A tibble: 3 × 4
#>   name  band    .env$name $band   foo$name $band  
#>   <chr> <chr>   <chr>     <chr>   <chr>    <chr>  
#> 1 Mick  Stones  Mick      Stones  Mick     Stones 
#> 2 John  Beatles John      Beatles John     Beatles
#> 3 Paul  Beatles Paul      Beatles Paul     Beatles
```

<sup>Created on 2023-02-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I believe the least surprising behaviour is to expect that `.env` and `.data` always refer to pronouns.

Since `mutate()` is already not accepting any data frame (refusing duplicate or empty names at least), it might refuse to create a column named ".data" or ".env", and maybe even refuse an input that would contain one, basically considering those corrupted.

(out of scope for dplyr but maybe these might even be refused in any function that uses `.name_repair` unless it's set to `"minimal"`)

**Comment by DavisVaughan** [comment]
It is mildly surprising that these give different results, but this is because we have a special path for _symbols_ such as a bare reference to `.env` that is different from _calls_ like `(.env)`. The symbol path doesn't use an rlang data mask so it doesn't know about the rlang `.env` pronoun and instead finds it in the data (that's one of the points of the symbol path, it quickly finds columns in the data without having to do a full evaluation).

``` r
library(dplyr, warn.conflicts = FALSE)

band_members %>% mutate(.env = band_members, foo = .env)
#> # A tibble: 3 × 4
#>   name  band    .env$name $band   foo$name $band  
#>   <chr> <chr>   <chr>     <chr>   <chr>    <chr>  
#> 1 Mick  Stones  Mick      Stones  Mick     Stones 
#> 2 John  Beatles John      Beatles John     Beatles
#> 3 Paul  Beatles Paul      Beatles Paul     Beatles

band_members %>% mutate(.env = band_members, foo = (.env))
#> Error in `mutate()`:
#> ℹ In argument: `foo = (.env)`.
#> Caused by error:
#> ! `foo` must be a vector, not a <rlang_ctxt_pronoun> object.
```

This ^ example explains why `.env$band` errors (it is a call and goes through the data mask, so it finds the `.env` pronoun) but the `foo = .env` example works (it is a symbol).

If we unconditionally evaluated in an rlang data mask then you wouldn't ever be able to reference an `.env` column in a `mutate()` expression:

``` r
library(rlang)

eval_tidy(expr(.en), data = list(.en = 1))
#> [1] 1

eval_tidy(expr(.env), data = list(.env = 1))
#> <environment: 0x7fbfb3ba40a8>
#> attr(,"class")
#> [1] "rlang_ctxt_pronoun"
```

but I don't think that is viable for us for performance reasons.

I also don't think it is worth the effort to try and disallow particular column names.

So I am tempted to close this and say that this is mainly a technical corner case that isn't important enough to warrant further action.

@lionel- do you agree with my analysis?

**Comment by lionel-** [comment]
I agree, it doesn't seem worth it to worry about these edge cases.
