### ISSUE TITLE
Obscure CRAN error

### ISSUE THREAD

**Issue by dieghernan** [tidyverse/dplyr#6793]
Cross posting from vctrs, seems that something was broken after the newest vctrs release:

https://github.com/r-lib/vctrs/issues/1821

It is only in [r-devel-linux-x86_64-debian-gcc](https://cran.r-project.org/web/checks/check_flavors.html#r-devel-linux-x86_64-debian-gcc):

```r
> as_tibble(r, xy = TRUE)
    Error in vectbl_assign(x[[j]], cells[[j]], value) : 
     DLL requires the use of native symbols
    Calls: as_tibble ... tbl_subassign_matrix -> withCallingHandlers -> vectbl_assign
    Execution halted
```

The error happens when I use dplyr, but the root cause may be in vctrs as per the error message

**Comment by lionel-** [comment]
I don't think this is due to vctrs or dplyr, but to this change in r-devel: https://github.com/r-devel/r-svn/commit/ae6f1becea792745847c227f2e92ebca2999f875

It's currently guarded behind an envvar and it looks like they turned it on on CRAN to assess the breakage fallout. Looks like some package in the stack sets `R_forceSymbols(dll, TRUE)` but that isn't vctrs.

But really I don't understand the r-devel change. It would make more sense to me if they checked whether `R_forceSymbols` was set to `FALSE`, not to `TRUE`. I'd suggest to just wait and see what happens next on r-devel.
