### ISSUE TITLE
Does join_by() support data masking?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dplyr#6807]
I am wondering if the link `` <[`data-masking`][rlang::args_data_masking]> `` should be added to `?join_by`.

That would help cases like mine where I'm using this anchor to build static analysis tools that know "there be ~dragons~ NSE here" inside calls that support NSE-only symbols (as do `select()`, `group_by()`, etc.).

But I also understand the data masking supported by `join_by()` is not as fully general as in other cases (e.g. the nod to pre-computing), so I am hesitating to just drop the link in and file a PR as it's not strictly an inconsistency.

If `join_by()` is an exception case (supports some NSE, but doesn't use the `args_data_masking` link), that's also fine.

**Comment by DavisVaughan** [comment]
It is not data-masking, nor is it really tidy-select.

It is a little closer to tidy-select because `join_by("x" == "y")` is equivalent to `join_by(x == y)` (whereas a data-masking version would interpret that as a literal character `"x"` rather than a column named `x`)

But the fact that `==` is allowed at all means it isn't tidy-select either, it really is its own special DSL.

There is a little more information on this here:
https://github.com/tidyverse/dplyr/issues/6469

I don't think we have enough experience with it yet to really give it its own tag or anything, so for now I don't think there is much else to do, but we will revisit if this question comes up a lot.
