### ISSUE TITLE
Should `between()` recycle `x` of size 1 to size of `left` and `right`?

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dplyr#6887]
My use case was a tibble with dates and a local date variable (e.g. the current date) and filter for rows where the date falls between start and end date.

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  start_date = as.Date(c("2023-01-01", "2023-01-02")),
  end_date = as.Date("2023-01-04", "2023-01-06"),
)

dplyr::between(
  as.Date("2023-01-01"),
  df$start_date,
  df$end_date
)
#> Error in `dplyr::between()`:
#> ! Can't recycle `left` (size 2) to size 1.
#> Backtrace:
#>     ▆
#>  1. ├─dplyr::between(as.Date("2023-01-01"), df$start_date, df$end_date)
#>  2. │ └─vctrs::vec_recycle_common(!!!args, .size = vec_size(x))
#>  3. └─vctrs:::stop_recycle_incompatible_size(...)
#>  4.   └─vctrs:::stop_vctrs(...)
#>  5.     └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = call)
```

<sup>Created on 2023-07-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I feel like this is a case where manual recycling to the size of left/right actually makes the intention clearer.

https://github.com/tidyverse/dplyr/pull/6260 is where we implemented `between()`, and i made a very conscious decision to cast to the type and size of `x` there. We had to walk back the type casting in https://github.com/tidyverse/dplyr/pull/6482 because it broke too many revdeps, but I still like the size casting.

To me `x` is the "primary input" here, and you should always be able to expect that the size of `x` going in is the same as the size of the result coming out. https://tidydesign.substack.com/p/argument-ordering

I don't think I'd want to give up this invariant for this somewhat rare (at least i think so) case

**Comment by DavisVaughan** [comment]
I think the 99% case is made up of:
- `left` and `right` are size 1 and recycled to size of `x`
- `x`, `left`, and `right` are all the same size

Anything else is considered an error for the 99% case, and I think you definitely want to see those errors, so something like `between(1, 0, integer())` should definitely be an error in my head over recycling to a common size of `0`.

So yea I think we should keep the current behavior of recycling to the size of `x`
