### ISSUE TITLE
 Confirm if `dplyr::across` can pass same length of vector to  `.names` 

### ISSUE THREAD

**Issue by ynsec37** [tidyverse/dplyr#6895]
Dear developer,

I found the below example work well but no related description in current [official document](https://dplyr.tidyverse.org/reference/across.html).

> .names	 A glue specification that describes how to name the output columns. This can use {.col} to stand for the selected column name, and {.fn} to stand for the name of the function being applied. The default (NULL) is equivalent to "{.col}" for the single function case and "{.col}_{.fn}" for the case where a list is used for .fns.

I just want to confirm whether this way is right or accepted, especilly when the new variable names can not simply be computed by `{.col}` or `{.fn}`

```r
library(dplyr, warn.conflicts = FALSE)

df <- tibble::tibble(a = 1, b = 2, c = 3)

cols <- c("a", "b", "c")
new_cols <- c("x", "y", "z")

df %>%
  mutate(across(
    .cols = all_of(cols),
    .fns = ~ .x + 10,
    .names = "{new_cols}"
  ))
#> # A tibble: 1 × 6
#>       a     b     c     x     y     z
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1     2     3    11    12    13
```
Thank very much for your reply.

**Comment by moodymudskipper** [comment]
Since the doc says it's a glue specification I believe the behavior is accepted (though happy to see it confirmed), but maybe the intent might be made clearer by either of those 2, though these might also slightly bite into the undocumented territory. 

```
cols <- c("a", "b", "c")
new_cols <- c("x", "y", "z")

df %>%
  mutate(
    across(
    .cols = all_of(cols),
    .fns = ~ .x + 10
  ) %>% set_names(new_cols)
)

df %>%
  mutate(
    across(
      .cols = all_of(set_names(cols, new_cols)),
      .fns = ~ .x + 10
    )
  )
```

The former uses the fact that across returns a data frame, so should be stable, unless `across()` is changed to only be recognised at the top level in dplyr verbs (it's not very clear from the doc if only top level is expected).

The latter is not 100% documented either but pretty close through #6655
