### ISSUE TITLE
Request for alias functions for relationship = '' join parameter

### ISSUE THREAD

**Issue by jmuhlenkamp** [tidyverse/dplyr#6941]
Hi all!

I really love the new `relationship` parameter within dplyr join functions as it has streamlined a lot of my pre/post-join sanity checks.

I was coding today and found myself typing `relationship = ` for the seemingly thousandth time when I had the idea that an alias here would be really useful for me (and thus likely for others as well).  It'd be faster to write the code & would result in less unnecessary multi-line wrapping for simple joins.

Here's my proposal for consideration.

*one-to-one 4 additional character alias*
```r
left_join(..., relationship = 'one-to-one')
left_join_oto(...)
```

*one-to-many 4 additional character alias*
```r
left_join(..., relationship = 'one-to-many')
left_join_otm(...)
```

*one-to-many 4 additional character alias*
```r
left_join(..., relationship = 'many-to-one')
left_join_mto(...)
```

*many-to-many 4 additional character alias*
```r
left_join(..., relationship = 'many-to-many')
left_join_mtm(...)
```

I'd be happy to attempt a PR for this feature, but first would want to know if such a feature would be accepted provided it was coded properly with unit tests, documentation, etc.  I'd also be happy if someone else just implemented it, but happy to help anyway I can.

Thoughts on this proposed feature?  Dead on arrival or something that would be considered?

Thanks!
Jason

**Comment by DavisVaughan** [comment]
It's a nice idea, but we try to keep the footprint of dplyr as small as possible to make it less overwhelming for newcomers to learn. Since we'd also have to do this for right/inner/full joins, I think that would result in too many functions, so I think that makes it dead on arrival.

Feel free to implement it yourself in your own personal package though! That sounds like a nice set of tools if this is something you use a lot.
