### ISSUE TITLE
Unexpected behavior with `coalesce()` on matrices

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/dplyr#6954]
`dplyr::coalesce()` does not behave as expected with matrices... given that matrices are glorified vectors I guess this is a bug...?
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

m1 <- matrix(letters[1:4], nrow = 2)
m2 <- matrix(letters[1:4], nrow = 2)


m1[1] <- NA_character_
m1
#>      [,1] [,2]
#> [1,] NA   "c" 
#> [2,] "b"  "d"
m2
#>      [,1] [,2]
#> [1,] "a"  "c" 
#> [2,] "b"  "d"
dplyr::coalesce(m1, m2)
#>      [,1] [,2]
#> [1,] NA   "c" 
#> [2,] "b"  "d"
dplyr::coalesce(as.vector(m1), as.vector(m2))
#> [1] "a" "b" "c" "d"
dplyr::coalesce(m1[1:2,], m2[1:2,])
#>      [,1] [,2]
#> [1,] NA   "c" 
#> [2,] "b"  "d"
dplyr::coalesce(m1[1:2,1], m2[1:2,1])
#> [1] "a" "b"

dplyr::coalesce(m1[1,1], m2[1,1])
#> [1] "a"
dplyr::coalesce(m1[1,1, drop = FALSE], m2[1,1, drop = FALSE])
#>      [,1]
#> [1,] "a"
dplyr::coalesce(m1[1, , drop = FALSE], m2[1, , drop = FALSE])
#>      [,1] [,2]
#> [1,] NA   "c"
dplyr::coalesce(m1[1, , drop = TRUE], m2[1, , drop = TRUE])
#> [1] "a" "c"
```

<sup>Created on 2023-11-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
What you are seeing is the result of the {vctrs} definition of "missing" for a matrix. For matrices and data frames, a "missing" row is one where every element in the row is missing. If any elements have values, it is not a missing row. 

If at least 1 element in the row is missing, it is considered "incomplete" but not necessarily "missing".

`coalesce()` only replaces "missing" rows in matrices and data frames, so that is why it doesn't do anything in your example.

Keep in mind that dplyr/vctrs aren't really full blown matrix packages, they are more intended for vectors and data frames, with support for matrices that had to be defined in a way that allowed it to use the same API as 1d vectors, and that resulted in the behavior you see here.

``` r
library(dplyr, warn.conflicts = FALSE)

m1 <- matrix(letters[1:4], nrow = 2)
m2 <- matrix(letters[1:4], nrow = 2)
m3 <- matrix(letters[1:4], nrow = 2)

m1[1] <- NA_character_
m2[1] <- NA_character_
m2[3] <- NA_character_

m1
#>      [,1] [,2]
#> [1,] NA   "c" 
#> [2,] "b"  "d"
m2
#>      [,1] [,2]
#> [1,] NA   NA  
#> [2,] "b"  "d"

# m1's first row isn't considered "missing" b/c there is some data there
vctrs::vec_detect_missing(m1)
#> [1] FALSE FALSE
vctrs::vec_detect_missing(m2)
#> [1]  TRUE FALSE

# m1's first row is considered incomplete, because it has at least 1 NA
vctrs::vec_detect_complete(m1)
#> [1] FALSE  TRUE
vctrs::vec_detect_complete(m2)
#> [1] FALSE  TRUE

# coalesce only replaces missing rows, so it "works" on m2 but not m1
dplyr::coalesce(m1, m3)
#>      [,1] [,2]
#> [1,] NA   "c" 
#> [2,] "b"  "d"
dplyr::coalesce(m2, m3)
#>      [,1] [,2]
#> [1,] "a"  "c" 
#> [2,] "b"  "d"
```

<sup>Created on 2023-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ramiromagno** [comment]
Hi @DavisVaughan:

Thank you for the explanation.

Perhaps this special meaning of missingness could be introduced in the documentation of `dplyr::coalesce()`?
