### ISSUE TITLE
Feature Request: Intuitive DataFrame Transposition Functionality in dplyr

### ISSUE THREAD

**Issue by hsalberti** [tidyverse/dplyr#6958]
Brief description of the problem:

Transposing a DataFrame in dplyr currently requires a combination of pivot_longer() and pivot_wider() functions. This process is not as straightforward as using the base R t() function and can be confusing for users, especially those new to dplyr or coming from a base R background. An intuitive, one-step transposition function would greatly simplify the data manipulation process in dplyr.

Expected output:

A new function, possibly named transpose_df(), that allows users to transpose a DataFrame in a single step, mirroring the simplicity and ease of use of the base R t() function.

----------------------------------------------------------------------------------------
library(dplyr)
library(tidyr)

# Sample dataframe
df <- tibble::tibble(
  x = 1:3,
  y = 4:6,
  z = 7:9
)

# Current method for transposing in dplyr/tidyr
transposed_df <- df %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value") %>%
  pivot_wider(names_from = "variable", values_from = "value")

# Print the transposed dataframe
print(transposed_df)

**Comment by philibe** [comment]
Your example doesn't work.

This works:
- `data.frame(t(df),row.names = names(df))`
- `df %>% t %>% data.frame(row.names = names(df))`

```R
  X1 X2 X3
x  1  2  3
y  4  5  6
z  7  8  9
```

**Comment by DavisVaughan** [comment]
We don't believe a data frame transpose mechanism is that useful because data frames can have multiple column types, but a transpose requires all column types to be forced into the same type.

If you need a true transpose operation, typically the best and most efficient thing to do is to convert to a single type matrix and use `t()`. That will be way faster than anything we could do with multi type data frame columns, and is really the only well defined way to do this
