### ISSUE TITLE
dplyr 1.1.4 breaks on empty dataframes constructed from matrices

### ISSUE THREAD

**Issue by john-b-edwards** [tidyverse/dplyr#7004]
Previous versions of dplyr would allow you to manipulate empty dataframes that had been constructed from empty matrices, e.g.

```r
packageurl <- "https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_1.1.3.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
#> Installing package into 'C:/Users/edwar/Documents/R/win-library/4.1'
#> (as 'lib' is unspecified)
packageVersion('dplyr')
#> [1] '1.1.3'
as.data.frame(matrix(nrow = 0, ncol = 0)) |> dplyr::slice(1)
#> data frame with 0 columns and 0 rows
```

In dplyr 1.1.4, this code causes an internal error:

```r
packageurl <- "https://cran.r-project.org/src/contrib/dplyr_1.1.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
#> Installing package into 'C:/Users/edwar/Documents/R/win-library/4.1'
#> (as 'lib' is unspecified)
packageVersion('dplyr')
#> [1] '1.1.4'
as.data.frame(matrix(nrow = 0, ncol = 0)) |> dplyr::slice(1)
#> Error: Internal error: `template` must have a `names` attribute.
```

Both versions are able to reliably manipulate empty dataframes that were not constructed from matrices (e.g. `data.frame() |> dplyr::slice(1)` works just fine).

**Comment by DavisVaughan** [comment]
This has been fixed upstream in base R https://github.com/wch/r-source/commit/ae3f49fd3181b0c6b3b9b4bf646ab378c1a3316f

For TDD, here is what I think we need to do to finish up the dplyr side. The changes take place here:
https://github.com/tidyverse/dplyr/blob/d69802224a1df16d7a795ce313880116ea62ed6e/R/data-mask.R#L14

We need to switch from `names2()` to `names()` so we can check for any issues in the names and throw an error rather than having rlang "repair" them for us. We need to check for 2 things:
- `NULL` names resulting from `names()`
- `NA` names resulting from `names()`

Both of these are typically "repaired" by rlang

```r
names <- names(data)

if (is.null(names)) {
  abort("Can't transform a data frame with `NULL` names.")
}
if (vec_any_missing(names)) {
  abort("Can't transform a data frame with missing names.")
}

names <- chr_unserialise_unicode(names)
```
