### ISSUE TITLE
Relocate multiple columns in a pairwise fashion

### ISSUE THREAD

**Issue by mbcann01** [tidyverse/dplyr#7011]
I would find it useful to be able to relocate multiple columns at once in a pairwise fashion with a set of columns passed to .before or .after.

```{r}
# Example data
df <- tibble(
  a = c(0, 1, 0),
  b = c(1, 2, 1),
  c = c(1, 1, 0)
) |> 
  mutate(
    a_f = factor(a, 0:1, c("No", "Yes")),
    b_f = factor(b, 1:2, c("First", "Second")),
    c_f = factor(c, 0:1, c("No", "Yes"))
  )
```
```
# A tibble: 3 × 6
      a     b     c a_f   b_f    c_f  
  <dbl> <dbl> <dbl> <fct> <fct>  <fct>
1     0     1     1 No    First  Yes  
2     1     2     1 Yes   Second Yes  
3     0     1     0 No    First  No 
```

Ideally, this code:

```{r}
df |> relocate(c(a_f, b_f, c_f), .after = c(a, b, c))
```

Would produce this result:

```
# A tibble: 3 × 6
      a a_f       b b_f        c c_f  
  <dbl> <fct> <dbl> <fct>  <dbl> <fct>
1     0 No        1 First      1 Yes  
2     1 Yes       2 Second     1 Yes  
3     0 No        1 First      0 No 
```

Instead of needing this code:

```{r}
df |> 
  relocate(a_f, .after = a) |> 
  relocate(b_f, .after = b) |> 
  relocate(c_f, .after = c)
```

Thanks for your time and consideration!

**Comment by DavisVaughan** [comment]
I appreciate the idea, but I think it has a high likelihood to accidentally be confusing, like if `.after = starts_with("foo")` returns 1 column in some cases, but 3 columns in other cases, and all of a sudden the 3 column version does something you weren't expecting it to (the pairwise relocating). Rather than tweaking tidyselect in any way to try and support this safely, I think it is probably best to just keep the current simpler implementation

**Comment by mbcann01** [comment]
Got it! Thank you for taking the time to consider the idea and write a response!
