### ISSUE TITLE
Feature request: global option for summarise .groups setting

### ISSUE THREAD

**Issue by wkumler** [tidyverse/dplyr#7067]
I'd like to make a feature request for a new global option that controls the behavior of `dplyr::summarise` with respect to the `.groups` argument. There's been [some discussion](https://stackoverflow.com/questions/62140483/how-to-interpret-dplyr-message-summarise-regrouping-output-by-x-override) around the `.groups` argument before and there's been a lot of [frustration with the unnecessary warning messages](https://forum.posit.co/t/summarise-has-grouped-output-by-x-you-can-override-using-the-groups-argument/174520). I agree with the author [here](https://forum.posit.co/t/6-months-later-the-groups-argument-in-summarise-and-the-familiar-warning-message/106555) that the default behavior that's most helpful for me is always dropping the grouping after a summarise.

There's two reasons for this. First, I very rarely chain summarise operations one after another. In the rare case that I desire this kind of nested calculation with a summarise piped directly into an additional summarise with the last set of groups dropped, I want the new set of groups to be explicit instead of implicit and typically write syntactic sugar of an additional `group_by` instead. Secondly, the idea of the *order* of the groups mattering is absurd to me. I don't write my code with a sense of "biggest group first, then the next biggest one, etc.". My groups are instead non-hierarchical and simply categories within which I'd like something calculated. Often times I actually move the opposite direction where I filter down to a single manageable working example to mimic a single group, then remove the filters and add additional groups to the end of the `group_by` call once I'm happy with the output. Unfortunately, adding groups to the *end* of the call without specifying `.groups` every time changes the behavior and has caused me more than one headache.

It seems like a relatively friction-free way of handling this would be the creation of a new global option similar to the existing `options(dplyr.summarise.inform = FALSE)` that controls this default behavior. That way old code isn't broken but it's a single line intervention (e.g. `options(dplyr.summarise.groups = "drop")`) at the top of the script that makes it clear what the behavior is throughout.

I'm aware of the "correct" way to do this by adding `.groups="drop"` explicitly to every single `summarise` I use as well as workarounds such as ungrouping after each call (unhelpful because the message is still thrown and it's an additional line of code), defining a new `summarise_drop` function that implements this behavior, or using the `.by` argument instead of the `group_by` function. All of these are far more annoying than setting a global variable at the top of my script that controls the default behavior.

**Comment by DavisVaughan** [comment]
> the default behavior that's most helpful for me is always dropping the grouping after a summarise

I completely agree. That is what we implemented `.by` for. It is an explicit call out in your code that you want "temporary grouping" for just this operation. I highly suggest that you use it if you like this behavior.

---

`options(dplyr.summarise.inform = FALSE)` is great as a global option because it _doesn't change the results_. So even if you've put it in your hidden personal `.Rprofile`, you and your colleague will get the same results if you run the same script.

With `options(dplyr.summarise.groups = "drop")`, that's not the case. That is a global option that has the ability to _change the output type_ of `summarise()`, and that is something that we strive extremely hard to avoid in the tidyverse. It can be extremely confusing if you put this in your `.Rprofile`, hand off the script to someone else, and now all of the sudden they don't get the same results as you and now you have a tough bug to track down.

So we believe the best thing to do is to write all new code with `.by` if you prefer the "drop" behavior, as most people seem to. For old code, migrate over to `.by` as you see fit, or add `.groups = "drop"`, or just leave it alone if its been working fine without any issues!
