### ISSUE TITLE
`if_else()` coerces `NA` as `list(NULL)` when the `false` argument is a list

### ISSUE THREAD

**Issue by arnaudgallou** [tidyverse/dplyr#7076]
See this example:

``` r
dplyr::if_else(
  TRUE,
  NA,
  list("foo")
)
#> [[1]]
#> NULL

dplyr::if_else(
  TRUE,
  NA,
  "foo"
)
#> [1] NA
```

<sup>Created on 2024-08-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Is this the desired behavior? I'd expect `if_else()` to return `list(NA)` in the first case.

**Comment by arnaudgallou** [comment]
In the end, that might be the desired behavior but maybe that could be mentioned in `if_else()` (and possibly in `vctrs::vec_cast_common()`) that `NA` will be changed to `NULL` in that case.

**Comment by DavisVaughan** [comment]
It is expected behavior. The "missing" type for a list is `list(NULL)`, so `NA` is cast to that when we compute the common type.

There's really no good place to put docs for this, as it is quite specific and not that common, but I'll add an example to `vec_init()` with a list to show that the NA element for a list is `NULL`
