### ISSUE TITLE
Why value in `mutate` ifelse custom condition is treated as a vector

### ISSUE THREAD

**Issue by maciekbanas** [tidyverse/dplyr#7107]
I can not understand why the value in the example below is treated as a vector and not scalar, when I try to put a simple string condition:

```
example_data <- data.frame(
  col_1 = c("John Test", "bobtest", "John Test"),
  col_2 = c(NA, "Bob Test", NA)
)

has_many_words <- function(char) {
  length(stringr::str_split_1(char, " ")) > 1
}

dplyr::mutate(
  example_data,
  col_2 = ifelse(is.na(col_2) & has_many_words(col_1), col_1, col_2)
)
```
Results in error:
![Image](https://github.com/user-attachments/assets/e47c0004-c340-4275-8a07-1161506fa508)

My question is if only way to approach `mutate` with customized condition is with `map` iterator? This works, though does not look nice:
```
dplyr::mutate(
  example_data,
  col_2 = purrr::map2(col_1, col_2, function(x, y) {
    ifelse(is.na(y) & has_many_words(x), x, y)
  })
)
```
Is there any other way, am I getting something wrong?

**Comment by joranE** [comment]
Both `ifelse` & `dplyr::if_else` expect a vector, not a scalar, condition; i.e. `mutate` doesn't do any "looping" for you over values in the column. So the expected use of `ifelse` or `dplyr::if_else` is that your condition is already vectorized, and hence the looping happens via that vectorization. 

In this case I believe you just need to switch to `str_split` and use `lengths()` rather than `length`:

```
has_many_words <- function(char) {
  lengths(stringr::str_split(char, " ")) > 1
}
```

**Comment by DavisVaughan** [comment]
I think @joranE is right that the main issue is that your `has_many_words()` function isn't vectorized quite right
